#!/usr/bin/env python3
"""
Create hockey/hockey_skaters_master.csv from Dobber skater rankings.
'y' in the source data indicates a defenseman (D); otherwise Forward (F).
Run recalculate.py afterward to compute Average Rank / Rank Variance.
"""

import csv
import os

# (rank, name, team, is_defense)
DOBBER_DATA = [
    (1, "Connor McDavid", "EDM", False),
    (2, "Nathan MacKinnon", "COL", False),
    (3, "Nikita Kucherov", "TBL", False),
    (4, "Leon Draisaitl", "EDM", False),
    (5, "Macklin Celebrini", "SJS", False),
    (6, "Connor Bedard", "CHI", False),
    (7, "Mikko Rantanen", "DAL", False),
    (8, "David Pastrnak", "BOS", False),
    (9, "Martin Necas", "COL", False),
    (10, "Mitch Marner", "VGK", False),
    (11, "Cale Makar", "COL", True),
    (12, "Kirill Kaprizov", "MIN", False),
    (13, "Jack Eichel", "VGK", False),
    (14, "Jason Robertson", "DAL", False),
    (15, "Kyle Connor", "WPG", False),
    (16, "Nick Suzuki", "MON", False),
    (17, "Jack Hughes", "NJD", False),
    (18, "Tim Stutzle", "OTT", False),
    (19, "Auston Matthews", "TOR", False),
    (20, "Quinn Hughes", "MIN", True),
    (21, "William Nylander", "TOR", False),
    (22, "Wyatt Johnston", "DAL", False),
    (23, "Mark Scheifele", "WPG", False),
    (24, "Sam Reinhart", "FLA", False),
    (25, "Cole Caufield", "MON", False),
    (26, "Lane Hutson", "MON", True),
    (27, "Sebastian Aho", "CAR", False),
    (28, "Tage Thompson", "BUF", False),
    (29, "Jake Guentzel", "TBL", False),
    (30, "Lucas Raymond", "DET", False),
    (31, "Zach Werenski", "CBJ", True),
    (32, "Matt Boldy", "MIN", False),
    (33, "Evan Bouchard", "EDM", True),
    (34, "Brandon Hagel", "TBL", False),
    (35, "Artemi Panarin", "NYR", False),
    (36, "Clayton Keller", "UTA", False),
    (37, "Ivan Demidov", "MON", False),
    (38, "Sidney Crosby", "PIT", False),
    (39, "Jesper Bratt", "NJD", False),
    (40, "Travis Konecny", "PHI", False),
    (41, "Rasmus Dahlin", "BUF", True),
    (42, "Alex DeBrincat", "DET", False),
    (43, "Mark Stone", "VGK", False),
    (44, "Leo Carlsson", "ANA", False),
    (45, "Brady Tkachuk", "OTT", False),
    (46, "Cutter Gauthier", "ANA", False),
    (47, "Kirill Marchenko", "CBJ", False),
    (48, "Drake Batherson", "OTT", False),
    (49, "Dylan Larkin", "DET", False),
    (50, "Roope Hintz", "DAL", False),
    (51, "Dylan Strome", "WAS", False),
    (52, "Dylan Guenther", "UTA", False),
    (53, "Brad Marchand", "FLA", False),
    (54, "Matthew Tkachuk", "FLA", False),
    (55, "Trevor Zegras", "PHI", False),
    (56, "Troy Terry", "ANA", False),
    (57, "Josh Morrissey", "WPG", True),
    (58, "Brayden Point", "TBL", False),
    (59, "Adam Fantilli", "CBJ", False),
    (60, "Logan Cooley", "UTA", False),
    (61, "Ryan Nugent-Hopkins", "EDM", False),
    (62, "Mathew Barzal", "NYI", False),
    (63, "Filip Forsberg", "NSH", False),
    (64, "Will Smith", "SJS", False),
    (65, "Adrian Kempe", "LAK", False),
    (66, "Juraj Slafkovsky", "MON", False),
    (67, "Matthew Knies", "TOR", False),
    (68, "Tomas Hertl", "VGK", False),
    (69, "Nico Hischier", "NJD", False),
    (70, "Morgan Geekie", "BOS", False),
    (71, "Andrei Svechnikov", "CAR", False),
    (72, "Robert Thomas", "STL", False),
    (73, "Tom Wilson", "WAS", False),
    (74, "Miro Heiskanen", "DAL", True),
    (75, "Mika Zibanejad", "NYR", False),
    (76, "Elias Pettersson", "VAN", False),
    (77, "Brock Nelson", "COL", False),
    (78, "Anton Lundell", "FLA", False),
    (79, "Alex Tuch", "BUF", False),
    (80, "Seth Jarvis", "CAR", False),
    (81, "Matvei Michkov", "PHI", False),
    (82, "Noah Dobson", "MON", True),
    (83, "Jake Sanderson", "OTT", True),
    (84, "Nikolaj Ehlers", "CAR", False),
    (85, "Adam Fox", "NYR", True),
    (86, "Gabriel Vilardi", "WPG", False),
    (87, "Darren Raddysh", "TBL", True),
    (88, "Nick Schmaltz", "UTA", False),
    (89, "JJ Peterka", "UTA", False),
    (90, "Matty Beniers", "SEA", False),
    (91, "Mikhail Sergachev", "UTA", True),
    (92, "Dylan Cozens", "OTT", False),
    (93, "Matthew Schaefer", "NYI", True),
    (94, "Alex Ovechkin", "WAS", False),
    (95, "Moritz Seider", "DET", True),
    (96, "John Tavares", "TOR", False),
    (97, "William Eklund", "SJS", False),
    (98, "Pavel Dorofeyev", "VGK", False),
    (99, "J.T. Miller", "NYR", False),
    (100, "Bo Horvat", "NYI", False),
    (101, "Beckett Sennecke", "ANA", False),
    (102, "Jakob Chychrun", "WAS", True),
    (103, "Kevin Fiala", "LAK", False),
    (104, "Carter Verhaeghe", "FLA", False),
    (105, "Aliaksei Protas", "WAS", False),
    (106, "Zach Hyman", "EDM", False),
    (107, "Shayne Gostisbehere", "CAR", True),
    (108, "Ivan Barbashev", "VGK", False),
    (109, "Joel Eriksson Ek", "MIN", False),
    (110, "Marco Rossi", "VAN", False),
    (111, "Ryan O'Reilly", "NSH", False),
    (112, "Elias Lindholm", "BOS", False),
    (113, "Quinton Byfield", "LAK", False),
    (114, "Aleksander Barkov", "FLA", False),
    (115, "Evgeni Malkin", "PIT", False),
    (116, "Luke Evangelista", "NSH", False),
    (117, "Charlie McAvoy", "BOS", True),
    (118, "Sam Bennett", "FLA", False),
    (119, "Shea Theodore", "VGK", True),
    (120, "Ryan McLeod", "BUF", False),
    (121, "Valeri Nichushkin", "COL", False),
    (122, "Bryan Rust", "PIT", False),
    (123, "Owen Tippett", "PHI", False),
    (124, "Erik Karlsson", "PIT", True),
    (125, "Jack Quinn", "BUF", False),
    (126, "John Carlson", "WAS", True),
    (127, "Connor McMichael", "WAS", False),
    (128, "Josh Doan", "BUF", False),
    (129, "Timo Meier", "NJD", False),
    (130, "Vincent Trocheck", "NYR", False),
    (131, "Mason McTavish", "ANA", False),
    (132, "Anthony Cirelli", "TBL", False),
    (133, "Frank Nazar", "CHI", False),
    (134, "Artturi Lehkonen", "COL", False),
    (135, "Jared McCann", "SEA", False),
    (136, "Tyler Toffoli", "SJS", False),
    (137, "Ryan Leonard", "WAS", False),
    (138, "Logan Stankoven", "CAR", False),
    (139, "Nazem Kadri", "CGY", False),
    (140, "Dylan Holloway", "STL", False),
    (141, "Jordan Kyrou", "STL", False),
    (142, "Patrick Kane", "DET", False),
    (143, "Steven Stamkos", "NSH", False),
    (144, "Vince Dunn", "SEA", True),
    (145, "Thomas Harley", "DAL", True),
    (146, "Jackson Blake", "CAR", False),
    (147, "Luke Hughes", "NJD", True),
    (148, "Mikael Granlund", "ANA", False),
    (149, "Dawson Mercer", "NJD", False),
    (150, "Tyler Bertuzzi", "CHI", False),
    (151, "Artyom Levshunov", "CHI", True),
    (152, "Claude Giroux", "OTT", False),
    (153, "Shane Pinto", "OTT", False),
    (154, "Filip Hronek", "VAN", True),
    (155, "Roman Josi", "NSH", True),
    (156, "Zach Benson", "BUF", False),
    (157, "Pavel Zacha", "BOS", False),
    (158, "Jackson Lacombe", "ANA", True),
    (159, "Michael Misa", "SJS", False),
    (160, "Alexis Lafreniere", "NYR", False),
    (161, "Matt Coronato", "CGY", False),
    (162, "Eeli Tolvanen", "SEA", False),
    (163, "Brandt Clarke", "LAK", True),
    (164, "Bowen Byram", "BUF", True),
    (165, "Victor Hedman", "TBL", True),
    (166, "Anthony Mantha", "PIT", False),
    (167, "Kent Johnson", "CBJ", False),
    (168, "Dmitri Voronkov", "CBJ", False),
    (169, "Simon Nemec", "NJD", True),
    (170, "Mavrik Bourque", "DAL", False),
    (171, "Bobby Brink", "PHI", False),
    (172, "Tyson Foerster", "PHI", False),
    (173, "Matt Duchene", "DAL", False),
    (174, "Rickard Rakell", "PIT", False),
    (175, "Pavel Buchnevich", "STL", False),
    (176, "Charlie Coyle", "CBJ", False),
    (177, "Fraser Minten", "BOS", False),
    (178, "Berkly Catton", "SEA", False),
    (179, "Shane Wright", "SEA", False),
    (180, "Rasmus Andersson", "VGK", True),
    (181, "Will Cuylle", "NYR", False),
    (182, "Brock Boeser", "VAN", False),
    (183, "Seth Jones", "FLA", True),
    (184, "Cole Sillinger", "CBJ", False),
    (185, "Chandler Stephenson", "SEA", False),
    (186, "Morgan Frost", "CGY", False),
    (187, "Casey Mittelstadt", "BOS", False),
    (188, "Brock Faber", "MIN", True),
    (189, "Jamie Drysdale", "PHI", True),
    (190, "Zayne Parekh", "CGY", True),
    (191, "Pierre-Luc Dubois", "WAS", False),
    (192, "Alex Laferriere", "LAK", False),
    (193, "Kaapo Kakko", "SEA", False),
    (194, "Alexander Wennberg", "SJS", False),
    (195, "Jonathan Huberdeau", "CGY", False),
    (196, "Benjamin Kindel", "PIT", False),
    (197, "Jordan Eberle", "SEA", False),
    (198, "Zack Bolduc", "MON", False),
    (199, "Mackie Samoskevich", "FLA", False),
    (200, "Josh Norris", "BUF", False),
    (201, "Sean Monahan", "CBJ", False),
    (202, "Patrik Laine", "MON", False),
    (203, "Morgan Rielly", "TOR", True),
    (204, "Konsta Helenius", "BUF", False),
    (205, "Jake Neighbours", "STL", False),
    (206, "Axel Sandin Pellikka", "DET", True),
    (207, "Conor Garland", "VAN", False),
    (208, "Alex Newhook", "MON", False),
    (209, "Andre Burakovsky", "CHI", False),
    (210, "Nicholas Robertson", "TOR", False),
    (211, "Denton Mateychuk", "CBJ", True),
    (212, "Barrett Hayton", "UTA", False),
    (213, "Cole Perfetti", "WPG", False),
    (214, "Tij Iginla", "UTA", False),
    (215, "Teuvo Teravainen", "CHI", False),
    (216, "Alexander Nikishin", "CAR", True),
    (217, "Matias Maccelli", "TOR", False),
    (218, "Ryan Donato", "CHI", False),
    (219, "Zeev Buium", "VAN", True),
    (220, "Mats Zuccarello", "MIN", False),
    (221, "Marcus Johansson", "MIN", False),
    (222, "Yegor Chinakhov", "PIT", False),
    (223, "Kirby Dach", "MON", False),
    (224, "Justin Sourdif", "WAS", False),
    (225, "Igor Chernyshov", "SJS", False),
    (226, "Sean Couturier", "PHI", False),
    (227, "Emil Heineman", "NYI", False),
    (228, "Cole Hutson", "WAS", True),
    (229, "Mason Marchment", "CBJ", False),
    (230, "Anton Frondell", "CHI", False),
    (231, "Maxim Shabanov", "NYI", False),
    (232, "Roman Kantserov", "CHI", False),
    (233, "Tyler Seguin", "DAL", False),
    (234, "Jack Roslovic", "EDM", False),
    (235, "Noah Hanifin", "VGK", True),
    (236, "Oliver Moore", "CHI", False),
    (237, "Collin Graf", "SJS", False),
    (238, "Thomas Chabot", "OTT", True),
    (239, "Justin Brazeau", "PIT", False),
    (240, "Ridly Greig", "OTT", False),
    (241, "Easton Cowan", "TOR", False),
    (242, "Brady Martin", "NSH", False),
    (243, "Gabe Perreault", "NYR", False),
    (244, "Chris Kreider", "ANA", False),
    (245, "Bobby McMann", "TOR", False),
    (246, "Jiri Kulich", "BUF", False),
    (247, "James Hagens", "BOS", False),
    (248, "Porter Martone", "PHI", False),
    (249, "Jason Zucker", "BUF", False),
    (250, "Arseniy Gritsyuk", "NJD", False),
    (251, "Connor Zary", "CGY", False),
    (252, "Jimmy Snuggerud", "STL", False),
    (253, "Simon Holmstrom", "NYI", False),
    (254, "Noah Ostlund", "BUF", False),
    (255, "Sam Dickinson", "SJS", True),
    (256, "Oliver Ekman-Larsson", "TOR", True),
    (257, "Mike Matheson", "MON", True),
    (258, "Danila Yurov", "MIN", False),
    (259, "Andrew Cristall", "WAS", False),
    (260, "Tommy Novak", "PIT", False),
    (261, "Oliver Bjorkstrand", "TBL", False),
    (262, "Boone Jenner", "CBJ", False),
    (263, "Cole Eiserman", "NYI", False),
    (264, "Jonathan Lekkerimaki", "VAN", False),
    (265, "Michael Rasmussen", "DET", False),
    (266, "Michael Bunting", "NSH", False),
    (267, "Cayden Lindstrom", "CBJ", False),
    (268, "Brandon Montour", "SEA", True),
    (269, "Rutger McGroarty", "PIT", False),
    (270, "Matvei Gridin", "CGY", False),
    (271, "Kailer Yamamoto", "UTA", False),
    (272, "Oliver Kapanen", "MON", False),
    (273, "Anders Lee", "NYI", False),
    (274, "Matt Savoie", "EDM", False),
    (275, "Max Domi", "TOR", False),
    (276, "Marco Kasper", "DET", False),
    (277, "William Karlsson", "VGK", False),
    (278, "Roger McQueen", "ANA", False),
    (279, "K'Andre Miller", "CAR", True),
    (280, "Owen Power", "BUF", True),
    (281, "Caleb Desnoyers", "UTA", False),
    (282, "Nick Lardis", "CHI", False),
    (283, "Denver Barkey", "PHI", False),
    (284, "Ivan Miroshnichenko", "WAS", False),
    (285, "Vasily Podkolzin", "EDM", False),
    (286, "Isak Rosen", "BUF", False),
    (287, "Braeden Bowman", "VGK", False),
    (288, "Sean Durzi", "UTA", True),
    (289, "Teddy Stiga", "NSH", False),
    (290, "Gavin Brindley", "COL", False),
    (291, "Jani Nyman", "SEA", False),
    (292, "Jake O'Brien", "SEA", False),
    (293, "Sam Malinski", "COL", True),
    (294, "Devon Toews", "COL", True),
    (295, "Eetu Luostarinen", "FLA", False),
    (296, "Calum Ritchie", "NYI", False),
    (297, "Noah Cates", "PHI", False),
    (298, "Dalibor Dvorsky", "STL", False),
    (299, "Liam Greentree", "LAK", False),
    (300, "Emmitt Finnie", "DET", False),
]

SOURCE_COL = "Dobber (Mar 2026)"
FIELDNAMES = ["Player", "Position", "Age", SOURCE_COL, "Average Rank", "Rank Variance"]

out_path = os.path.join(os.path.dirname(__file__), "..", "hockey", "hockey_skaters_master.csv")
out_path = os.path.normpath(out_path)

rows = []
for rank, name, team, is_defense in DOBBER_DATA:
    rows.append({
        "Player": name,
        "Position": "D" if is_defense else "F",
        "Age": "",
        SOURCE_COL: rank,
        "Average Rank": "",
        "Rank Variance": "",
    })

with open(out_path, "w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=FIELDNAMES)
    writer.writeheader()
    writer.writerows(rows)

print(f"Wrote {len(rows)} skaters to {out_path}")
