#!/usr/bin/env python3
"""Merge Baseball America Top 500 Dynasty Rankings (Feb 2026) into baseball master CSV."""

import csv
import re
import unicodedata
import subprocess

MASTER_PATH = "baseball/baseball_rankings_master.csv"
NEW_COL = "Baseball America (Feb 2026)"

# All 500 Baseball America rankings (rank, name, pos, team, age)
# Age is None where blank in source; pos "RHP" normalized to "SP", "UT/P" kept as-is
BA_RANKINGS = [
    (1,   "Shohei Ohtani",           "UT/P", "LAD", 31.7),
    (2,   "Juan Soto",               "OF",   "NYM", 27.4),
    (3,   "Bobby Witt Jr.",          "SS",   "KCR", 25.8),
    (4,   "Tarik Skubal",            "SP",   "DET", 29.3),
    (5,   "Paul Skenes",             "SP",   "PIT", 23.8),
    (6,   "Elly De La Cruz",         "SS",   "CIN", 24.2),
    (7,   "Gunnar Henderson",        "SS",   "BAL", 24.7),
    (8,   "Corbin Carroll",          "OF",   "ARI", 25.6),
    (9,   "Julio Rodriguez",         "OF",   "SEA", 25.2),
    (10,  "Aaron Judge",             "OF",   "NYY", 33.9),
    (11,  "Junior Caminero",         "3B",   "TBR", 22.7),
    (12,  "Jackson Chourio",         "OF",   "MIL", 22.0),
    (13,  "Fernando Tatis Jr.",      "OF",   "SDP", 27.2),
    (14,  "Garrett Crochet",         "SP",   "BOS", 26.8),
    (15,  "Nick Kurtz",              "1B",   "ATH", 23.0),
    (16,  "Vladimir Guerrero Jr.",   "1B",   "TOR", 27.0),
    (17,  "Jose Ramirez",            "3B",   "CLE", None),  # age 18 in source is erroneous
    (18,  "Ronald Acuna Jr.",        "OF",   "ATL", 28.3),
    (19,  "Jazz Chisholm Jr.",       "2B",   "NYY", 28.1),
    (20,  "Kyle Tucker",             "OF",   "LAD", 29.2),
    (21,  "Konnor Griffin",          "SS",   "PIT", 19.9),
    (22,  "Wyatt Langford",          "OF",   "TEX", 24.3),
    (23,  "James Wood",              "OF",   "WAS", 23.5),
    (24,  "Roman Anthony",           "OF",   "BOS", 21.8),
    (25,  "Yordan Alvarez",          "OF",   "HOU", 28.7),
    (26,  "Yoshinobu Yamamoto",      "SP",   "LAD", 27.6),
    (27,  "Zach Neto",               "SS",   "LAA", 25.1),
    (28,  "Logan Gilbert",           "SP",   "SEA", 28.8),
    (29,  "Hunter Brown",            "SP",   "HOU", 27.5),
    (30,  "Francisco Lindor",        "SS",   "NYM", 32.3),
    (31,  "Kevin McGonigle",         "2B",   "DET", 21.6),
    (32,  "Pete Crow-Armstrong",     "OF",   "CHC", 24.0),
    (33,  "Jackson Merrill",         "OF",   "SDP", 22.9),
    (34,  "Manny Machado",           "3B",   "SDP", 33.7),
    (35,  "Cal Raleigh",             "C",    "SEA", 29.3),
    (36,  "Bryce Harper",            "1B",   "PHI", 33.4),
    (37,  "CJ Abrams",               "SS",   "WAS", 25.4),
    (38,  "Hunter Greene",           "SP",   "CIN", 26.6),
    (39,  "JJ Wetherholt",           "SS",   "STL", 23.5),
    (40,  "Pete Alonso",             "1B",   "BAL", 31.3),
    (41,  "Ketel Marte",             "2B",   "ARI", 32.4),
    (42,  "Rafael Devers",           "1B",   "SFG", 29.4),
    (43,  "Trea Turner",             "SS",   "PHI", 32.7),
    (44,  "Mookie Betts",            "SS",   "LAD", 33.4),
    (45,  "Trey Yesavage",           "SP",   "TOR", 22.6),
    (46,  "Cristopher Sanchez",      "SP",   "PHI", 29.3),
    (47,  "Joe Ryan",                "SP",   "MIN", 29.8),
    (48,  "Eury Perez",              "SP",   "MIA", 22.9),
    (49,  "Nolan McLean",            "SP",   "NYM", 24.7),
    (50,  "Kyle Schwarber",          "UT",   "PHI", 33.0),
    (51,  "Jesus Made",              "SS",   "MIL", 18.8),
    (52,  "Corey Seager",            "SS",   "TEX", 31.8),
    (53,  "Colt Emerson",            "SS",   "SEA", 20.7),
    (54,  "Matt Olson",              "1B",   "ATL", 31.9),
    (55,  "Riley Greene",            "OF",   "DET", 25.4),
    (56,  "Oneil Cruz",              "OF",   "PIT", 27.4),
    (57,  "Walker Jenkins",          "OF",   "MIN", 21.1),
    (58,  "Chris Sale",              "SP",   "ATL", 36.9),
    (59,  "Jacob deGrom",            "SP",   "TEX", 37.8),
    (60,  "George Kirby",            "SP",   "SEA", 28.1),
    (61,  "Logan Webb",              "SP",   "SFG", 29.3),
    (62,  "Samuel Basallo",          "C",    "BAL", 21.6),
    (63,  "Bryan Woo",               "SP",   "SEA", 26.1),
    (64,  "Chase Burns",             "SP",   "CIN", 23.2),
    (65,  "Spencer Strider",         "SP",   "ATL", 27.3),
    (66,  "Jacob Misiorowski",       "SP",   "MIL", 23.9),
    (67,  "Max Clark",               "OF",   "DET", 21.3),
    (68,  "Freddie Freeman",         "1B",   "LAD", 36.5),
    (69,  "William Contreras",       "C",    "MIL", 28.3),
    (70,  "Cody Bellinger",          "OF",   "NYY", 30.7),
    (71,  "Geraldo Perdomo",         "SS",   "ARI", 26.4),
    (72,  "Jackson Holliday",        "2B",   "BAL", 22.3),
    (73,  "Jeremy Pena",             "SS",   "HOU", 28.5),
    (74,  "Austin Riley",            "3B",   "ATL", 28.9),
    (75,  "Mason Miller",            "RP",   "SDP", 27.6),
    (76,  "Freddy Peralta",          "SP",   "MIL", 29.8),
    (77,  "Luke Keaschall",          "2B",   "MIN", 23.6),
    (78,  "Brice Turang",            "2B",   "MIL", 26.3),
    (79,  "Edward Florentino",       "OF",   "PIT", 19.3),
    (80,  "Randy Arozarena",         "OF",   "SEA", 31.0),
    (81,  "Brent Rooker",            "OF",   "ATH", 31.3),
    (82,  "Tyler Soderstrom",        "1B",   "ATH", 24.3),
    (83,  "Jordan Westburg",         "3B",   "BAL", 27.1),
    (84,  "Josh Naylor",             "1B",   "SEA", 28.8),
    (85,  "Vinnie Pasquantino",      "1B",   "KCR", 28.4),
    (86,  "Ben Rice",                "C",    "NYY", 27.1),
    (87,  "Aidan Miller",            "SS",   "PHI", 21.8),
    (88,  "Shea Langeliers",         "C",    "ATH", 28.3),
    (89,  "Agustin Ramirez",         "C",    "MIA", 24.5),
    (90,  "Jose Altuve",             "2B",   "HOU", 35.8),
    (91,  "Leo De Vries",            "SS",   "ATH", 19.4),
    (92,  "Jarren Duran",            "OF",   "BOS", 29.5),
    (93,  "Carson Benge",            "OF",   "NYM", 23.2),
    (94,  "Andy Pages",              "OF",   "LAD", 25.3),
    (95,  "Drake Baldwin",           "C",    "ATL", 24.9),
    (96,  "Cole Ragans",             "SP",   "KCR", 28.3),
    (97,  "Caleb Bonemer",           "SS",   "CWS", 20.4),
    (98,  "Blake Snell",             "SP",   "LAD", 33.3),
    (99,  "Bryce Rainer",            "SS",   "DET", 20.7),
    (100, "Lawrence Butler",         "OF",   "ATH", 25.7),
    (101, "Max Fried",               "SP",   "NYY", 32.2),
    (102, "Christian Yelich",        "OF",   "MIL", 34.3),
    (103, "Michael Harris II",       "OF",   "ATL", 25.0),
    (104, "Bo Bichette",             "SS",   "NYM", 28.0),
    (105, "Michael Busch",           "1B",   "CHC", 28.3),
    (106, "Seiya Suzuki",            "OF",   "CHC", 31.6),
    (107, "Bryce Eldridge",          "1B",   "SFG", 21.4),
    (108, "Matt Shaw",               "3B",   "CHC", 24.3),
    (109, "Sal Stewart",             "1B",   "CIN", 22.3),
    (110, "Cam Schlittler",          "SP",   "NYY", 25.1),
    (111, "Kyle Bradish",            "SP",   "BAL", 29.5),
    (112, "Jesus Luzardo",           "SP",   "PHI", 28.4),
    (113, "Dylan Cease",             "SP",   "TOR", 30.2),
    (114, "Andres Munoz",            "RP",   "SEA", 27.2),
    (115, "Tyler Glasnow",           "SP",   "LAD", 32.6),
    (116, "Emmet Sheehan",           "SP",   "LAD", 26.3),
    (117, "Gerrit Cole",             "SP",   "NYY", 35.5),
    (118, "MacKenzie Gore",          "SP",   "TEX", 27.1),
    (119, "Nick Pivetta",            "SP",   "SDP", 33.1),
    (120, "Michael King",            "SP",   "SD",  30.8),
    (121, "Nick Lodolo",             "SP",   "CIN", 28.1),
    (122, "Rainiel Rodriguez",       "C",    "STL", 19.2),
    (123, "Framber Valdez",          "SP",   "DET", 32.3),
    (124, "Kevin Gausman",           "SP",   "TOR", 35.2),
    (125, "Jhoan Duran",             "RP",   "PHI", 28.2),
    (126, "Edwin Diaz",              "RP",   "LAD", 30.6),
    (127, "Ozzie Albies",            "2B",   "ATL", 29.2),
    (128, "Maikel Garcia",           "3B",   "KCR", 26.0),
    (129, "Willy Adames",            "SS",   "SFG", 30.5),
    (130, "Alex Bregman",            "3B",   "CHC", 31.9),
    (131, "Byron Buxton",            "OF",   "MIN", 32.3),
    (132, "Josue De Paula",          "OF",   "LAD", 20.8),
    (133, "Royce Lewis",             "3B",   "MIN", 26.8),
    (134, "Cam Smith",               "OF",   "HOU", 23.1),
    (135, "Jacob Wilson",            "SS",   "ATH", 23.9),
    (136, "Eduardo Quintero",        "OF",   "LAD", 20.5),
    (137, "Isaac Paredes",           "3B",   "HOU", 27.1),
    (138, "Dylan Crews",             "OF",   "WAS", 24.1),
    (139, "Will Smith",              "C",    "LAD", 30.9),
    (140, "Kyle Manzardo",           "1B",   "CLE", 25.7),
    (141, "Jo Adell",                "OF",   "LAA", 26.9),
    (142, "Ivan Herrera",            "C",    "STL", 25.8),
    (143, "Cade Smith",              "RP",   "CLE", 23.9),
    (144, "Steven Kwan",             "OF",   "CLE", 28.5),
    (145, "Addison Barger",          "3B",   "TOR", 26.3),
    (146, "Luis Robert Jr.",         "OF",   "CWS", 28.6),
    (147, "Luis Pena",               "SS",   "MIL", 19.3),
    (148, "Teoscar Hernandez",       "OF",   "LAD", 33.4),
    (149, "Mike Trout",              "OF",   "LAA", 34.6),
    (150, "Sebastian Walcott",       "SS",   "TEX", 20.0),
    (151, "Thomas White",            "SP",   "MIA", 21.4),
    (152, "Spencer Schwellenbach",   "SP",   "ATL", 25.8),
    (153, "Jac Caglianone",          "OF",   "KCR", 23.1),
    (154, "Zack Wheeler",            "SP",   "PHI", 35.8),
    (155, "George Springer",         "OF",   "TOR", 36.5),
    (156, "Kyle Stowers",            "OF",   "MIA", 28.2),
    (157, "Yandy Diaz",              "1B",   "TBR", 34.6),
    (158, "Francisco Alvarez",       "C",    "NYM", 24.3),
    (159, "Bubba Chandler",          "SP",   "PIT", 23.5),
    (160, "Carlos Rodon",            "SP",   "NYY", 33.3),
    (161, "Carter Jensen",           "C",    "KCR", 22.7),
    (162, "Payton Tolle",            "SP",   "BOS", 23.3),
    (163, "Nathan Eovaldi",          "SP",   "TEX", 36.1),
    (164, "Jack Flaherty",           "SP",   "DET", 30.4),
    (165, "Sonny Gray",              "SP",   "BOS", 36.3),
    (166, "Travis Bazzana",          "2B",   "CLE", 23.5),
    (167, "Joshua Baez",             "OF",   "STL", 22.7),
    (168, "Ranger Suarez",           "SP",   "BOS", 30.6),
    (169, "Tanner Bibee",            "SP",   "CLE", 27.0),
    (170, "Ryan Waldschmidt",        "OF",   "ARI", 23.4),
    (171, "Ian Happ",                "OF",   "CHC", 31.6),
    (172, "Anthony Volpe",           "SS",   "NYY", 24.8),
    (173, "Brandon Nimmo",           "OF",   "TEX", 32.9),
    (174, "Mark Vientos",            "3B",   "NYM", 26.3),
    (175, "Zyhir Hope",              "OF",   "LAD", 21.2),
    (176, "Eugenio Suarez",          "3B",   "CIN", 34.7),
    (177, "Gavin Williams",          "SP",   "CLE", 26.7),
    (178, "Jonah Tong",              "SP",   "NYM", 22.8),
    (179, "Shane McClanahan",        "SP",   "TBR", 28.8),
    (180, "Zebby Matthews",          "SP",   "MIN", 25.8),
    (181, "Shane Baz",               "SP",   "BAL", 26.8),
    (182, "Luis Castillo",           "SP",   "SEA", 33.3),
    (183, "Shane Bieber",            "SP",   "TOR", 30.8),
    (184, "Edward Cabrera",          "SP",   "CHC", 27.9),
    (185, "Mike Sirota",             "OF",   "LAD", 22.8),
    (186, "Noelvi Marte",            "3B",   "CIN", 24.4),
    (187, "Matt Chapman",            "3B",   "SFG", 32.8),
    (188, "Gleyber Torres",          "2B",   "DET", 29.3),
    (189, "Brett Baty",              "3B",   "NYM", 26.3),
    (190, "Jordan Lawlar",           "SS",   "ARI", 23.7),
    (191, "Jonathan Aranda",         "1B",   "TBR", 27.8),
    (192, "Robbie Ray",              "SP",   "SFG", 34.4),
    (193, "Shota Imanaga",           "SP",   "CHC", 32.5),
    (194, "Bryce Miller",            "SP",   "SEA", 27.6),
    (195, "Josuar Gonzalez",         "SS",   "SFG", 18.4),
    (196, "Grayson Rodriguez",       "SP",   "LAA", 26.3),
    (197, "Sandy Alcantara",         "SP",   "MIA", 30.5),
    (198, "Chase DeLauter",          "OF",   "CLE", 24.4),
    (199, "Ryan Pepiot",             "SP",   "TBR", 28.6),
    (200, "Tatsuya Imai",            "SP",   "HOU", 27.8),
    (201, "Brandon Woodruff",        "SP",   "MIL", 33.1),
    (202, "Jasson Dominguez",        "OF",   "NYY", 23.1),
    (203, "Spencer Torkelson",       "1B",   "DET", 26.6),
    (204, "Liam Doyle",              "SP",   "STL", 21.8),
    (205, "Nico Hoerner",            "2B",   "CHC", 28.8),
    (206, "Jared Jones",             "SP",   "PIT", 22.6),
    (207, "Corbin Burnes",           "SP",   "ARI", 31.4),
    (208, "Cade Horton",             "SP",   "CHC", 24.6),
    (209, "Josh Hader",              "RP",   "HOU", 31.9),
    (210, "Justin Steele",           "SP",   "CHC", 30.7),
    (211, "Brody Hopkins",           "SP",   "TBR", 24.2),
    (212, "Kade Anderson",           "SP",   "SEA", 21.7),
    (213, "Kazuma Okamoto",          "3B",   "TOR", 29.7),
    (214, "Alejandro Kirk",          "C",    "TOR", 27.3),
    (215, "Brandon Lowe",            "2B",   "PIT", 31.7),
    (216, "Masyn Winn",              "SS",   "STL", 24.0),
    (217, "Adley Rutschman",         "C",    "BAL", 28.1),
    (218, "Gabriel Moreno",          "C",    "ARI", 26.1),
    (219, "Hunter Goodman",          "C",    "COL", 26.4),
    (220, "Kyle Teel",               "C",    "CWS", 24.1),
    (221, "Owen Caissie",            "OF",   "MIA", 23.7),
    (222, "Ceddanne Rafaela",        "OF",   "BOS", 25.5),
    (223, "Drew Rasmussen",          "SP",   "TBR", 30.6),
    (224, "Munetaka Murakami",       "3B",   "CWS", 26.1),
    (225, "Jeff Hoffman",            "RP",   "TOR", 33.2),
    (226, "Aaron Nola",              "SP",   "PHI", 32.8),
    (227, "Kris Bubic",              "SP",   "KCR", 28.6),
    (228, "Joe Musgrove",            "SP",   "SDP", 33.3),
    (229, "Zac Gallen",              "SP",   "ARI", 30.6),
    (230, "Alec Burleson",           "1B",   "STL", 27.3),
    (231, "Willson Contreras",       "1B",   "BOS", 33.8),
    (232, "Braden Montgomery",       "OF",   "CWS", 22.9),
    (233, "Xavier Edwards",          "2B",   "MIA", 26.6),
    (234, "Triston Casas",           "1B",   "BOS", 26.2),
    (235, "Kerry Carpenter",         "OF",   "DET", 28.5),
    (236, "Heliot Ramos",            "OF",   "SFG", 26.5),
    (237, "Colton Cowser",           "OF",   "BAL", 26.0),
    (238, "Robby Snelling",          "SP",   "MIA", 22.3),
    (239, "Brenton Doyle",           "OF",   "COL", 27.8),
    (240, "Daylen Lile",             "OF",   "WAS", 23.3),
    (241, "Otto Lopez",              "SS",   "MIA", 27.4),
    (242, "Bryson Stott",            "2B",   "PHI", 28.4),
    (243, "Trevor Story",            "SS",   "BOS", 33.3),
    (244, "Brendan Donovan",         "2B",   "SEA", 29.2),
    (245, "Austin Wells",            "C",    "NYY", 26.7),
    (246, "Yainer Diaz",             "C",    "HOU", 27.5),
    (247, "Dylan Beavers",           "OF",   "BAL", 24.6),
    (248, "Ezequiel Tovar",          "SS",   "COL", 24.6),
    (249, "Taj Bradley",             "SP",   "MIN", 25.0),
    (250, "Alec Bohm",               "3B",   "PHI", 29.6),
    (251, "Wilyer Abreu",            "OF",   "BOS", 26.8),
    (252, "Bryan Reynolds",          "OF",   "PIT", 31.1),
    (253, "Xander Bogaerts",         "2B",   "SDP", 33.4),
    (254, "Dansby Swanson",          "SS",   "CHC", 32.1),
    (255, "Marcelo Mayer",           "3B",   "BOS", 23.3),
    (256, "Jarlin Susana",           "SP",   "WAS", 22.0),
    (257, "Roki Sasaki",             "SP",   "LAD", 24.3),
    (258, "Trevor Rogers",           "SP",   "BAL", 28.3),
    (259, "Ryne Nelson",             "SP",   "ARI", 28.1),
    (260, "Andrew Abbott",           "SP",   "CIN", 26.8),
    (261, "Taylor Ward",             "OF",   "BAL", 32.3),
    (262, "Quinn Priester",          "SP",   "MIL", 25.5),
    (263, "Andrew Painter",          "SP",   "PHI", 22.9),
    (264, "Connelly Early",          "SP",   "BOS", 23.9),
    (265, "Casey Mize",              "SP",   "DET", 28.8),
    (266, "Carlos Correa",           "SS",   "HOU", 31.5),
    (267, "Sal Frelick",             "OF",   "MIL", 25.9),
    (268, "Caleb Durbin",            "2B",   "BOS", 26.1),
    (269, "Matt McLain",             "2B",   "CIN", 26.6),
    (270, "Jaxon Wiggins",           "SP",   "CHC", 24.4),
    (271, "Colt Keith",              "2B",   "DET", 24.6),
    (272, "Luis Garcia Jr.",         "2B",   "WAS", 25.8),
    (273, "Coby Mayo",               "3B",   "BAL", 24.3),
    (274, "Kaelen Culpepper",        "SS",   "MIN", 23.2),
    (275, "Chandler Simpson",        "OF",   "TBR", 25.3),
    (276, "Matt Wallner",            "OF",   "MIN", 28.3),
    (277, "Emmanuel Rodriguez",      "OF",   "MIN", 23.0),
    (278, "Dax Kilby",               "SS",   "NYY", 19.3),
    (279, "Daulton Varsho",          "OF",   "TOR", 29.7),
    (280, "Lazaro Montes",           "OF",   "SEA", 21.4),
    (281, "JoJo Parker",             "SS",   "TOR", 19.6),
    (282, "Carlos Lagrange",         "SP",   "NYY", 22.8),
    (283, "Grant Taylor",            "RP",   "CWS", 23.8),
    (284, "Kodai Senga",             "SP",   "NYM", 33.1),
    (285, "Gage Jump",               "SP",   "ATH", 22.9),
    (286, "Eli Willits",             "SS",   "WAS", 18.3),
    (287, "Dalton Rushing",          "C",    "LAD", 25.1),
    (288, "Seth Hernandez",          "SP",   "PIT", 19.7),
    (289, "AJ Smith-Shawver",        "SP",   "ATL", 23.3),
    (290, "David Bednar",            "RP",   "NYY", 31.4),
    (291, "Merrill Kelly",           "SP",   "ARI", 37.4),
    (292, "Will Warren",             "SP",   "NYY", 26.8),
    (293, "Brayan Bello",            "SP",   "BOS", 26.8),
    (294, "Jack Leiter",             "SP",   "TEX", 25.9),
    (295, "Josue Briceño",           "C",    "DET", 21.5),
    (296, "Troy Melton",             "SP",   "DET", 25.3),
    (297, "Ryan Helsley",            "SP",   "BAL", 31.7),
    (298, "Ryan Clifford",           "1B",   "NYM", 22.7),
    (299, "Pete Fairbanks",          "RP",   "MIA", 32.3),
    (300, "Jacob Reimer",            "3B",   "NYM", 22.1),
    (301, "Trevor Megill",           "RP",   "MIL", 32.3),
    (302, "Ralphy Velazquez",        "1B",   "CLE", 20.8),
    (303, "Daniel Palencia",         "RP",   "CHC", 26.1),
    (304, "Devin Williams",          "RP",   "NYM", 31.5),
    (305, "A.J. Ewing",              "OF",   "NYM", 21.6),
    (306, "Colson Montgomery",       "SS",   "CWS", 24.0),
    (307, "Jett Williams",           "SS",   "MIL", 22.3),
    (308, "Ryan Sloan",              "SP",   "SEA", 20.1),
    (309, "Josh Lowe",               "OF",   "TBR", 28.1),
    (310, "Logan O'Hoppe",           "C",    "LAA", 26.1),
    (311, "Trent Grisham",           "OF",   "NYY", 29.3),
    (312, "Moises Ballesteros",      "C",    "CHC", 22.3),
    (313, "Jackson Jobe",            "SP",   "DET", 23.6),
    (314, "Mike Burrows",            "SP",   "HOU", 26.3),
    (315, "Emil Morales",            "SS",   "LAD", 19.5),
    (316, "TJ Friedl",               "OF",   "CIN", 30.6),
    (317, "Salvador Perez",          "C",    "KCR", 35.8),
    (318, "Theo Gillen",             "OF",   "TBR", 20.5),
    (319, "Jorge Polanco",           "2B",   "NYM", 32.7),
    (320, "Arjun Nimmala",           "SS",   "TOR", 20.4),
    (321, "Max Muncy",               "3B",   "LAD", 23.6),
    (322, "Charlie Condon",          "OF",   "COL", 22.9),
    (323, "Nolan Schanuel",          "1B",   "LAA", 24.1),
    (324, "Andrew Vaughn",           "1B",   "MIL", 27.9),
    (325, "Alfredo Duno",            "C",    "CIN", 20.2),
    (326, "Kumar Rocker",            "SP",   "TEX", 26.3),
    (327, "Lars Nootbaar",           "OF",   "STL", 28.5),
    (328, "Trey Gibson",             "SP",   "BAL", 23.8),
    (329, "Kristian Campbell",       "OF",   "BOS", 23.7),
    (330, "Jacob Melton",            "OF",   "TBR", 25.5),
    (331, "Jurickson Profar",        "OF",   "ATL", 33.1),
    (332, "Josh Jung",               "3B",   "TEX", 28.1),
    (333, "Christian Walker",        "1B",   "HOU", 34.9),
    (334, "Justin Gonzales",         "OF",   "BOS", 19.2),
    (335, "Pablo Lopez",             "SP",   "MIN", 30.0),
    (336, "Luis Arraez",             "1B",   "SFG", 28.9),
    (337, "Jakob Marsee",            "OF",   "MIA", 24.7),
    (338, "Michael Arroyo",          "OF",   "SEA", 21.3),
    (339, "Dillon Dingler",          "C",    "DET", 27.5),
    (340, "Jung Hoo Lee",            "OF",   "SFG", 27.6),
    (341, "Justin Crawford",         "OF",   "PHI", 22.2),
    (342, "Brandon Sproat",          "SP",   "MIL", 25.5),
    (343, "Edgar Quero",             "C",    "CWS", 22.9),
    (344, "George Lombard Jr.",      "SS",   "NYY", 20.8),
    (345, "Cooper Pratt",            "SS",   "MIL", 21.6),
    (346, "Evan Carter",             "OF",   "TEX", 23.5),
    (347, "Adolis Garcia",           "OF",   "PHI", 33.0),
    (348, "Luis Perales",            "SP",   "WAS", 22.9),
    (349, "Jesus Sanchez",           "OF",   "TOR", 28.4),
    (350, "Tanner McDougal",         "SP",   "CWS", 22.9),
    (351, "Giancarlo Stanton",       "OF",   "NYY", 36.3),
    (352, "Steele Hall",             "SS",   "CIN", 18.7),
    (353, "Marcell Ozuna",           "UT",   "PIT", 35.3),
    (354, "Franklin Arias",          "SS",   "BOS", 20.3),
    (355, "Tyler O'Neill",           "OF",   "BAL", 30.8),
    (356, "Ha-Seong Kim",            "SS",   "ATL", 30.4),
    (357, "Carson Williams",         "SS",   "TBR", 22.8),
    (358, "Jordan Beck",             "OF",   "COL", 24.9),
    (359, "Caden Scarborough",       "SP",   "TEX", 20.9),
    (360, "Marcus Semien",           "2B",   "NYM", 35.5),
    (361, "Brock Wilken",            "3B",   "MIL", 23.8),
    (362, "Brandon Pfaadt",          "SP",   "ARI", 27.4),
    (363, "Jose Soriano",            "SP",   "LAA", 27.4),
    (364, "Robert Suarez",           "RP",   "ATL", 35.0),
    (365, "Cam Caminiti",            "SP",   "ATL", 19.6),
    (366, "Aroldis Chapman",         "RP",   "BOS", 38.0),
    (367, "Tanner Scott",            "RP",   "LAD", 31.7),
    (368, "Jhonny Level",            "SS",   "",    18.9),
    (369, "Devin Fitz-Gerald",       "2B",   "WAS", 20.6),
    (370, "Lenyn Sosa",              "2B",   "CWS", 26.2),
    (371, "Ramon Laureano",          "OF",   "SDP", 31.7),
    (372, "Luis Hernandez",          "SS",   "SFG", None),
    (373, "Raisel Iglesias",         "RP",   "ATL", 36.2),
    (374, "Shane Smith",             "SP",   "CWS", 25.9),
    (375, "Miguel Vargas",           "3B",   "CWS", 26.3),
    (376, "Spencer Steer",           "1B",   "CIN", 28.3),
    (377, "Max Meyer",               "SP",   "MIA", 27.0),
    (378, "Johenssy Colome",         "SS",   "ATH", None),
    (379, "Mickey Moniak",           "OF",   "COL", 27.8),
    (380, "Cade Cavalli",            "SP",   "WAS", 27.6),
    (381, "Bailey Ober",             "SP",   "MIN", 30.7),
    (382, "Demetrio Crisantes",      "2B",   "ARI", 21.5),
    (383, "Noah Cameron",            "SP",   "KCR", 26.7),
    (384, "Ryan Weathers",           "SP",   "NYY", 26.3),
    (385, "Joe Boyle",               "SP",   "TBR", 26.6),
    (386, "Luis Gil",                "SP",   "NYY", 27.8),
    (387, "Matthew Boyd",            "SP",   "CHC", 35.1),
    (388, "Tyson Lewis",             "SS",   "CIN", 20.2),
    (389, "Mitch Keller",            "SP",   "PIT", 29.9),
    (390, "Clay Holmes",             "SP",   "NYM", 32.9),
    (391, "Trevor Larnach",          "OF",   "MIN", 29.1),
    (392, "Spencer Horwitz",         "1B",   "PIT", 28.3),
    (393, "Joey Ortiz",              "SS",   "MIL", 27.7),
    (394, "Rhett Lowder",            "SP",   "CIN", None),
    (395, "Brady House",             "3B",   "WAS", 22.8),
    (396, "Brady Singer",            "SP",   "CIN", 29.6),
    (397, "Brandon Marsh",           "OF",   "PHI", 28.3),
    (398, "Jonny Farmelo",           "OF",   "SEA", 21.5),
    (399, "Tommy Edman",             "2B",   "LAD", 30.8),
    (400, "Chase Meidroth",          "SS",   "CWS", 24.7),
    (401, "Khal Stephen",            "SP",   "CLE", 23.3),
    (402, "Brooks Lee",              "SS",   "MIN", 25.1),
    (403, "Luis Morales",            "SP",   "ATH", 23.5),
    (404, "Gavin Fien",              "SS",   "WAS", 19.0),
    (405, "Parker Meadows",          "OF",   "DET", 26.3),
    (406, "Ryan O'Hearn",            "1B",   "PIT", 32.7),
    (407, "Anthony Santander",       "OF",   "TOR", 31.4),
    (408, "Jose Caballero",          "2B",   "NYY", 29.5),
    (409, "Bo Naylor",               "C",    "CLE", 26.1),
    (410, "Noah Schultz",            "SP",   "CWS", 22.6),
    (411, "Andres Gimenez",          "2B",   "TOR", 27.5),
    (412, "Ronny Mauricio",          "2B",   "NYM", 24.9),
    (413, "Braxton Garrett",         "SP",   "MIA", 28.6),
    (414, "Chad Patrick",            "SP",   "MIL", 27.6),
    (415, "Angel Genoa",             "SS",   "CLE", None),
    (416, "J.T. Realmuto",           "C",    "PHI", 35.0),
    (417, "Justin Wrobleski",        "SP",   "LAD", 25.7),
    (418, "Cole Young",              "2B",   "SEA", 22.6),
    (419, "Aiva Arquette",           "SS",   "MIA", 22.4),
    (420, "Alejandro Osuna",         "OF",   "TEX", 23.4),
    (421, "Bo Davidson",             "OF",   "SFG", 23.7),
    (422, "Ethan Conrad",            "OF",   "CHC", 21.7),
    (423, "David Hagaman",           "SP",   "ARI", 22.9),
    (424, "Reynaldo Lopez",          "SP",   "ATL", 32.2),
    (425, "Travis Sykora",           "SP",   "WAS", 21.8),
    (426, "Josh Smith",              "3B",   "TEX", 28.6),
    (427, "Juneiker Caceres",        "OF",   "CLE", 18.6),
    (428, "Hurston Waldrep",         "SP",   "ATL", 24.0),
    (429, "Ben Brown",               "SP",   "CHC", 26.5),
    (430, "Jake Burger",             "1B",   "TEX", 29.9),
    (431, "Ethan Holliday",          "SS",   "COL", 19.1),
    (432, "JR Ritchie",              "SP",   "ATL", 22.8),
    (433, "Jamie Arnold",            "SP",   "ATH", 22.0),
    (434, "Braylon Doughty",         "SP",   "CLE", 20.3),
    (435, "Cedric Mullins",          "OF",   "TBR", 31.4),
    (436, "Josh Hammond",            "SS",   "KCR", 19.5),
    (437, "Jhostynxon Garcia",       "OF",   "PIT", 23.3),
    (438, "Zach McKinstry",          "OF",   "DET", 30.8),
    (439, "Victor Robles",           "OF",   "SEA", 28.8),
    (440, "Dominic Canzone",         "OF",   "SEA", 28.6),
    (441, "Kevin Alcantara",         "OF",   "CHC", None),
    (442, "Hagen Smith",             "SP",   "CWS", 22.6),
    (443, "Harrison Bader",          "OF",   "SFG", 31.8),
    (444, "Austin Hays",             "OF",   "CWS", 30.7),
    (445, "Xavier Neyens",           "SS",   "HOU", None),
    (446, "Aroon Escobar",           "2B",   "PHI", 21.2),
    (447, "Tyler Freeman",           "OF",   "COL", 26.8),
    (448, "Bryan Abreu",             "RP",   "HOU", 28.9),
    (449, "Ryan Jeffers",            "C",    "MIN", 28.8),
    (450, "Angeibel Gomez",          "SS",   "KCR", None),
    (451, "Christian Oppor",         "SP",   "CWS", 21.7),
    (452, "Nate George",             "OF",   "BAL", 19.8),
    (453, "Carlos Narvaez",          "C",    "BOS", 27.3),
    (454, "Seth Lugo",               "SP",   "KCR", 36.3),
    (455, "Sean Manaea",             "SP",   "NYM", 34.1),
    (456, "Ethan Frey",              "OF",   "HOU", None),
    (457, "Kyson Witherspoon",       "SP",   "BOS", 21.6),
    (458, "Quinn Mathews",           "SP",   "STL", None),
    (459, "Braxton Ashcraft",        "SP",   "PIT", 26.4),
    (460, "Slade Cecconi",           "SP",   "CLE", 26.8),
    (461, "Lucas Giolito",           "SP",   "FA",  31.7),
    (462, "Braylon Payne",           "OF",   "MIL", None),
    (463, "Carlos Estevez",          "RP",   "KCR", 33.2),
    (464, "Ian Seymour",             "SP",   "TBR", 27.3),
    (465, "Paul Goldschmidt",        "1B",   "NYY", 38.5),
    (466, "Kendry Chourio",          "SP",   "KCR", 18.4),
    (467, "J.P. Crawford",           "SS",   "SEA", 31.2),
    (468, "Curtis Mead",             "1B",   "CWS", 25.4),
    (469, "Brayan Rocchio",          "SS",   "CLE", 25.2),
    (470, "Sean Murphy",             "C",    "ATL", 31.4),
    (471, "Juan Sanchez",            "SS",   "TOR", 23.0),
    (472, "Heston Kjerstad",         "OF",   "BAL", 27.1),
    (473, "Gavin Stone",             "SP",   "LAD", 27.4),
    (474, "Nolan Gorman",            "2B",   "STL", 25.8),
    (475, "Felix Bautista",          "RP",   "BAL", 30.8),
    (476, "Rhys Hoskins",            "1B",   "FA",  33.0),
    (477, "Jace LaViolette",         "OF",   "CLE", None),
    (478, "Tyler Bremner",           "SP",   "LAA", None),
    (479, "Gage Wood",               "SP",   "PHI", 22.3),
    (480, "Slade Caldwell",          "OF",   "ARI", 19.8),
    (481, "Joey Cantillo",           "SP",   "CLE", 26.3),
    (482, "Drew Gilbert",            "OF",   "SFG", 25.4),
    (483, "Enrique Bradfield Jr.",   "OF",   "BAL", None),
    (484, "Jake Cronenworth",        "2B",   "SDP", 32.2),
    (485, "Johnny King",             "SP",   "TOR", 19.7),
    (486, "Jeff McNeil",             "2B",   "ATH", 33.9),
    (487, "Esteban Mejia",           "SP",   "BAL", 21.3),
    (488, "Jorge Soler",             "OF",   "LAA", 34.1),
    (489, "Tyler Stephenson",        "C",    "CIN", 29.6),
    (490, "Hayden Birdsong",         "SP",   "SFG", 24.5),
    (491, "Isaac Collins",           "OF",   "KCR", 28.7),
    (492, "Ryan Mountcastle",        "1B",   "BAL", 29.1),
    (493, "C.J. Kayfus",             "1B",   "CLE", 24.3),
    (494, "Owen Murphy",             "SP",   "ATL", 22.4),
    (495, "Jack Perkins",            "SP",   "ATH", 26.3),
    (496, "Jurrangelo Cijntje",      "SP",   "STL", 22.8),
    (497, "Spencer Jones",           "OF",   "NYY", 24.8),
    (498, "Jake Bennett",            "SP",   "BOS", None),
    (499, "Parker Messick",          "SP",   "CLE", 25.4),
    (500, "Cristian Javier",         "SP",   "HOU", 29.0),
]


def normalize(name):
    """Normalize name to ASCII lowercase, stripping suffixes and punctuation."""
    name = unicodedata.normalize("NFKD", name)
    name = name.encode("ascii", "ignore").decode("ascii")
    name = name.lower()
    name = re.sub(r"\b(jr|sr|ii|iii|iv|v)\b\.?", "", name)
    name = re.sub(r"[^a-z\s]", "", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name


def main():
    # Build BA lookup: normalized_name -> (rank, name, pos, team, age)
    ba_lookup = {}
    for rank, name, pos, team, age in BA_RANKINGS:
        key = normalize(name)
        ba_lookup[key] = (rank, name, pos, team, age)

    # Read master
    with open(MASTER_PATH, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = list(reader.fieldnames)
        rows = list(reader)

    # Check if column already exists
    if NEW_COL in fieldnames:
        print(f"Column '{NEW_COL}' already exists — updating values in place.")
        new_fieldnames = fieldnames
    else:
        # Insert new column before "Average Rank"
        avg_rank_idx = fieldnames.index("Average Rank")
        new_fieldnames = fieldnames[:avg_rank_idx] + [NEW_COL] + fieldnames[avg_rank_idx:]

    # Track matched keys
    matched_keys = set()

    # Update existing rows
    for row in rows:
        key = normalize(row["Player"])
        if key in ba_lookup:
            rank, _, _, _, _ = ba_lookup[key]
            row[NEW_COL] = rank
            matched_keys.add(key)
        else:
            if NEW_COL not in row:
                row[NEW_COL] = ""

    # Find unmatched BA players
    unmatched = []
    for rank, name, pos, team, age in BA_RANKINGS:
        key = normalize(name)
        if key not in matched_keys:
            unmatched.append((rank, name, pos, team, age))

    print(f"Matched: {len(matched_keys)} players")
    print(f"New players to add: {len(unmatched)}")
    for rank, name, pos, team, age in unmatched:
        print(f"  [{rank}] {name} ({pos}, {team})")

    # Add new rows for unmatched players
    for rank, name, pos, team, age in unmatched:
        new_row = {fn: "" for fn in new_fieldnames}
        new_row["Player"] = name
        new_row["Position"] = pos
        new_row["Team"] = team if team else ""
        new_row["Age"] = str(age) if age else ""
        new_row[NEW_COL] = rank
        rows.append(new_row)

    # Write back
    with open(MASTER_PATH, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=new_fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"\nWrote {len(rows)} rows to {MASTER_PATH}")

    # Recalculate
    print("\nRunning recalculate.py...")
    result = subprocess.run(
        ["python3", "scripts/recalculate.py", MASTER_PATH],
        capture_output=True, text=True
    )
    print(result.stdout)
    if result.stderr:
        print("STDERR:", result.stderr)


if __name__ == "__main__":
    main()
