#!/usr/bin/env python3
"""
Merge Lineup Experts (Oct 2025) skater rankings into hockey_skaters_master.csv.
Draft picks and goalies are excluded. Overall ranks (including goalies) are preserved as-is.
Run recalculate.py afterward.
"""

import csv
import os
import re
import subprocess
import unicodedata

MASTER_PATH = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "hockey", "hockey_skaters_master.csv"))
SOURCE_COL = "Lineup Experts (Oct 2025)"

# (overall_rank, canonical_name, position)
# Names normalized to match existing master entries where needed.
# Draft picks and goalies already excluded.
SKATER_DATA = [
    (1, "Macklin Celebrini", "F"),
    (2, "Jack Hughes", "F"),
    (3, "Connor McDavid", "F"),
    (4, "Cale Makar", "D"),
    (5, "Quinn Hughes", "D"),
    (6, "Connor Bedard", "F"),
    (7, "Nathan MacKinnon", "F"),
    (8, "Matt Boldy", "F"),
    (9, "Tim Stutzle", "F"),
    (10, "Evan Bouchard", "D"),
    (11, "Matvei Michkov", "F"),
    (12, "Leon Draisaitl", "F"),
    (13, "Wyatt Johnston", "F"),
    (14, "Auston Matthews", "F"),
    (16, "Rasmus Dahlin", "D"),
    (17, "Seth Jarvis", "F"),
    (19, "Brady Tkachuk", "F"),
    (20, "Kirill Kaprizov", "F"),
    (21, "David Pastrnak", "F"),
    (22, "Jake Sanderson", "D"),
    (23, "Dylan Guenther", "F"),
    (24, "Nikita Kucherov", "F"),
    (25, "Lane Hutson", "D"),
    (26, "Cole Caufield", "F"),
    (27, "Jason Robertson", "F"),
    (28, "Lucas Raymond", "F"),
    (29, "Moritz Seider", "D"),
    (30, "Adam Fantilli", "F"),
    (31, "Matthew Knies", "F"),
    (32, "Jack Eichel", "F"),
    (33, "Logan Cooley", "F"),
    (34, "Mikko Rantanen", "F"),
    (37, "Thomas Harley", "D"),
    (38, "Kyle Connor", "F"),
    (39, "Tage Thompson", "F"),
    (40, "Juraj Slafkovsky", "F"),
    (41, "Martin Necas", "F"),
    (42, "Brandon Hagel", "F"),
    (43, "Jesper Bratt", "F"),
    (44, "JJ Peterka", "F"),
    (45, "Cutter Gauthier", "F"),
    (46, "William Nylander", "F"),
    (47, "Dylan Holloway", "F"),
    (48, "Elias Pettersson", "F"),
    (49, "Quinton Byfield", "F"),
    (50, "Clayton Keller", "F"),
    (51, "Nick Suzuki", "F"),
    (52, "Adam Fox", "D"),
    (53, "Kirill Marchenko", "F"),
    (55, "Zach Werenski", "D"),
    (56, "Mitch Marner", "F"),
    (57, "Mason McTavish", "F"),
    (58, "Matthew Tkachuk", "F"),
    (60, "Pavel Dorofeyev", "F"),
    (61, "Sam Reinhart", "F"),
    (63, "Ivan Demidov", "F"),
    (64, "Sam Rinzel", "D"),
    (65, "Brayden Point", "F"),
    (66, "Nico Hischier", "F"),
    (67, "Logan Stankoven", "F"),
    (68, "Robert Thomas", "F"),
    (69, "Noah Dobson", "D"),
    (70, "Matt Coronato", "F"),
    (71, "Jackson Lacombe", "D"),
    (72, "Jake Guentzel", "F"),
    (73, "Alex DeBrincat", "F"),
    (74, "Brock Faber", "D"),
    (75, "Brandt Clarke", "D"),
    (77, "Kent Johnson", "F"),
    (78, "Filip Forsberg", "F"),
    (79, "Jordan Kyrou", "F"),
    (80, "Cole Perfetti", "F"),
    (81, "Artemi Panarin", "F"),
    (84, "Jiri Kulich", "F"),
    (85, "Andrei Svechnikov", "F"),
    (86, "Trevor Zegras", "F"),
    (87, "Will Smith", "F"),
    (88, "Simon Edvinsson", "D"),
    (89, "Dylan Cozens", "F"),
    (90, "Miro Heiskanen", "D"),
    (91, "Sebastian Aho", "F"),
    (92, "Matty Beniers", "F"),
    (93, "Drake Batherson", "F"),
    (94, "Zack Bolduc", "F"),
    (96, "Adrian Kempe", "F"),
    (97, "Shane Wright", "F"),
    (98, "Marco Rossi", "F"),
    (99, "Mikhail Sergachev", "D"),
    (100, "Alexander Nikishin", "D"),
    (101, "William Eklund", "F"),
    (102, "Josh Morrissey", "D"),
    (103, "Owen Power", "D"),
    (104, "Zayne Parekh", "D"),
    (105, "Will Cuylle", "F"),
    (106, "Charlie McAvoy", "D"),
    (108, "Jakob Chychrun", "D"),
    (109, "Marco Kasper", "F"),
    (111, "Leo Carlsson", "F"),
    (112, "MacKenzie Weegar", "D"),
    (116, "Connor McMichael", "F"),
    (117, "Anton Lundell", "F"),
    (119, "J.T. Miller", "F"),
    (120, "Aleksander Barkov", "F"),
    (122, "Gabriel Vilardi", "F"),
    (123, "Frank Nazar", "F"),
    (124, "Victor Hedman", "D"),
    (125, "Mark Scheifele", "F"),
    (127, "Alexis Lafreniere", "F"),
    (128, "Dylan Larkin", "F"),
    (130, "Luke Hughes", "D"),
    (131, "Nikolaj Ehlers", "F"),
    (132, "Bowen Byram", "D"),
    (133, "Tyson Foerster", "F"),
    (134, "Jimmy Snuggerud", "F"),
    (135, "Aliaksei Protas", "F"),
    (136, "Travis Konecny", "F"),
    (137, "Alex Tuch", "F"),
    (139, "Owen Tippett", "F"),
    (140, "Roope Hintz", "F"),
    (141, "Jackson Blake", "F"),
    (143, "Alex Laferriere", "F"),
    (144, "Matthew Schaefer", "D"),
    (145, "Morgan Geekie", "F"),
    (146, "Roman Josi", "D"),
    (147, "Pierre-Luc Dubois", "F"),
    (148, "Alexander Romanov", "D"),
    (150, "Philip Broberg", "D"),
    (151, "Shane Pinto", "F"),
    (152, "Joel Eriksson Ek", "F"),
    (156, "Kevin Fiala", "F"),
    (157, "Carter Verhaeghe", "F"),
    (158, "Dylan Strome", "F"),
    (159, "Olen Zellweger", "D"),
    (160, "Connor Zary", "F"),
    (161, "Sidney Crosby", "F"),
    (162, "Mathew Barzal", "F"),
    (163, "Dmitri Voronkov", "F"),
    (164, "Shea Theodore", "D"),
    (165, "Timo Meier", "F"),
    (166, "Kaiden Guhle", "D"),
    (167, "Dougie Hamilton", "D"),
    (168, "Bo Horvat", "F"),
    (169, "Vincent Trocheck", "F"),
    (171, "Zach Hyman", "F"),
    (173, "John Tavares", "F"),
    (174, "Filip Hronek", "D"),
    (176, "Alex Vlasic", "D"),
    (177, "Thomas Chabot", "D"),
    (178, "Logan Mailloux", "D"),
    (180, "Vince Dunn", "D"),
    (182, "Dawson Mercer", "F"),
    (183, "Sam Bennett", "F"),
    (185, "Devon Toews", "D"),
    (186, "K'Andre Miller", "D"),
    (187, "Nazem Kadri", "F"),
    (188, "Brandon Montour", "D"),
    (189, "Mika Zibanejad", "F"),
    (190, "Tom Wilson", "F"),
    (191, "Rickard Rakell", "F"),
    (192, "Kaapo Kakko", "F"),
    (193, "Maxim Shabanov", "F"),
    (195, "Jake Walman", "D"),
    (196, "Michael Kesselring", "D"),
    (197, "Brock Boeser", "F"),
    (198, "Noah Hanifin", "D"),
    (199, "John Carlson", "D"),
    (200, "Aaron Ekblad", "D"),
    (201, "Morgan Rielly", "D"),
    (202, "Cole Sillinger", "F"),
    (203, "Tomas Hertl", "F"),
    (204, "Anthony Cirelli", "F"),
    (205, "Ridly Greig", "F"),
    (207, "Rasmus Andersson", "D"),
    (208, "Valeri Nichushkin", "F"),
    (209, "Darnell Nurse", "D"),
    (210, "Artturi Lehkonen", "F"),
    (211, "Barrett Hayton", "F"),
    (212, "Jake Neighbours", "F"),
    (213, "Gustav Forsling", "D"),
    (214, "Conor Garland", "F"),
    (215, "Neal Pionk", "D"),
    (216, "Sean Durzi", "D"),
    (217, "Jared McCann", "F"),
    (218, "Erik Karlsson", "D"),
    (219, "Pavel Buchnevich", "F"),
    (220, "Sean Monahan", "F"),
    (221, "Braden Schneider", "D"),
    (223, "Colton Parayko", "D"),
    (224, "Bryan Rust", "F"),
    (225, "Ryan Nugent-Hopkins", "F"),
    (226, "Zeev Buium", "D"),
    (227, "Gabriel Landeskog", "F"),
    (228, "Frank Vatrano", "F"),
    (229, "Troy Terry", "F"),
    (230, "Seth Jones", "D"),
    (231, "Nick Schmaltz", "F"),
    (232, "Alex Ovechkin", "F"),
    (233, "Simon Holmstrom", "F"),
    (234, "Elias Lindholm", "F"),
    (235, "Josh Norris", "F"),
    (236, "Mark Stone", "F"),
    (237, "Shayne Gostisbehere", "D"),
    (238, "Ryan Leonard", "F"),
    (239, "Zach Benson", "F"),
    (240, "Brock Nelson", "F"),
    (241, "Dylan Samberg", "D"),
    (242, "Dante Fabbro", "D"),
    (243, "Steven Stamkos", "F"),
    (244, "Cameron York", "D"),
    (245, "Filip Chytil", "F"),
    (246, "Tyler Toffoli", "F"),
    (247, "Mason Lohrei", "D"),
    (248, "Travis Sanheim", "D"),
    (249, "Arseniy Gritsyuk", "F"),
    (250, "Matt Duchene", "F"),
    (251, "Drew Doughty", "D"),
    (253, "Jake DeBrusk", "F"),
    (254, "Jack Quinn", "F"),
    (255, "Mason Marchment", "F"),
    (256, "Morgan Frost", "F"),
    (257, "Anthony DeAngelo", "D"),
    (258, "Jaccob Slavin", "D"),
    (260, "Jonathan Marchessault", "F"),
    (261, "Ryan Donato", "F"),
    (262, "Ryan O'Reilly", "F"),
    (264, "Jordan Spence", "D"),
    (265, "Pavel Zacha", "F"),
    (266, "Boone Jenner", "F"),
    (267, "Chris Kreider", "F"),
    (268, "Mattias Ekholm", "D"),
    (270, "Josh Doan", "F"),
    (271, "Rasmus Sandin", "D"),
    (272, "Warren Foegele", "F"),
    (273, "Luke Evangelista", "F"),
    (274, "Blake Coleman", "F"),
    (275, "William Karlsson", "F"),
    (276, "Eeli Tolvanen", "F"),
    (277, "Mikey Anderson", "D"),
    (278, "Patrik Laine", "F"),
    (279, "Tyler Seguin", "F"),
    (280, "Brady Skjei", "D"),
    (281, "Anders Lee", "F"),
    (282, "Esa Lindell", "D"),
    (283, "Jonathan Huberdeau", "F"),
    (284, "Mike Matheson", "D"),
    (285, "Phillip Danault", "F"),
    (286, "Jacob Middleton", "D"),
    (287, "Jamie Drysdale", "D"),
    (288, "Trevor Moore", "F"),
    (289, "Bobby McMann", "F"),
    (290, "Jake McCabe", "D"),
    (291, "Ryan Pulock", "D"),
    (292, "Fabian Zetterlund", "F"),
    (293, "Brad Marchand", "F"),
    (294, "Jesperi Kotkaniemi", "F"),
    (295, "Hampus Lindholm", "D"),
    (296, "Justin Faulk", "D"),
    (297, "Jared Spurgeon", "D"),
    (298, "Cam Fowler", "D"),
    (299, "Vladislav Gavrikov", "D"),
    (300, "Patrick Kane", "F"),
    (301, "Denton Mateychuk", "D"),
    (302, "Anze Kopitar", "F"),
    (303, "Ivan Provorov", "D"),
    (304, "Darren Raddysh", "D"),
    (305, "Adam Larsson", "D"),
    (306, "Jacob Trouba", "D"),
    (307, "Ivan Barbashev", "F"),
    (308, "Brayden McNabb", "D"),
    (309, "Samuel Girard", "D"),
    (310, "Matt Roy", "D"),
    (311, "Mats Zuccarello", "F"),
    (312, "Kris Letang", "D"),
    (313, "Ryan McLeod", "F"),
    (314, "Jonas Brodin", "D"),
    (315, "Mikael Granlund", "F"),
    (316, "Marcus Pettersson", "D"),
    (317, "Scott Morrow", "D"),
    (318, "Yegor Sharangovich", "F"),
    (319, "Ross Colton", "F"),
    (320, "Casey Mittelstadt", "F"),
    (321, "J.J. Moser", "D"),
    (322, "Sean Couturier", "F"),
    (323, "Mackie Samoskevich", "F"),
    (324, "Mikael Backlund", "F"),
    (325, "Sam Malinski", "D"),
    (326, "Brayden Schenn", "F"),
    (327, "Viktor Arvidsson", "F"),
    (328, "Jamie Benn", "F"),
    (329, "Oliver Bjorkstrand", "F"),
    (330, "Evgeni Malkin", "F"),
    (331, "Yegor Chinakhov", "F"),
    (332, "Nick Seeler", "D"),
    (333, "Stefan Noesen", "F"),
    (334, "Martin Fehervary", "D"),
    (335, "Oliver Ekman-Larsson", "D"),
    (336, "Ryan McDonagh", "D"),
    (337, "Matias Maccelli", "F"),
    (338, "Brent Burns", "D"),
    (340, "Jason Zucker", "F"),
    (341, "Dylan DeMelo", "D"),
    (342, "Jaden Schwartz", "F"),
    (343, "Radko Gudas", "D"),
    (344, "Kyle Palmieri", "F"),
    (345, "Timothy Liljegren", "D"),
    (346, "Evan Rodrigues", "F"),
    (347, "Chris Tanev", "D"),
    (348, "Pius Suter", "F"),
    (349, "Evander Kane", "F"),
    (350, "Brett Pesce", "D"),
]


def normalize(name):
    name = unicodedata.normalize("NFKD", name)
    name = name.encode("ascii", "ignore").decode("ascii")
    name = name.lower()
    name = re.sub(r"\b(jr|sr|ii|iii|iv|v)\b\.?", "", name)
    name = re.sub(r"[^a-z\s]", "", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name


with open(MASTER_PATH, newline="") as f:
    reader = csv.DictReader(f)
    fieldnames = list(reader.fieldnames)
    rows = list(reader)

if SOURCE_COL not in fieldnames:
    fieldnames.insert(fieldnames.index("Average Rank"), SOURCE_COL)
    for row in rows:
        row[SOURCE_COL] = ""

lookup = {normalize(row["Player"]): row for row in rows}

new_players = []
for rank, name, pos in SKATER_DATA:
    key = normalize(name)
    if key in lookup:
        lookup[key][SOURCE_COL] = rank
    else:
        new_row = {fn: "" for fn in fieldnames}
        new_row["Player"] = name
        new_row["Position"] = pos
        new_row["Age"] = ""
        new_row[SOURCE_COL] = rank
        new_row["Average Rank"] = ""
        new_row["Rank Variance"] = ""
        new_players.append(new_row)
        rows.append(new_row)
        lookup[key] = new_row

with open(MASTER_PATH, "w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f"Merged {len(SKATER_DATA)} Lineup Experts skaters.")
print(f"  Matched: {len(SKATER_DATA) - len(new_players)}")
print(f"  New players added: {len(new_players)}")
if new_players:
    for p in new_players:
        print(f"    + {p['Player']}")

subprocess.run(["python3", os.path.join(os.path.dirname(__file__), "recalculate.py"), MASTER_PATH])
