#!/usr/bin/env python3
"""
Merge Lineup Experts (Aug 2026) skater rankings into hockey_skaters_master.csv.
Draft picks and goalies are excluded. Overall ranks (including goalies) are
re-ranked sequentially 1-N among skaters only, by order of appearance.
Run recalculate.py afterward.
"""

import csv
import os
import re
import subprocess
import unicodedata

MASTER_PATH = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "hockey", "hockey_skaters_master.csv"))
OLD_SOURCE_COL = "Lineup Experts (Oct 2025)"
SOURCE_COL = "Lineup Experts (Aug 2026)"

# (sequential_rank, canonical_name, position)
# Names normalized to match existing master entries where needed.
SKATER_DATA = [
    (1, "Macklin Celebrini", "F"),
    (2, "Matthew Schaefer", "D"),
    (3, "Cutter Gauthier", "F"),
    (4, "Connor McDavid", "F"),
    (5, "Wyatt Johnston", "F"),
    (6, "Matt Boldy", "F"),
    (7, "Jack Hughes", "F"),
    (8, "Leo Carlsson", "F"),
    (9, "Lane Hutson", "D"),
    (10, "Porter Martone", "F"),
    (11, "Cale Makar", "D"),
    (12, "Connor Bedard", "F"),
    (13, "Dylan Guenther", "F"),
    (14, "Cole Caufield", "F"),
    (15, "Nathan MacKinnon", "F"),
    (16, "Jason Robertson", "F"),
    (17, "Adam Fantilli", "F"),
    (18, "Juraj Slafkovsky", "F"),
    (19, "Martin Necas", "F"),
    (20, "Tim Stutzle", "F"),
    (21, "Quinn Hughes", "D"),
    (22, "Nick Suzuki", "F"),
    (23, "Anton Frondell", "F"),
    (24, "Evan Bouchard", "D"),
    (25, "Will Smith", "F"),
    (26, "Brandon Hagel", "F"),
    (27, "Leon Draisaitl", "F"),
    (28, "Jake Sanderson", "D"),
    (29, "Nikita Kucherov", "F"),
    (30, "Brandt Clarke", "D"),
    (31, "Auston Matthews", "F"),
    (32, "Kirill Kaprizov", "F"),
    (33, "Dylan Holloway", "F"),
    (34, "Gavin McKenna", "F"),
    (35, "Brady Tkachuk", "F"),
    (36, "David Pastrnak", "F"),
    (37, "Rasmus Dahlin", "D"),
    (38, "Moritz Seider", "D"),
    (39, "Seth Jarvis", "F"),
    (40, "Logan Cooley", "F"),
    (41, "Lucas Raymond", "F"),
    (42, "Zach Werenski", "D"),
    (43, "Ivan Demidov", "F"),
    (44, "Pavel Dorofeyev", "F"),
    (45, "Jack Eichel", "F"),
    (46, "Jimmy Snuggerud", "F"),
    (47, "Quinton Byfield", "F"),
    (48, "Luke Hughes", "D"),
    (49, "Brock Faber", "D"),
    (50, "Beckett Sennecke", "F"),
    (51, "Kirill Marchenko", "F"),
    (52, "Tage Thompson", "F"),
    (53, "Kyle Connor", "F"),
    (54, "Jackson LaCombe", "D"),
    (55, "Ryan Leonard", "F"),
    (56, "Matthew Knies", "F"),
    (57, "Robert Thomas", "F"),
    (58, "Mikko Rantanen", "F"),
    (59, "Bowen Byram", "D"),
    (60, "Alex DeBrincat", "F"),
    (61, "Matthew Tkachuk", "F"),
    (62, "Zach Benson", "F"),
    (63, "Alexis Lafreniere", "F"),
    (64, "Ilya Protas", "F"),
    (65, "Benjamin Kindel", "F"),
    (66, "Ivar Stenberg", "F"),
    (67, "Mitch Marner", "F"),
    (68, "William Eklund", "F"),
    (69, "Matvei Michkov", "F"),
    (70, "Jake Guentzel", "F"),
    (71, "Miro Heiskanen", "D"),
    (72, "Dylan Cozens", "F"),
    (73, "Jackson Blake", "F"),
    (74, "Nico Hischier", "F"),
    (75, "Cole Hutson", "D"),
    (76, "Matty Beniers", "F"),
    (77, "Clayton Keller", "F"),
    (78, "William Nylander", "F"),
    (79, "Thomas Harley", "D"),
    (80, "Josh Doan", "F"),
    (81, "Matvei Gridin", "F"),
    (82, "Frank Nazar", "F"),
    (83, "Aleksander Barkov", "F"),
    (84, "Luke Evangelista", "F"),
    (85, "Jakob Chychrun", "D"),
    (86, "Adrian Kempe", "F"),
    (87, "Trevor Zegras", "F"),
    (88, "Logan Stankoven", "F"),
    (89, "Aliaksei Protas", "F"),
    (90, "Simon Nemec", "D"),
    (91, "Sam Reinhart", "F"),
    (92, "Andrei Svechnikov", "F"),
    (93, "Alex Laferriere", "F"),
    (94, "Adam Fox", "D"),
    (95, "Mark Scheifele", "F"),
    (96, "Matt Coronato", "F"),
    (97, "Sebastian Aho", "F"),
    (98, "Filip Forsberg", "F"),
    (99, "Darren Raddysh", "D"),
    (100, "Noah Dobson", "D"),
    (101, "Owen Power", "D"),
    (102, "JJ Peterka", "F"),
    (103, "Cole Perfetti", "F"),
    (104, "Owen Tippett", "F"),
    (105, "Igor Chernyshov", "F"),
    (106, "Gabriel Vilardi", "F"),
    (107, "Brayden Point", "F"),
    (108, "Mason McTavish", "F"),
    (109, "Philip Broberg", "D"),
    (110, "Artemi Panarin", "F"),
    (111, "Marco Rossi", "F"),
    (112, "Tyson Foerster", "F"),
    (113, "Anton Lundell", "F"),
    (114, "Mikhail Sergachev", "D"),
    (115, "Elias Pettersson", "F"),
    (116, "Jesper Bratt", "F"),
    (117, "Simon Edvinsson", "D"),
    (118, "Roope Hintz", "F"),
    (119, "Bo Horvat", "F"),
    (120, "Dylan Larkin", "F"),
    (121, "Alex Tuch", "F"),
    (122, "Shane Pinto", "F"),
    (123, "Mathew Barzal", "F"),
    (124, "Will Cuylle", "F"),
    (125, "Michael Misa", "F"),
    (126, "Timo Meier", "F"),
    (127, "Charlie McAvoy", "D"),
    (128, "Fraser Minten", "F"),
    (129, "Nikolaj Ehlers", "F"),
    (130, "Morgan Geekie", "F"),
    (131, "Drake Batherson", "F"),
    (132, "Josh Morrissey", "D"),
    (133, "Alexander Nikishin", "D"),
    (134, "Nick Schmaltz", "F"),
    (135, "Joel Eriksson Ek", "F"),
    (136, "Connor McMichael", "F"),
    (137, "Denton Mateychuk", "D"),
    (138, "Mavrik Bourque", "F"),
    (139, "Jake Neighbours", "F"),
    (140, "Jiri Kulich", "F"),
    (141, "Matt Savoie", "F"),
    (142, "Travis Konecny", "F"),
    (143, "Jack Quinn", "F"),
    (144, "Zach Hyman", "F"),
    (145, "Mattias Samuelsson", "D"),
    (146, "Roman Kantserov", "F"),
    (147, "Filip Hronek", "D"),
    (148, "Mika Zibanejad", "F"),
    (149, "Dylan Strome", "F"),
    (150, "K'Andre Miller", "D"),
    (151, "Kevin Fiala", "F"),
    (152, "Mark Stone", "F"),
    (153, "Jordan Kyrou", "F"),
    (154, "Gabe Perreault", "F"),
    (155, "Tom Wilson", "F"),
    (156, "John Carlson", "D"),
    (157, "Dawson Mercer", "F"),
    (158, "Thomas Chabot", "D"),
    (159, "Cameron York", "D"),
    (160, "Anthony Cirelli", "F"),
    (161, "Valeri Nichushkin", "F"),
    (162, "Carter Yakemchuk", "D"),
    (163, "Josh Norris", "F"),
    (164, "Bryan Rust", "F"),
    (165, "Vince Dunn", "D"),
    (166, "Jared McCann", "F"),
    (167, "Roman Josi", "D"),
    (168, "Noah Hanifin", "D"),
    (169, "Rickard Rakell", "F"),
    (170, "J.T. Miller", "F"),
    (171, "Rasmus Andersson", "D"),
    (172, "Pavel Mintyukov", "D"),
    (173, "Mackie Samoskevich", "F"),
    (174, "Shane Wright", "F"),
    (175, "Shayne Gostisbehere", "D"),
    (176, "Sam Malinski", "D"),
    (177, "John Tavares", "F"),
    (178, "Brock Nelson", "F"),
    (179, "MacKenzie Weegar", "D"),
    (180, "Tomas Hertl", "F"),
    (181, "Shea Theodore", "D"),
    (182, "Viktor Arvidsson", "F"),
    (183, "Artturi Lehkonen", "F"),
    (184, "Arseniy Gritsyuk", "F"),
    (185, "Vasily Podkolzin", "F"),
    (186, "Erik Karlsson", "D"),
    (187, "Nazem Kadri", "F"),
    (188, "Sam Bennett", "F"),
    (189, "Sidney Crosby", "F"),
    (190, "Olen Zellweger", "D"),
    (191, "Sean Durzi", "D"),
    (192, "Bobby McMann", "F"),
    (193, "J.J. Moser", "D"),
    (194, "Seth Jones", "D"),
    (195, "Kaiden Guhle", "D"),
    (196, "Dougie Hamilton", "D"),
    (197, "Ryan O'Reilly", "F"),
    (198, "Noah Cates", "F"),
    (199, "Ryan Nugent-Hopkins", "F"),
    (200, "Vincent Trocheck", "F"),
    (201, "Dmitri Voronkov", "F"),
    (202, "Gabriel Landeskog", "F"),
    (203, "Devon Toews", "D"),
    (204, "Ivan Barbashev", "F"),
    (205, "Darnell Nurse", "D"),
    (206, "Martin Fehervary", "D"),
    (207, "Braden Schneider", "D"),
    (208, "Ivan Provorov", "D"),
    (209, "Pavel Zacha", "F"),
    (210, "Victor Hedman", "D"),
    (211, "Troy Terry", "F"),
    (212, "Esa Lindell", "D"),
    (213, "Jake DeBrusk", "F"),
    (214, "Mason Marchment", "F"),
    (215, "Yegor Chinakhov", "F"),
    (216, "Pierre-Luc Dubois", "F"),
    (217, "Alexander Romanov", "D"),
    (218, "Easton Cowan", "F"),
    (219, "Travis Sanheim", "D"),
    (220, "Jamie Drysdale", "D"),
    (221, "Steven Stamkos", "F"),
    (222, "Elias Lindholm", "F"),
    (223, "Jordan Spence", "D"),
    (224, "Brock Boeser", "F"),
    (225, "Patrick Kane", "F"),
    (226, "Anthony Mantha", "F"),
    (227, "William Karlsson", "F"),
    (228, "Ryan Hartman", "F"),
    (229, "Mike Matheson", "D"),
    (230, "Emil Heineman", "F"),
    (231, "Brandon Montour", "D"),
    (232, "Pavel Buchnevich", "F"),
    (233, "Jacob Trouba", "D"),
    (234, "Jake Walman", "D"),
    (235, "Carter Verhaeghe", "F"),
    (236, "Aaron Ekblad", "D"),
    (237, "Colton Parayko", "D"),
    (238, "Lawson Crouse", "F"),
    (239, "Justin Sourdif", "F"),
    (240, "Morgan Frost", "F"),
    (241, "Dylan Samberg", "D"),
    (242, "Morgan Rielly", "D"),
    (243, "Theo Lindstein", "D"),
    (244, "Kyle Palmieri", "F"),
    (245, "Mikael Granlund", "F"),
    (246, "Justin Faulk", "D"),
    (247, "Tyler Bertuzzi", "F"),
    (248, "Sean Walker", "D"),
    (249, "Mattias Ekholm", "D"),
    (250, "Blake Coleman", "F"),
    (251, "Jake McCabe", "D"),
    (252, "Gustav Forsling", "D"),
    (253, "Charlie Coyle", "F"),
    (254, "Christian Dvorak", "F"),
    (255, "Alex Ovechkin", "F"),
    (256, "Tyler Seguin", "F"),
    (257, "Matt Duchene", "F"),
    (258, "Sean Monahan", "F"),
    (259, "Oliver Kapanen", "F"),
    (260, "Damon Severson", "D"),
    (261, "Jason Zucker", "F"),
    (262, "Adam Larsson", "D"),
    (263, "Kent Johnson", "F"),
    (264, "Jaccob Slavin", "D"),
    (265, "Evgeni Malkin", "F"),
    (266, "Neal Pionk", "D"),
    (267, "Vladislav Gavrikov", "D"),
    (268, "Gage Goncalves", "F"),
    (269, "Tyler Toffoli", "F"),
    (270, "Mats Zuccarello", "F"),
    (271, "Rasmus Sandin", "D"),
    (272, "Victor Olofsson", "F"),
    (273, "Brad Marchand", "F"),
    (274, "Jonas Brodin", "D"),
    (275, "Anthony DeAngelo", "D"),
    (276, "Chris Kreider", "F"),
    (277, "Fabian Zetterlund", "F"),
    (278, "Ross Colton", "F"),
    (279, "Jonathan Huberdeau", "F"),
    (280, "Trevor Moore", "F"),
    (281, "Matt Roy", "D"),
    (282, "Jordan Eberle", "F"),
    (283, "Anders Lee", "F"),
    (284, "Ryan Pulock", "D"),
    (285, "Brayden McNabb", "D"),
    (286, "Noah Ostlund", "F"),
    (287, "Artem Zub", "D"),
    (288, "Simon Holmstrom", "F"),
    (289, "Danila Yurov", "F"),
    (290, "Ryan Poehling", "F"),
    (291, "Hampus Lindholm", "D"),
    (292, "Josh Manson", "D"),
    (293, "Taylor Hall", "F"),
    (294, "Kaapo Kakko", "F"),
    (295, "Brayden Schenn", "F"),
    (296, "Jaden Schwartz", "F"),
    (297, "Filip Chytil", "F"),
    (298, "Alexander Wennberg", "F"),
    (299, "Barrett Hayton", "F"),
    (300, "Nikita Zadorov", "D"),
    (301, "Oliver Ekman-Larsson", "D"),
    (302, "Ryan McDonagh", "D"),
    (303, "Boone Jenner", "F"),
    (304, "Chandler Stephenson", "F"),
    (305, "Andrew Copp", "F"),
    (306, "Yan Kuznetsov", "D"),
    (307, "Jared Spurgeon", "D"),
    (308, "Adam Pelech", "D"),
    (309, "Mikael Backlund", "F"),
    (310, "Brent Burns", "D"),
    (311, "Mikey Anderson", "D"),
    (312, "Jack Roslovic", "F"),
    (313, "John Marino", "D"),
    (314, "Tommy Novak", "F"),
    (315, "Brady Skjei", "D"),
    (316, "Joel Farabee", "F"),
    (317, "Drew Doughty", "D"),
    (318, "Mario Ferraro", "D"),
    (319, "Jacob Middleton", "D"),
    (320, "Alexandre Carrier", "D"),
    (321, "Zayne Parekh", "D"),
    (322, "Rasmus Ristolainen", "D"),
    (323, "Joel Edmundson", "D"),
    (324, "Chris Tanev", "D"),
    (325, "Claude Giroux", "F"),
    (326, "Kris Letang", "D"),
    (327, "Samuel Girard", "D"),
    (328, "Louis Crevier", "D"),
    (329, "Dmitry Orlov", "D"),
    (330, "Kiefer Sherwood", "F"),
    (331, "Ryan McLeod", "F"),
    (332, "Nick Seeler", "D"),
    (333, "Connor Brown", "F"),
    (334, "Jalen Chatfield", "D"),
    (335, "Jonathan Aspirot", "D"),
    (336, "Casey Mittelstadt", "F"),
    (337, "Jamie Benn", "F"),
    (338, "Charle-Edouard D'Astous", "D"),
    (339, "Ben Chiarot", "D"),
    (340, "Connor Murphy", "D"),
    (341, "Dylan DeMelo", "D"),
    (342, "Yanni Gourde", "F"),
    (343, "Eeli Tolvanen", "F"),
    (344, "Jordan Staal", "F"),
    (345, "Alex Newhook", "F"),
    (346, "Zach Whitecloud", "D"),
    (347, "Matthew Wood", "F"),
    (348, "Daniil Miromanov", "D"),
    (349, "Brett Pesce", "D"),
    (350, "Radko Gudas", "D"),
    (351, "Brett Howden", "F"),
    (352, "Emmitt Finnie", "F"),
    (353, "Logan Mailloux", "D"),
    (354, "Zack Bolduc", "F"),
    (355, "James Hagens", "F"),
    (356, "Konsta Helenius", "F"),
    (357, "Collin Graf", "F"),
    (358, "Viggo Bjorck", "F"),
    (359, "Marcus Pettersson", "D"),
    (360, "Alex Bump", "F"),
    (361, "Sam Rinzel", "D"),
    (362, "Cole Sillinger", "F"),
    (363, "Ridly Greig", "F"),
    (364, "Eetu Luostarinen", "F"),
    (365, "Connor Zary", "F"),
    (366, "Calum Ritchie", "F"),
    (367, "Charlie Stramel", "F"),
    (368, "Erik Cernak", "D"),
    (369, "Dalibor Dvorsky", "F"),
    (370, "Dominic James", "F"),
    (371, "Tij Iginla", "F"),
    (372, "Nicholas Robertson", "F"),
    (373, "Victor Eklund", "F"),
    (374, "Maveric Lamoureux", "D"),
    (375, "Marco Kasper", "F"),
    (376, "Sean Couturier", "F"),
    (377, "Conor Timmins", "D"),
    (378, "Ryan Greene", "F"),
    (379, "Otto Stenberg", "F"),
    (380, "Vitali Pinchuk", "F"),
    (381, "Jack Drury", "F"),
    (382, "Braeden Bowman", "F"),
    (383, "Tyson Hinds", "D"),
    (384, "Peyton Krebs", "F"),
    (385, "Artyom Levshunov", "D"),
    (386, "Tyler Kleven", "D"),
    (387, "Brandon Carlo", "D"),
    (388, "Trevor Connelly", "F"),
    (389, "Zeev Buium", "D"),
    (390, "Tom Willander", "D"),
    (391, "Roger McQueen", "F"),
    (392, "Nick Lardis", "F"),
    (393, "Dante Fabbro", "D"),
    (394, "Bobby Brink", "F"),
    (395, "Berkly Catton", "F"),
    (396, "Bradly Nadeau", "F"),
    (397, "Yegor Sharangovich", "F"),
    (398, "Matthew Poitras", "F"),
    (399, "Ryan Ufko", "D"),
    (400, "Adam Jiricek", "D"),
    (401, "Brad Lambert", "F"),
    (402, "Niko Mikkola", "D"),
    (403, "Jackson Smith", "D"),
    (404, "Parker Kelly", "F"),
    (405, "Sam Dickinson", "D"),
    (406, "Liam Ohgren", "F"),
    (407, "Marat Khusnutdinov", "F"),
    (408, "Jakob Pelletier", "F"),
    (409, "Noah Laba", "F"),
    (410, "Andrew Cristall", "F"),
    (411, "Gavin Brindley", "F"),
    (412, "Connor Dewar", "F"),
    (413, "Tristan Luneau", "D"),
    (414, "Danil But", "F"),
    (415, "Justin Hryckowian", "F"),
    (416, "Evander Kane", "F"),
    (417, "Mikey Eyssimont", "F"),
    (418, "Ian Cole", "D"),
    (419, "Matthew Robertson", "D"),
    (420, "Matias Maccelli", "F"),
    (421, "Samuel Honzek", "F"),
    (422, "Cole Eiserman", "F"),
    (423, "Conor Geekie", "F"),
    (424, "Luca Del Bel Belluz", "F"),
    (425, "Denver Barkey", "F"),
    (426, "Caleb Desnoyers", "F"),
    (427, "Luca Cagnoni", "D"),
    (428, "Arthur Kaliyev", "F"),
    (429, "Warren Foegele", "F"),
    (430, "Maxim Strbak", "D"),
    (431, "Jack McBain", "F"),
    (432, "Maxim Shabanov", "F"),
    (433, "Michael Brandsegg-Nygard", "F"),
    (434, "Zachary L'Heureux", "F"),
    (435, "Colby Barlow", "F"),
    (436, "Kirby Dach", "F"),
    (437, "Axel Sandin Pellikka", "D"),
    (438, "Tanner Molendyk", "D"),
    (439, "Drew Helleson", "D"),
    (440, "Rutger McGroarty", "F"),
    (441, "Hunter Brzustewicz", "D"),
    (442, "Joel Nystrom", "D"),
    (443, "Conor Garland", "F"),
    (444, "Ilya Mikheyev", "F"),
    (445, "John Klingberg", "D"),
    (446, "Michael Amadio", "F"),
    (447, "Michael Kesselring", "D"),
    (448, "Brayden Yager", "F"),
    (449, "Alexandre Texier", "F"),
    (450, "Owen Beck", "F"),
    (451, "Brady Martin", "F"),
    (452, "Lenni Hameenaho", "F"),
    (453, "Eric Pohlkamp", "D"),
    (454, "Kaedan Korczak", "D"),
    (455, "Oliver Moore", "F"),
    (456, "Nate Danielson", "F"),
    (457, "Erik Haula", "F"),
    (458, "Ivan Miroshnichenko", "F"),
    (459, "Morgan Barron", "F"),
    (460, "Anton Wahlberg", "F"),
    (461, "Aatu Raty", "F"),
    (462, "Justin Carbonneau", "F"),
    (463, "Jared Wright", "F"),
    (464, "Vladimir Tarasenko", "F"),
    (465, "Nils Lundkvist", "D"),
]


def normalize(name):
    name = unicodedata.normalize("NFKD", name)
    name = name.encode("ascii", "ignore").decode("ascii")
    name = name.lower()
    name = re.sub(r"\b(jr|sr|ii|iii|iv|v)\b\.?", "", name)
    name = re.sub(r"[^a-z\s]", "", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name


with open(MASTER_PATH, newline="") as f:
    reader = csv.DictReader(f)
    fieldnames = list(reader.fieldnames)
    rows = list(reader)

if OLD_SOURCE_COL in fieldnames:
    fieldnames = [SOURCE_COL if fn == OLD_SOURCE_COL else fn for fn in fieldnames]
    for row in rows:
        row[SOURCE_COL] = ""
        if OLD_SOURCE_COL in row:
            del row[OLD_SOURCE_COL]
elif SOURCE_COL not in fieldnames:
    fieldnames.insert(fieldnames.index("Average Rank"), SOURCE_COL)
    for row in rows:
        row[SOURCE_COL] = ""
else:
    for row in rows:
        row[SOURCE_COL] = ""

lookup = {normalize(row["Player"]): row for row in rows}

new_players = []
for rank, name, pos in SKATER_DATA:
    key = normalize(name)
    if key in lookup:
        lookup[key][SOURCE_COL] = rank
    else:
        new_row = {fn: "" for fn in fieldnames}
        new_row["Player"] = name
        new_row["Position"] = pos
        new_row["Age"] = ""
        new_row[SOURCE_COL] = rank
        new_row["Average Rank"] = ""
        new_row["Rank Variance"] = ""
        new_players.append(new_row)
        rows.append(new_row)
        lookup[key] = new_row

with open(MASTER_PATH, "w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f"Merged {len(SKATER_DATA)} Lineup Experts skaters.")
print(f"  Matched: {len(SKATER_DATA) - len(new_players)}")
print(f"  New players added: {len(new_players)}")
if new_players:
    for p in new_players:
        print(f"    + {p['Player']}")

subprocess.run(["python3", os.path.join(os.path.dirname(__file__), "recalculate.py"), MASTER_PATH])
