#!/usr/bin/env python3
"""Merge Owen FBB Invitational startup draft (Feb 2026) into baseball master CSV.
Overall pick number is used as rank."""

import csv
import re
import unicodedata
import subprocess

MASTER_PATH = "baseball/baseball_rankings_master.csv"
NEW_COL = "Owen FBB Invitational (Startup, Feb 2026)"

# All 500 picks: (ov_pick, player_name, pos, team)
# Two players named "Max Muncy" exist (prospect LAD + veteran ATH); first pick wins.
DRAFT_PICKS = [
    (1,   "Shohei Ohtani",              "UT",  "LAD"),
    (2,   "Bobby Witt Jr.",             "SS",  "KC"),
    (3,   "Juan Soto",                  "OF",  "NYM"),
    (4,   "Aaron Judge",                "OF",  "NYY"),
    (5,   "Corbin Carroll",             "OF",  "ARI"),
    (6,   "Junior Caminero",            "3B",  "TB"),
    (7,   "Jose Ramirez",               "3B",  "CLE"),
    (8,   "Julio Rodriguez",            "OF",  "SEA"),
    (9,   "Elly De La Cruz",            "SS",  "CIN"),
    (10,  "Roman Anthony",              "OF",  "BOS"),
    (11,  "Ronald Acuna Jr.",           "OF",  "ATL"),
    (12,  "Nick Kurtz",                 "1B",  "ATH"),
    (13,  "Paul Skenes",                "SP",  "PIT"),
    (14,  "Tarik Skubal",               "SP",  "DET"),
    (15,  "Gunnar Henderson",           "SS",  "BAL"),
    (16,  "Jackson Chourio",            "OF",  "MIL"),
    (17,  "James Wood",                 "OF",  "WSH"),
    (18,  "Vladimir Guerrero Jr.",      "1B",  "TOR"),
    (19,  "Garrett Crochet",            "SP",  "BOS"),
    (20,  "Kyle Tucker",                "OF",  "LAD"),
    (21,  "Fernando Tatis Jr.",         "OF",  "SD"),
    (22,  "Cal Raleigh",                "C",   "SEA"),
    (23,  "Zach Neto",                  "SS",  "LAA"),
    (24,  "Wyatt Langford",             "OF",  "TEX"),
    (25,  "Yordan Alvarez",             "UT",  "HOU"),
    (26,  "Francisco Lindor",           "SS",  "NYM"),
    (27,  "Yoshinobu Yamamoto",         "SP",  "LAD"),
    (28,  "Ketel Marte",                "2B",  "ARI"),
    (29,  "Bryan Woo",                  "SP",  "SEA"),
    (30,  "Pete Crow-Armstrong",        "OF",  "CHC"),
    (31,  "Hunter Greene",              "SP",  "CIN"),
    (32,  "Cristopher Sanchez",         "SP",  "PHI"),
    (33,  "Josh Naylor",                "1B",  "SEA"),
    (34,  "Kyle Schwarber",             "UT",  "PHI"),
    (35,  "Hunter Brown",               "SP",  "HOU"),
    (36,  "Logan Gilbert",              "SP",  "SEA"),
    (37,  "Jackson Merrill",            "OF",  "SD"),
    (38,  "Cole Ragans",                "SP",  "KC"),
    (39,  "Rafael Devers",              "UT",  "SF"),
    (40,  "Jazz Chisholm Jr.",          "2B",  "NYY"),
    (41,  "Jacob Misiorowski",          "SP",  "MIL"),
    (42,  "Eury Perez",                 "SP",  "MIA"),
    (43,  "Ben Rice",                   "1B",  "NYY"),
    (44,  "Pete Alonso",                "1B",  "BAL"),
    (45,  "Matt Olson",                 "1B",  "ATL"),
    (46,  "Manny Machado",              "3B",  "SD"),
    (47,  "Geraldo Perdomo",            "SS",  "ARI"),
    (48,  "Vinnie Pasquantino",         "1B",  "KC"),
    (49,  "Riley Greene",               "OF",  "DET"),
    (50,  "Logan Webb",                 "SP",  "SF"),
    (51,  "Jackson Holliday",           "2B",  "BAL"),
    (52,  "Chase Burns",                "SP",  "CIN"),
    (53,  "Freddy Peralta",             "SP",  "NYM"),
    (54,  "Brent Rooker",               "UT",  "ATH"),
    (55,  "Spencer Schwellenbach",      "SP",  "ATL"),
    (56,  "Max Fried",                  "SP",  "NYY"),
    (57,  "Trea Turner",                "SS",  "PHI"),
    (58,  "William Contreras",          "C",   "MIL"),
    (59,  "Austin Riley",               "3B",  "ATL"),
    (60,  "Trey Yesavage",              "SP",  "TOR"),
    (61,  "Jac Caglianone",             "OF",  "KC"),
    (62,  "Bubba Chandler",             "SP",  "PIT"),
    (63,  "Samuel Basallo",             "C",   "BAL"),
    (64,  "Nolan McLean",               "SP",  "NYM"),
    (65,  "Maikel Garcia",              "3B",  "KC"),
    (66,  "Mookie Betts",               "SS",  "LAD"),
    (67,  "Joe Ryan",                   "SP",  "MIN"),
    (68,  "Tyler Soderstrom",           "OF",  "ATH"),
    (69,  "Dylan Cease",                "SP",  "TOR"),
    (70,  "CJ Abrams",                  "SS",  "WSH"),
    (71,  "Dylan Crews",                "OF",  "WSH"),
    (72,  "George Kirby",               "SP",  "SEA"),
    (73,  "Cody Bellinger",             "OF",  "NYY"),
    (74,  "Brice Turang",               "2B",  "MIL"),
    (75,  "Spencer Torkelson",          "1B",  "DET"),
    (76,  "Jesus Luzardo",              "SP",  "PHI"),
    (77,  "Corey Seager",               "SS",  "TEX"),
    (78,  "Shea Langeliers",            "C",   "ATH"),
    (79,  "Bo Bichette",                "SS",  "NYM"),
    (80,  "Bryce Harper",               "1B",  "PHI"),
    (81,  "Spencer Strider",            "SP",  "ATL"),
    (82,  "Jarren Duran",               "OF",  "BOS"),
    (83,  "Jordan Westburg",            "3B",  "BAL"),
    (84,  "Cade Smith",                 "RP",  "CLE"),
    (85,  "Jacob Wilson",               "SS",  "ATH"),
    (86,  "Alex Bregman",               "3B",  "CHC"),
    (87,  "Bryce Eldridge",             "UT",  "SF"),
    (88,  "Jeremy Pena",                "SS",  "HOU"),
    (89,  "Nico Hoerner",               "2B",  "CHC"),
    (90,  "Drake Baldwin",              "C",   "ATL"),
    (91,  "Kyle Bradish",               "SP",  "BAL"),
    (92,  "Framber Valdez",             "SP",  "DET"),
    (93,  "Luke Keaschall",             "2B",  "MIN"),
    (94,  "Colson Montgomery",          "SS",  "CHW"),
    (95,  "Chris Sale",                 "SP",  "ATL"),
    (96,  "Mason Miller",               "RP",  "SD"),
    (97,  "Michael Harris II",          "OF",  "ATL"),
    (98,  "Cam Schlittler",             "SP",  "NYY"),
    (99,  "MacKenzie Gore",             "SP",  "TEX"),
    (100, "Agustin Ramirez",            "C",   "MIA"),
    (101, "Freddie Freeman",            "1B",  "LAD"),
    (102, "Kyle Stowers",               "OF",  "MIA"),
    (103, "Emmet Sheehan",              "SP",  "LAD"),
    (104, "Luis Robert Jr.",            "OF",  "NYM"),
    (105, "Oneil Cruz",                 "OF",  "PIT"),
    (106, "Jacob deGrom",               "SP",  "TEX"),
    (107, "Jonathan Aranda",            "1B",  "TB"),
    (108, "Steven Kwan",                "OF",  "CLE"),
    (109, "Seiya Suzuki",               "UT",  "CHC"),
    (110, "Pablo Lopez",                "SP",  "MIN"),
    (111, "Roki Sasaki",                "SP",  "LAD"),
    (112, "Carter Jensen",              "C",   "KC"),
    (113, "Andres Munoz",               "RP",  "SEA"),
    (114, "Willy Adames",               "SS",  "SF"),
    (115, "Cade Horton",                "SP",  "CHC"),
    (116, "Michael Busch",              "1B",  "CHC"),
    (117, "Byron Buxton",               "OF",  "MIN"),
    (118, "Jhoan Duran",                "RP",  "PHI"),
    (119, "Lawrence Butler",            "OF",  "ATH"),
    (120, "Edward Cabrera",             "SP",  "CHC"),
    (121, "Tanner Bibee",               "SP",  "CLE"),
    (122, "Matt Shaw",                  "3B",  "CHC"),
    (123, "Edwin Diaz",                 "RP",  "LAD"),
    (124, "Gavin Williams",             "SP",  "CLE"),
    (125, "Hunter Goodman",             "C",   "COL"),
    (126, "Wilyer Abreu",               "OF",  "BOS"),
    (127, "Sal Stewart",                "1B",  "CIN"),
    (128, "Trevor Story",               "SS",  "BOS"),
    (129, "Jared Jones",                "SP",  "PIT"),
    (130, "Marcelo Mayer",              "3B",  "BOS"),
    (131, "Addison Barger",             "3B",  "TOR"),
    (132, "Nick Lodolo",                "SP",  "CIN"),
    (133, "Ryan Pepiot",                "SP",  "TB"),
    (134, "Michael King",               "SP",  "SD"),
    (135, "Andrew Abbott",              "SP",  "CIN"),
    (136, "Sandy Alcantara",            "SP",  "MIA"),
    (137, "Noelvi Marte",               "OF",  "CIN"),
    (138, "Tyler Glasnow",              "SP",  "LAD"),
    (139, "Will Smith",                 "C",   "LAD"),
    (140, "Josh Hader",                 "RP",  "HOU"),
    (141, "Blake Snell",                "SP",  "LAD"),
    (142, "Shane McClanahan",           "SP",  "TB"),
    (143, "Adley Rutschman",            "C",   "BAL"),
    (144, "Hurston Waldrep",            "SP",  "ATL"),
    (145, "Nick Pivetta",               "SP",  "SD"),
    (146, "Payton Tolle",               "RP",  "BOS"),
    (147, "Brandon Woodruff",           "SP",  "MIL"),
    (148, "Chandler Simpson",           "OF",  "TB"),
    (149, "Drew Rasmussen",             "SP",  "TB"),
    (150, "Randy Arozarena",            "OF",  "SEA"),
    (151, "Ceddanne Rafaela",           "OF",  "BOS"),
    (152, "Daylen Lile",                "OF",  "WSH"),
    (153, "Ivan Herrera",               "UT",  "STL"),
    (154, "Zack Wheeler",               "SP",  "PHI"),
    (155, "Ozzie Albies",               "2B",  "ATL"),
    (156, "Jung Hoo Lee",               "OF",  "SF"),
    (157, "Xavier Edwards",             "2B",  "MIA"),
    (158, "Jonah Tong",                 "SP",  "NYM"),
    (159, "Jackson Jobe",               "SP",  "DET"),
    (160, "Andy Pages",                 "OF",  "LAD"),
    (161, "Dansby Swanson",             "SS",  "CHC"),
    (162, "Masyn Winn",                 "SS",  "STL"),
    (163, "Jakob Marsee",               "OF",  "MIA"),
    (164, "Jasson Dominguez",           "OF",  "NYY"),
    (165, "Isaac Paredes",              "3B",  "HOU"),
    (166, "Gleyber Torres",             "2B",  "DET"),
    (167, "Kris Bubic",                 "SP",  "KC"),
    (168, "Eugenio Suarez",             "3B",  "CIN"),
    (169, "Jordan Lawlar",              "3B",  "ARI"),
    (170, "Jo Adell",                   "OF",  "LAA"),
    (171, "Kyle Teel",                  "C",   "CHW"),
    (172, "Connelly Early",             "SP",  "BOS"),
    (173, "Kevin Gausman",              "SP",  "TOR"),
    (174, "Sonny Gray",                 "SP",  "BOS"),
    (175, "Bryce Miller",               "SP",  "SEA"),
    (176, "Trevor Rogers",              "SP",  "BAL"),
    (177, "Luis Castillo",              "SP",  "SEA"),
    (178, "Ranger Suarez",              "SP",  "BOS"),
    (179, "Cam Smith",                  "OF",  "HOU"),
    (180, "Aroldis Chapman",            "RP",  "BOS"),
    (181, "Abner Uribe",                "RP",  "MIL"),
    (182, "Kyle Manzardo",              "UT",  "CLE"),
    (183, "Shane Bieber",               "SP",  "TOR"),
    (184, "Yandy Diaz",                 "UT",  "TB"),
    (185, "David Bednar",               "RP",  "NYY"),
    (186, "Sal Frelick",                "OF",  "MIL"),
    (187, "Shane Baz",                  "SP",  "BAL"),
    (188, "Matt Chapman",               "3B",  "SF"),
    (189, "Brendan Donovan",            "2B",  "SEA"),
    (190, "Royce Lewis",                "3B",  "MIN"),
    (191, "Bryson Stott",               "2B",  "PHI"),
    (192, "Shota Imanaga",              "SP",  "CHC"),
    (193, "Corbin Burnes",              "SP",  "ARI"),
    (194, "Christian Yelich",           "UT",  "MIL"),
    (195, "Ryan Weathers",              "SP",  "NYY"),
    (196, "Devin Williams",             "RP",  "NYM"),
    (197, "Yainer Diaz",                "C",   "HOU"),
    (198, "Dylan Beavers",              "OF",  "BAL"),
    (199, "Gerrit Cole",                "SP",  "NYY"),
    (200, "Logan O'Hoppe",              "C",   "LAA"),
    (201, "Mike Trout",                 "UT",  "LAA"),
    (202, "Jack Leiter",                "SP",  "TEX"),
    (203, "Luis Garcia Jr.",            "2B",  "WSH"),
    (204, "Caleb Durbin",               "3B",  "BOS"),
    (205, "Braxton Ashcraft",           "RP",  "PIT"),
    (206, "Alec Burleson",              "1B",  "STL"),
    (207, "Giancarlo Stanton",          "UT",  "NYY"),
    (208, "Zac Gallen",                 "SP",  "ARI"),
    (209, "Luis Arraez",                "1B",  "SF"),
    (210, "Ezequiel Tovar",             "SS",  "COL"),
    (211, "Ryne Nelson",                "SP",  "ARI"),
    (212, "Jurickson Profar",           "OF",  "ATL"),
    (213, "Grayson Rodriguez",          "SP",  "LAA"),
    (214, "Kodai Senga",                "SP",  "NYM"),
    (215, "Logan Henderson",            "SP",  "MIL"),
    (216, "Alejandro Kirk",             "C",   "TOR"),
    (217, "Heliot Ramos",               "OF",  "SF"),
    (218, "Trevor Megill",              "RP",  "MIL"),
    (219, "Carlos Rodon",               "SP",  "NYY"),
    (220, "Joe Musgrove",               "SP",  "SD"),
    (221, "Ian Happ",                   "OF",  "CHC"),
    (222, "Owen Caissie",               "OF",  "MIA"),
    (223, "Brandon Lowe",               "2B",  "PIT"),
    (224, "Noah Cameron",               "SP",  "KC"),
    (225, "Jack Flaherty",              "SP",  "DET"),
    (226, "Willson Contreras",          "1B",  "BOS"),
    (227, "George Springer",            "OF",  "TOR"),
    (228, "Jose Altuve",                "2B",  "HOU"),
    (229, "Matt McLain",                "2B",  "CIN"),
    (230, "Bailey Ober",                "SP",  "MIN"),
    (231, "Coby Mayo",                  "1B",  "BAL"),
    (232, "Taylor Ward",                "OF",  "BAL"),
    (233, "Ryan Helsley",               "RP",  "BAL"),
    (234, "Brandon Nimmo",              "OF",  "TEX"),
    (235, "Kristian Campbell",          "2B",  "BOS"),
    (236, "Evan Carter",                "OF",  "TEX"),
    (237, "TJ Friedl",                  "OF",  "CIN"),
    (238, "Colton Cowser",              "OF",  "BAL"),
    (239, "Reese Olson",                "SP",  "DET"),
    (240, "Spencer Horwitz",            "1B",  "PIT"),
    (241, "Brandon Sproat",             "SP",  "MIL"),
    (242, "Justin Steele",              "SP",  "CHC"),
    (243, "Parker Messick",             "SP",  "CLE"),
    (244, "Ernie Clement",              "3B",  "TOR"),
    (245, "Brayan Bello",               "SP",  "BOS"),
    (246, "Quinn Priester",             "SP",  "MIL"),
    (247, "Daniel Palencia",            "RP",  "CHC"),
    (248, "Daulton Varsho",             "OF",  "TOR"),
    (249, "Aaron Nola",                 "SP",  "PHI"),
    (250, "Taj Bradley",                "SP",  "MIN"),
    (251, "Andrew Vaughn",              "1B",  "MIL"),
    (252, "Otto Lopez",                 "SS",  "MIA"),
    (253, "Gabriel Moreno",             "C",   "ARI"),
    (254, "Bryan Reynolds",             "OF",  "PIT"),
    (255, "Emilio Pagan",               "RP",  "CIN"),
    (256, "Jorge Polanco",              "UT",  "NYM"),
    (257, "Zebby Matthews",             "SP",  "MIN"),
    (258, "Nathan Eovaldi",             "SP",  "TEX"),
    (259, "Robbie Ray",                 "SP",  "SF"),
    (260, "Casey Mize",                 "SP",  "DET"),
    (261, "Salvador Perez",             "C",   "KC"),
    (262, "Robert Suarez",              "RP",  "ATL"),
    (263, "Kerry Carpenter",            "OF",  "DET"),
    (264, "Francisco Alvarez",          "C",   "NYM"),
    (265, "Nolan Schanuel",             "1B",  "LAA"),
    (266, "Jordan Walker",              "OF",  "STL"),
    (267, "Anthony Santander",          "UT",  "TOR"),
    (268, "Jose Caballero",             "SS",  "NYY"),
    (269, "Jose Soriano",               "SP",  "LAA"),
    (270, "Christian Walker",           "1B",  "HOU"),
    (271, "Carlos Estevez",             "RP",  "KC"),
    (272, "Miguel Vargas",              "3B",  "CHW"),
    (273, "Brady Singer",               "SP",  "CIN"),
    (274, "Shane Smith",                "SP",  "CHW"),
    (275, "Teoscar Hernandez",          "OF",  "LAD"),
    (276, "Alec Bohm",                  "3B",  "PHI"),
    (277, "Mike Burrows",               "SP",  "HOU"),
    (278, "Luis Gil",                   "SP",  "NYY"),
    (279, "Carlos Correa",              "SS",  "HOU"),
    (280, "Jeff Hoffman",               "RP",  "TOR"),
    (281, "Trent Grisham",              "OF",  "NYY"),
    (282, "Christian Moore",            "2B",  "LAA"),
    (283, "Pete Fairbanks",             "RP",  "MIA"),
    (284, "Cody Ponce",                 "SP",  "TOR"),
    (285, "Ramon Laureano",             "OF",  "SD"),
    (286, "Adolis Garcia",              "OF",  "PHI"),
    (287, "Brett Baty",                 "3B",  "NYM"),
    (288, "Brandon Pfaadt",             "SP",  "ARI"),
    (289, "Josh Lowe",                  "OF",  "LAA"),
    (290, "Anthony Volpe",              "SS",  "NYY"),
    (291, "Moises Ballesteros",         "UT",  "CHC"),
    (292, "Joey Cantillo",              "RP",  "CLE"),
    (293, "Austin Wells",               "C",   "NYY"),
    (294, "Colt Keith",                 "UT",  "DET"),
    (295, "Joe Boyle",                  "SP",  "TB"),
    (296, "Xander Bogaerts",            "SS",  "SD"),
    (297, "Matthew Boyd",               "SP",  "CHC"),
    (298, "Rhett Lowder",               "SP",  "CIN"),
    (299, "Dalton Rushing",             "C",   "LAD"),
    (300, "Griffin Conine",             "OF",  "MIA"),
    (301, "Luisangel Acuna",            "2B",  "CHW"),
    (302, "Raisel Iglesias",            "RP",  "ATL"),
    (303, "Mitch Keller",               "SP",  "PIT"),
    (304, "Jameson Taillon",            "SP",  "CHC"),
    (305, "Chase Meidroth",             "SS",  "CHW"),
    (306, "Harry Ford",                 "C",   "WSH"),
    (307, "Brenton Doyle",              "OF",  "COL"),
    (308, "Max Muncy",                  "3B",  "LAD"),  # prospect (also veteran at 387 ATH)
    (309, "Troy Melton",                "RP",  "DET"),
    (310, "AJ Smith-Shawver",           "SP",  "ATL"),
    (311, "Ian Seymour",                "RP",  "TB"),
    (312, "Luis Morales",               "SP",  "ATH"),
    (313, "Ryan O'Hearn",               "1B",  "PIT"),
    (314, "Lars Nootbaar",              "OF",  "STL"),
    (315, "Johan Oviedo",               "SP",  "BOS"),
    (316, "Spencer Steer",              "1B",  "CIN"),
    (317, "Chad Patrick",               "SP",  "MIL"),
    (318, "Jordan Beck",                "OF",  "COL"),
    (319, "Triston Casas",              "1B",  "BOS"),
    (320, "Will Warren",                "SP",  "NYY"),
    (321, "Max Meyer",                  "SP",  "MIA"),
    (322, "Jose Berrios",               "SP",  "TOR"),
    (323, "Lenyn Sosa",                 "2B",  "CHW"),
    (324, "Mark Vientos",               "3B",  "NYM"),
    (325, "Dominic Canzone",            "OF",  "SEA"),
    (326, "Cade Cavalli",               "SP",  "WSH"),
    (327, "Grant Taylor",               "RP",  "CHW"),
    (328, "Carson Williams",            "SS",  "TB"),
    (329, "Reid Detmers",               "RP",  "LAA"),
    (330, "Mickey Moniak",              "OF",  "COL"),
    (331, "Sean Manaea",                "SP",  "NYM"),
    (332, "Merrill Kelly",              "SP",  "ARI"),
    (333, "Ryan Walker",                "RP",  "SF"),
    (334, "Jake Burger",                "1B",  "TEX"),
    (335, "Brooks Lee",                 "SS",  "MIN"),
    (336, "Jeff McNeil",                "2B",  "ATH"),
    (337, "Jeremiah Estrada",           "RP",  "SD"),
    (338, "Marcus Semien",              "2B",  "NYM"),
    (339, "Josh Smith",                 "SS",  "TEX"),
    (340, "Slade Cecconi",              "SP",  "CLE"),
    (341, "Cole Young",                 "2B",  "SEA"),
    (342, "Michael Soroka",             "SP",  "ARI"),
    (343, "Foster Griffin",             "SP",  "WSH"),
    (344, "Brady House",                "3B",  "WSH"),
    (345, "Griffin Jax",                "RP",  "TB"),
    (346, "Josh Bell",                  "UT",  "MIN"),
    (347, "Clay Holmes",                "SP",  "NYM"),
    (348, "Jacob Lopez",                "SP",  "ATH"),
    (349, "Zach McKinstry",             "3B",  "DET"),
    (350, "J.T. Realmuto",              "C",   "PHI"),
    (351, "Mick Abel",                  "SP",  "MIN"),
    (352, "River Ryan",                 "SP",  "LAD"),
    (353, "Andres Gimenez",             "2B",  "TOR"),
    (354, "CJ Kayfus",                  "OF",  "CLE"),
    (355, "Josh Jung",                  "3B",  "TEX"),
    (356, "Isaac Collins",              "OF",  "KC"),
    (357, "Romy Gonzalez",              "1B",  "BOS"),
    (358, "Adrian Morejon",             "RP",  "SD"),
    (359, "Yusei Kikuchi",              "SP",  "LAA"),
    (360, "Yoan Moncada",               "3B",  "LAA"),
    (361, "Spencer Arrighetti",         "SP",  "HOU"),
    (362, "Robert Garcia",              "RP",  "TEX"),
    (363, "Braydon Fisher",             "RP",  "TOR"),
    (364, "Matt Wallner",               "OF",  "MIN"),
    (365, "Bryan Abreu",                "RP",  "HOU"),
    (366, "Kenley Jansen",              "RP",  "DET"),
    (367, "Zack Littell",               "SP",  ""),
    (368, "David Peterson",             "SP",  "NYM"),
    (369, "Jacob Melton",               "OF",  "TB"),
    (370, "Hayden Birdsong",            "SP",  "SF"),
    (371, "Simeon Woods-Richardson",    "SP",  "MIN"),
    (372, "Riley O'Brien",              "RP",  "STL"),
    (373, "J.P. Crawford",              "SS",  "SEA"),
    (374, "Jonathan India",             "2B",  "KC"),
    (375, "Cedric Mullins",             "OF",  "TB"),
    (376, "Matthew Liberatore",         "SP",  "STL"),
    (377, "Tommy Edman",                "2B",  "LAD"),
    (378, "Cristian Javier",            "SP",  "HOU"),
    (379, "Tyler O'Neill",              "OF",  "BAL"),
    (380, "Edwin Uceta",                "RP",  "TB"),
    (381, "Austin Hays",                "OF",  "CHW"),
    (382, "Andrew Benintendi",          "OF",  "CHW"),
    (383, "Connor Norby",               "3B",  "MIA"),
    (384, "Garrett Whitlock",           "RP",  "BOS"),
    (385, "Willi Castro",               "2B",  "COL"),
    (386, "Braxton Garrett",            "SP",  "MIA"),
    (387, "Max Muncy",                  "3B",  "ATH"),  # veteran — duplicate name, skipped
    (388, "Nolan Arenado",              "3B",  "ARI"),
    (389, "Jack Perkins",               "RP",  "ATH"),
    (390, "Ryan McMahon",               "3B",  "NYY"),
    (391, "Hunter Barco",               "RP",  "PIT"),
    (392, "Ryan Jeffers",               "C",   "MIN"),
    (393, "Tony Santillan",             "RP",  "CIN"),
    (394, "Edgar Quero",                "C",   "CHW"),
    (395, "Jake Cronenworth",           "2B",  "SD"),
    (396, "Lucas Giolito",              "SP",  ""),
    (397, "Hyeseong Kim",               "2B",  "LAD"),
    (398, "JoJo Romero",                "RP",  "STL"),
    (399, "Dennis Santana",             "RP",  "PIT"),
    (400, "Marcell Ozuna",              "UT",  "PIT"),
    (401, "Nolan Gorman",               "3B",  "STL"),
    (402, "Harrison Bader",             "OF",  "SF"),
    (403, "Javier Baez",                "SS",  "DET"),
    (404, "Denzel Clarke",              "OF",  "ATH"),
    (405, "Bo Naylor",                  "C",   "CLE"),
    (406, "Michael Wacha",              "SP",  "KC"),
    (407, "Tyler Stephenson",           "C",   "CIN"),
    (408, "Jake Latz",                  "RP",  "TEX"),
    (409, "Kumar Rocker",               "SP",  "TEX"),
    (410, "Gavin Lux",                  "UT",  "TB"),
    (411, "Jhostynxon Garcia",          "OF",  "PIT"),
    (412, "Landen Roupp",               "SP",  "SF"),
    (413, "Chris Bassitt",              "SP",  "BAL"),
    (414, "Dillon Dingler",             "C",   "DET"),
    (415, "Gavin Sheets",               "OF",  "SD"),
    (416, "Trevor Larnach",             "UT",  "MIN"),
    (417, "Jared Triolo",               "SS",  "PIT"),
    (418, "Joey Ortiz",                 "SS",  "MIL"),
    (419, "Seranthony Dominguez",       "RP",  "CHW"),
    (420, "Dustin May",                 "SP",  "STL"),
    (421, "Ben Joyce",                  "RP",  "LAA"),
    (422, "Jesus Sanchez",              "OF",  "TOR"),
    (423, "Kevin Alcantara",            "OF",  "CHC"),
    (424, "Jeffrey Springs",            "SP",  "ATH"),
    (425, "Zach Eflin",                 "SP",  "BAL"),
    (426, "Nick Yorke",                 "2B",  "PIT"),
    (427, "Tyler Mahle",                "SP",  "SF"),
    (428, "Dean Kremer",                "SP",  "BAL"),
    (429, "Christian Scott",            "SP",  "NYM"),
    (430, "Victor Scott",               "OF",  "STL"),
    (431, "Jake Meyers",                "OF",  "HOU"),
    (432, "Matt Brash",                 "RP",  "SEA"),
    (433, "Reynaldo Lopez",             "SP",  "ATL"),
    (434, "Seth Lugo",                  "SP",  "KC"),
    (435, "Luis Severino",              "SP",  "ATH"),
    (436, "Ryan Bergert",               "SP",  "KC"),
    (437, "Nick Castellanos",           "OF",  "SD"),
    (438, "Ha-Seong Kim",               "SS",  "ATL"),
    (439, "Josiah Gray",                "SP",  "WSH"),
    (440, "Chase Dollander",            "SP",  "COL"),
    (441, "Brice Matthews",             "2B",  "HOU"),
    (442, "Heston Kjerstad",            "OF",  "BAL"),
    (443, "Clarke Schmidt",             "SP",  "NYY"),
    (444, "Carmen Mlodzinski",          "RP",  "PIT"),
    (445, "Sean Burke",                 "SP",  "CHW"),
    (446, "Adael Amador",               "2B",  "COL"),
    (447, "Adrian Houser",              "SP",  "SF"),
    (448, "Jake Mangum",                "OF",  "PIT"),
    (449, "Michael McGreevy",           "SP",  "STL"),
    (450, "Jordan Leasure",             "RP",  "CHW"),
    (451, "Tyler Wells",                "SP",  "BAL"),
    (452, "Parker Meadows",             "OF",  "DET"),
    (453, "Carlos Narvaez",             "C",   "BOS"),
    (454, "Jorge Soler",                "OF",  "LAA"),
    (455, "Richard Fitts",              "SP",  "STL"),
    (456, "Justin Wrobleski",           "SP",  "LAD"),
    (457, "Kody Clemens",               "1B",  "MIN"),
    (458, "Ryan Mountcastle",           "1B",  "BAL"),
    (459, "Nathan Lukes",               "OF",  "TOR"),
    (460, "Alex Freeland",              "UT",  "LAD"),
    (461, "Garrett Mitchell",           "OF",  "MIL"),
    (462, "Alek Thomas",                "OF",  "ARI"),
    (463, "Clayton Beeter",             "RP",  "WSH"),
    (464, "Will Vest",                  "RP",  "DET"),
    (465, "Didier Fuentes",             "SP",  "ATL"),
    (466, "Mike Yastrzemski",           "OF",  "ATL"),
    (467, "Grant Holmes",               "SP",  "ATL"),
    (468, "Mason Montgomery",           "RP",  "PIT"),
    (469, "Zac Veen",                   "OF",  "COL"),
    (470, "Edouard Julien",             "1B",  "COL"),
    (471, "Ben Brown",                  "SP",  "CHC"),
    (472, "Justin Martinez",            "RP",  "ARI"),
    (473, "Miguel Andujar",             "3B",  "SD"),
    (474, "Luke Weaver",                "RP",  "NYM"),
    (475, "Brooks Baldwin",             "OF",  "CHW"),
    (476, "Eduardo Rodriguez",          "SP",  "ARI"),
    (477, "Brayan Rocchio",             "SS",  "CLE"),
    (478, "Javier Sanoja",              "3B",  "MIA"),
    (479, "Anthony Kay",                "SP",  "CHW"),
    (480, "Christopher Morel",          "OF",  "MIA"),
    (481, "Wenceel Perez",              "OF",  "DET"),
    (482, "Brandon Marsh",              "OF",  "PHI"),
    (483, "Davis Schneider",            "OF",  "TOR"),
    (484, "Hunter Gaddis",              "RP",  "CLE"),
    (485, "Ke'Bryan Hayes",             "3B",  "CIN"),
    (486, "Camilo Doval",               "RP",  "NYY"),
    (487, "Carson Kelly",               "C",   "CHC"),
    (488, "Kyle Finnegan",              "RP",  "DET"),
    (489, "Felix Bautista",             "RP",  "BAL"),
    (490, "Robert Hassell",             "OF",  "WSH"),
    (491, "Robert Stephenson",          "RP",  "LAA"),
    (492, "Thomas Saggese",             "2B",  "STL"),
    (493, "Victor Robles",              "OF",  "SEA"),
    (494, "Kyle Leahy",                 "RP",  "STL"),
    (495, "Sean Murphy",                "C",   "ATL"),
    (496, "Randy Rodriguez",            "RP",  "SF"),
    (497, "Jose Ferrer",                "RP",  "SEA"),
    (498, "Gabriel Arias",              "SS",  "CLE"),
    (499, "DJ Herz",                    "SP",  "WSH"),
    (500, "Drew Gilbert",               "OF",  "SF"),
]


def normalize(name):
    """Normalize name to ASCII lowercase, stripping suffixes and punctuation."""
    name = unicodedata.normalize("NFKD", name)
    name = name.encode("ascii", "ignore").decode("ascii")
    name = name.lower()
    name = re.sub(r"\b(jr|sr|ii|iii|iv|v)\b\.?", "", name)
    name = re.sub(r"[^a-z\s]", "", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name


def main():
    # Build draft lookup: normalized_name -> (pick, name, pos, team)
    # Use setdefault so first (better) pick wins for duplicate names.
    draft_lookup = {}
    for pick, name, pos, team in DRAFT_PICKS:
        key = normalize(name)
        draft_lookup.setdefault(key, (pick, name, pos, team))

    # Read master
    with open(MASTER_PATH, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = list(reader.fieldnames)
        rows = list(reader)

    # Check if column already exists
    if NEW_COL in fieldnames:
        print(f"Column '{NEW_COL}' already exists — updating values in place.")
        new_fieldnames = fieldnames
    else:
        avg_rank_idx = fieldnames.index("Average Rank")
        new_fieldnames = fieldnames[:avg_rank_idx] + [NEW_COL] + fieldnames[avg_rank_idx:]

    # Track matched keys
    matched_keys = set()

    # Update existing rows
    for row in rows:
        key = normalize(row["Player"])
        if key in draft_lookup:
            pick, _, _, _ = draft_lookup[key]
            row[NEW_COL] = pick
            matched_keys.add(key)
        else:
            if NEW_COL not in row:
                row[NEW_COL] = ""

    # Find unmatched draft picks
    unmatched = []
    for pick, name, pos, team in DRAFT_PICKS:
        key = normalize(name)
        if key not in matched_keys:
            unmatched.append((pick, name, pos, team))

    print(f"Matched: {len(matched_keys)} players")
    print(f"New players to add: {len(unmatched)}")
    for pick, name, pos, team in unmatched:
        print(f"  [{pick}] {name} ({pos}, {team})")

    # Add new rows for unmatched players
    for pick, name, pos, team in unmatched:
        new_row = {fn: "" for fn in new_fieldnames}
        new_row["Player"] = name
        new_row["Position"] = pos
        new_row["Team"] = team if team else ""
        new_row[NEW_COL] = pick
        rows.append(new_row)

    # Write back
    with open(MASTER_PATH, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=new_fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"\nWrote {len(rows)} rows to {MASTER_PATH}")

    # Recalculate
    print("\nRunning recalculate.py...")
    result = subprocess.run(
        ["python3", "scripts/recalculate.py", MASTER_PATH],
        capture_output=True, text=True
    )
    print(result.stdout)
    if result.stderr:
        print("STDERR:", result.stderr)


if __name__ == "__main__":
    main()
