import csv
import subprocess
import unicodedata
import re

MASTER = "baseball/baseball_rankings_master.csv"
OLD_COL = "Baseball America (May 2026)"
NEW_COL = "Baseball America (Jun 2026)"

RANKINGS = [
    (1, "Shohei Ohtani", "LAD", "TWP"),
    (2, "Juan Soto", "NYM", "OF"),
    (3, "Bobby Witt Jr.", "KC", "SS"),
    (4, "Paul Skenes", "PIT", "SP"),
    (5, "Corbin Carroll", "AZ", "OF"),
    (6, "Elly De La Cruz", "CIN", "SS"),
    (7, "Junior Caminero", "TB", "3B"),
    (8, "Konnor Griffin", "PIT", "SS"),
    (9, "Julio Rodriguez", "SEA", "OF"),
    (10, "Nick Kurtz", "ATH", "1B"),
    (11, "Jackson Chourio", "MIL", "OF"),
    (12, "James Wood", "WSH", "OF"),
    (13, "Yordan Alvarez", "HOU", "OF"),
    (14, "Aaron Judge", "NYY", "OF"),
    (15, "Jacob Misiorowski", "MIL", "SP"),
    (16, "Ronald Acuna Jr.", "ATL", "OF"),
    (17, "Cristopher Sanchez", "PHI", "SP"),
    (18, "Gunnar Henderson", "BAL", "SS"),
    (19, "Kevin McGonigle", "DET", "2B"),
    (20, "Jose Ramirez", "CLE", "3B"),
    (21, "Yoshinobu Yamamoto", "LAD", "SP"),
    (22, "Tarik Skubal", "DET", "SP"),
    (23, "Fernando Tatis Jr.", "SD", "OF"),
    (24, "Vladimir Guerrero Jr.", "TOR", "1B"),
    (25, "Jesus Made", "MIL", "SS"),
    (26, "Zach Neto", "LAA", "SS"),
    (27, "CJ Abrams", "WSH", "SS"),
    (28, "Cam Schlittler", "NYY", "SP"),
    (29, "Pete Crow-Armstrong", "CHC", "OF"),
    (30, "Logan Gilbert", "SEA", "SP"),
    (31, "JJ Wetherholt", "STL", "SS"),
    (32, "Bryce Harper", "PHI", "1B"),
    (33, "Chase Burns", "CIN", "SP"),
    (34, "Roman Anthony", "BOS", "OF"),
    (35, "Wyatt Langford", "TEX", "OF"),
    (36, "Oneil Cruz", "PIT", "OF"),
    (37, "Kyle Schwarber", "PHI", "OF"),
    (38, "Ben Rice", "NYY", "1B"),
    (39, "Nolan McLean", "NYM", "SP"),
    (40, "Ketel Marte", "AZ", "2B"),
    (41, "Garrett Crochet", "BOS", "SP"),
    (42, "Colt Emerson", "SEA", "SS"),
    (43, "Hunter Brown", "HOU", "SP"),
    (44, "Jazz Chisholm Jr.", "NYY", "2B"),
    (45, "Jackson Merrill", "SD", "OF"),
    (46, "Pete Alonso", "BAL", "1B"),
    (47, "Eury Perez", "MIA", "SP"),
    (48, "Bryan Woo", "SEA", "SP"),
    (49, "Francisco Lindor", "NYM", "SS"),
    (50, "Matt Olson", "ATL", "1B"),
    (51, "Josue De Paula", "LAD", "OF"),
    (52, "Sal Stewart", "CIN", "1B"),
    (53, "Joe Ryan", "MIN", "SP"),
    (54, "Riley Greene", "DET", "OF"),
    (55, "Kyle Tucker", "LAD", "OF"),
    (56, "Theo Gillen", "TB", "OF"),
    (57, "Trea Turner", "PHI", "SS"),
    (58, "George Kirby", "SEA", "SP"),
    (59, "Mason Miller", "SD", "RP"),
    (60, "Drake Baldwin", "ATL", "C"),
    (61, "Shea Langeliers", "ATH", "C"),
    (62, "Cal Raleigh", "SEA", "C"),
    (63, "Samuel Basallo", "BAL", "C"),
    (64, "Travis Bazzana", "CLE", "2B"),
    (65, "Brice Turang", "MIL", "2B"),
    (66, "William Contreras", "MIL", "C"),
    (67, "Tyler Soderstrom", "ATH", "1B"),
    (68, "Dylan Cease", "TOR", "SP"),
    (69, "Michael Harris II", "ATL", "OF"),
    (70, "Andy Pages", "LAD", "OF"),
    (71, "Mookie Betts", "LAD", "SS"),
    (72, "Franklin Arias", "BOS", "SS"),
    (73, "Corey Seager", "TEX", "SS"),
    (74, "Chris Sale", "ATL", "SP"),
    (75, "Leo De Vries", "ATH", "SS"),
    (76, "Randy Arozarena", "SEA", "OF"),
    (77, "Logan Webb", "SF", "SP"),
    (78, "Walker Jenkins", "MIN", "OF"),
    (79, "Carson Benge", "NYM", "OF"),
    (80, "Ralphy Velazquez", "CLE", "1B"),
    (81, "Jacob deGrom", "TEX", "SP"),
    (82, "Jackson Holliday", "BAL", "2B"),
    (83, "Rainiel Rodriguez", "STL", "C"),
    (84, "Freddie Freeman", "LAD", "1B"),
    (85, "Munetaka Murakami", "CWS", "3B"),
    (86, "Rafael Devers", "SF", "1B"),
    (87, "Jeremy Pena", "HOU", "SS"),
    (88, "Jesus Luzardo", "PHI", "SP"),
    (89, "A.J. Ewing", "NYM", "OF"),
    (90, "Josuar Gonzalez", "SF", "SS"),
    (91, "Kade Anderson", "SEA", "SP"),
    (92, "Josh Naylor", "SEA", "1B"),
    (93, "Hunter Greene", "CIN", "SP"),
    (94, "Payton Tolle", "BOS", "SP"),
    (95, "Byron Buxton", "MIN", "OF"),
    (96, "Chase DeLauter", "CLE", "OF"),
    (97, "Gerrit Cole", "NYY", "SP"),
    (98, "Sam Antonacci", "CWS", "OF"),
    (99, "Cade Smith", "CLE", "RP"),
    (100, "Max Fried", "NYY", "SP"),
    (101, "Bryce Eldridge", "SF", "1B"),
    (102, "Cody Bellinger", "NYY", "OF"),
    (103, "Jac Caglianone", "KC", "OF"),
    (104, "Eli Willits", "WSH", "SS"),
    (105, "Mike Sirota", "LAD", "OF"),
    (106, "Kyle Bradish", "BAL", "SP"),
    (107, "Mike Trout", "LAA", "OF"),
    (108, "Cam Smith", "HOU", "OF"),
    (109, "Geraldo Perdomo", "AZ", "SS"),
    (110, "Michael Busch", "CHC", "1B"),
    (111, "Kevin Gausman", "TOR", "SP"),
    (112, "Gavin Williams", "CLE", "SP"),
    (113, "Vinnie Pasquantino", "KC", "1B"),
    (114, "Jhoan Duran", "PHI", "RP"),
    (115, "Sebastian Walcott", "TEX", "SS"),
    (116, "Luke Keaschall", "MIN", "2B"),
    (117, "Zack Wheeler", "PHI", "SP"),
    (118, "Drew Rasmussen", "TB", "SP"),
    (119, "Andres Munoz", "SEA", "RP"),
    (120, "Jordan Walker", "STL", "OF"),
    (121, "Ryan Sloan", "SEA", "SP"),
    (122, "Ranger Suarez", "BOS", "SP"),
    (123, "Tyler Glasnow", "LAD", "SP"),
    (124, "Miguel Vargas", "CWS", "3B"),
    (125, "Kazuma Okamoto", "TOR", "3B"),
    (126, "Eric Hartman", "ATL", "OF"),
    (127, "Ivan Herrera", "STL", "C"),
    (128, "Braden Montgomery", "CWS", "OF"),
    (129, "Seiya Suzuki", "CHC", "OF"),
    (130, "Brent Rooker", "ATH", "OF"),
    (131, "Austin Riley", "ATL", "3B"),
    (132, "Seth Hernandez", "PIT", "SP"),
    (133, "Nico Hoerner", "CHC", "2B"),
    (134, "Willson Contreras", "BOS", "1B"),
    (135, "Manny Machado", "SD", "3B"),
    (136, "Hunter Goodman", "COL", "C"),
    (137, "Otto Lopez", "MIA", "SS"),
    (138, "Bryce Miller", "SEA", "SP"),
    (139, "Carter Jensen", "KC", "C"),
    (140, "Edward Florentino", "PIT", "OF"),
    (141, "Willy Adames", "SF", "SS"),
    (142, "Freddy Peralta", "NYM", "SP"),
    (143, "Framber Valdez", "DET", "SP"),
    (144, "Max Clark", "DET", "OF"),
    (145, "Francisco Alvarez", "NYM", "C"),
    (146, "Kyle Harrison", "MIL", "SP"),
    (147, "Jo Adell", "LAA", "OF"),
    (148, "Gage Jump", "ATH", "SP"),
    (149, "Maikel Garcia", "KC", "3B"),
    (150, "Jacob Wilson", "ATH", "SS"),
    (151, "Shane McClanahan", "TB", "SP"),
    (152, "Teoscar Hernandez", "LAD", "OF"),
    (153, "Will Smith", "LAD", "C"),
    (154, "Carlos Rodon", "NYY", "SP"),
    (155, "Ozzie Albies", "ATL", "2B"),
    (156, "MacKenzie Gore", "TEX", "SP"),
    (157, "Yandy Diaz", "TB", "1B"),
    (158, "Trey Yesavage", "TOR", "SP"),
    (159, "Luis Hernandez", "SF", "SS"),
    (160, "Spencer Strider", "ATL", "SP"),
    (161, "Brandon Lowe", "PIT", "2B"),
    (162, "Parker Messick", "CLE", "SP"),
    (163, "Colson Montgomery", "CWS", "SS"),
    (164, "Tanner Bibee", "CLE", "SP"),
    (165, "Noah Schultz", "CWS", "SP"),
    (166, "Christian Yelich", "MIL", "OF"),
    (167, "Emmet Sheehan", "LAD", "SP"),
    (168, "Blake Snell", "LAD", "SP"),
    (169, "Nick Lodolo", "CIN", "SP"),
    (170, "Joshua Baez", "STL", "OF"),
    (171, "Jarren Duran", "BOS", "OF"),
    (172, "Bo Bichette", "NYM", "SS"),
    (173, "Jonathan Aranda", "TB", "1B"),
    (174, "George Lombard Jr.", "NYY", "SS"),
    (175, "Braxton Ashcraft", "PIT", "SP"),
    (176, "Bubba Chandler", "PIT", "SP"),
    (177, "Eduardo Quintero", "LAD", "OF"),
    (178, "Caleb Bonemer", "CWS", "SS"),
    (179, "Wilyer Abreu", "BOS", "OF"),
    (180, "Arjun Nimmala", "TOR", "SS"),
    (181, "Addison Barger", "TOR", "3B"),
    (182, "Devin Fitz-Gerald", "WSH", "2B"),
    (183, "Jordan Lawlar", "AZ", "SS"),
    (184, "Jose Altuve", "HOU", "2B"),
    (185, "Ryan Waldschmidt", "AZ", "OF"),
    (186, "Luis Pena", "MIL", "SS"),
    (187, "Nathan Eovaldi", "TEX", "SP"),
    (188, "Shota Imanaga", "CHC", "SP"),
    (189, "Edward Cabrera", "CHC", "SP"),
    (190, "Spencer Schwellenbach", "ATL", "SP"),
    (191, "Jhonny Level", "SF", "SS"),
    (192, "Dylan Crews", "WSH", "OF"),
    (193, "Emmanuel Rodriguez", "MIN", "OF"),
    (194, "Sandy Alcantara", "MIA", "SP"),
    (195, "Kyle Manzardo", "CLE", "1B"),
    (196, "Zyhir Hope", "LAD", "OF"),
    (197, "Lazaro Montes", "SEA", "OF"),
    (198, "Ian Happ", "CHC", "OF"),
    (199, "Alex Bregman", "CHC", "3B"),
    (200, "Brandon Nimmo", "TEX", "OF"),
    (201, "Shane Baz", "BAL", "SP"),
    (202, "Mark Vientos", "NYM", "3B"),
    (203, "Isaac Paredes", "HOU", "3B"),
    (204, "Josiah Hartshorn", "CHC", "OF"),
    (205, "Xavier Edwards", "MIA", "2B"),
    (206, "Sonny Gray", "BOS", "SP"),
    (207, "Jared Jones", "PIT", "SP"),
    (208, "Henry Bolte", "ATH", "OF"),
    (209, "Seaver King", "WSH", "SS"),
    (210, "Jose Soriano", "LAA", "SP"),
    (211, "Matt Shaw", "CHC", "3B"),
    (212, "Anthony Eyanson", "BOS", "SP"),
    (213, "Matt Chapman", "SF", "3B"),
    (214, "Connelly Early", "BOS", "SP"),
    (215, "Dillon Dingler", "DET", "C"),
    (216, "Angel Genao", "CLE", "SS"),
    (217, "Brandon Woodruff", "MIL", "SP"),
    (218, "Daylen Lile", "WSH", "OF"),
    (219, "Michael King", "SD", "SP"),
    (220, "Edwin Diaz", "LAD", "RP"),
    (221, "Grayson Rodriguez", "LAA", "SP"),
    (222, "Alec Burleson", "STL", "1B"),
    (223, "Bryan Reynolds", "PIT", "OF"),
    (224, "Kyle Teel", "CWS", "C"),
    (225, "Kaelen Culpepper", "MIN", "SS"),
    (226, "Cole Ragans", "KC", "SP"),
    (227, "Roldy Brito", "COL", "OF"),
    (228, "Owen Caissie", "MIA", "OF"),
    (229, "Luis Lara", "MIL", "OF"),
    (230, "Adley Rutschman", "BAL", "C"),
    (231, "Reid Detmers", "LAA", "SP"),
    (232, "Dalton Rushing", "LAD", "C"),
    (233, "Josh Hammond", "KC", "SS"),
    (234, "Gabriel Moreno", "AZ", "C"),
    (235, "Ceddanne Rafaela", "BOS", "OF"),
    (236, "Aidan Miller", "PHI", "SS"),
    (237, "Gage Wood", "PHI", "SP"),
    (238, "Jojo Parker", "TOR", "SS"),
    (239, "Jordan Westburg", "BAL", "3B"),
    (240, "Andrew Painter", "PHI", "SP"),
    (241, "Xavier Neyens", "HOU", "SS"),
    (242, "Ryan Weathers", "NYY", "SP"),
    (243, "Emil Morales", "LAD", "SS"),
    (244, "Josh Adamczewski", "MIL", "OF"),
    (245, "Jack Leiter", "TEX", "SP"),
    (246, "Demetrio Crisantes", "AZ", "2B"),
    (247, "Jack Flaherty", "DET", "SP"),
    (248, "Josh Hader", "HOU", "RP"),
    (249, "Eugenio Suarez", "CIN", "3B"),
    (250, "Shane Bieber", "TOR", "SP"),
    (251, "Taylor Ward", "BAL", "OF"),
    (252, "Corbin Burnes", "AZ", "SP"),
    (253, "Masyn Winn", "STL", "SS"),
    (254, "Brody Hopkins", "TB", "SP"),
    (255, "Alejandro Kirk", "TOR", "C"),
    (256, "Steele Hall", "CIN", "SS"),
    (257, "Cooper Pratt", "MIL", "SS"),
    (258, "Yainer Diaz", "HOU", "C"),
    (259, "Kyle Stowers", "MIA", "OF"),
    (260, "Andrew Abbott", "CIN", "SP"),
    (261, "Karson Milbrandt", "MIA", "SP"),
    (262, "Alfredo Duno", "CIN", "C"),
    (263, "Grant Taylor", "CWS", "RP"),
    (264, "Heliot Ramos", "SF", "OF"),
    (265, "Carlos Lagrange", "NYY", "SP"),
    (266, "Will Warren", "NYY", "SP"),
    (267, "Taj Bradley", "MIN", "SP"),
    (268, "Bryson Stott", "PHI", "2B"),
    (269, "Jackson Jobe", "DET", "SP"),
    (270, "Ethan Salas", "SD", "C"),
    (271, "Max Muncy", "LAD", "3B"),
    (272, "Anthony Volpe", "NYY", "SS"),
    (273, "Matthew Boyd", "CHC", "SP"),
    (274, "Justin Gonzales", "BOS", "OF"),
    (275, "Daulton Varsho", "TOR", "OF"),
    (276, "Thomas White", "MIA", "SP"),
    (277, "Christian Scott", "NYM", "SP"),
    (278, "George Springer", "TOR", "OF"),
    (279, "Bryce Rainer", "DET", "SS"),
    (280, "Matt McLain", "CIN", "2B"),
    (281, "Colton Cowser", "BAL", "OF"),
    (282, "Ezequiel Tovar", "COL", "SS"),
    (283, "Roki Sasaki", "LAD", "SP"),
    (284, "Johnny King", "TOR", "SP"),
    (285, "Gleyber Torres", "DET", "2B"),
    (286, "Chandler Simpson", "TB", "OF"),
    (287, "Luis Robert Jr.", "NYM", "OF"),
    (288, "Juneiker Caceres", "CLE", "OF"),
    (289, "Casey Mize", "DET", "SP"),
    (290, "Coby Mayo", "BAL", "3B"),
    (291, "Brett Baty", "NYM", "3B"),
    (292, "Max Meyer", "MIA", "SP"),
    (293, "Josh Jung", "TEX", "3B"),
    (294, "Colt Keith", "DET", "2B"),
    (295, "Royce Lewis", "MIN", "3B"),
    (296, "Braylon Payne", "MIL", "OF"),
    (297, "Dylan Beavers", "BAL", "OF"),
    (298, "Marcelo Mayer", "BOS", "3B"),
    (299, "Luis Castillo", "SEA", "SP"),
    (300, "Dax Kilby", "NYY", "SS"),
    (301, "Aaron Nola", "PHI", "SP"),
    (302, "Agustin Ramirez", "MIA", "C"),
    (303, "Angeibel Gomez", "KC", "SS"),
    (304, "Devin Williams", "NYM", "RP"),
    (305, "Spencer Torkelson", "DET", "1B"),
    (306, "Luis Garcia Jr.", "WSH", "2B"),
    (307, "Xander Bogaerts", "SD", "2B"),
    (308, "AJ Smith-Shawver", "ATL", "SP"),
    (309, "Foster Griffin", "WSH", "SP"),
    (310, "Ronny Cruz", "WSH", "SS"),
    (311, "David Bednar", "NYY", "RP"),
    (312, "Cooper Flemming", "TB", "SS"),
    (313, "Louis Varland", "TOR", "RP"),
    (314, "Robbie Ray", "SF", "SP"),
    (315, "Taitn Gray", "TB", "1B"),
    (316, "Christian Zazueta", "LAD", "SP"),
    (317, "Mickey Moniak", "COL", "OF"),
    (318, "Lawrence Butler", "ATH", "OF"),
    (319, "Moises Ballesteros", "CHC", "C"),
    (320, "Zebby Matthews", "MIN", "SP"),
    (321, "Kerry Carpenter", "DET", "OF"),
    (322, "Alexander Frias", "MIL", "OF"),
    (323, "Kris Bubic", "KC", "SP"),
    (324, "Travis Sykora", "WSH", "SP"),
    (325, "Brendan Donovan", "SEA", "2B"),
    (326, "Charles Davalan", "LAD", "OF"),
    (327, "Caden Scarborough", "TEX", "SP"),
    (328, "Logan Henderson", "MIL", "SP"),
    (329, "Alec Bohm", "PHI", "3B"),
    (330, "Landen Roupp", "SF", "SP"),
    (331, "Justin Crawford", "PHI", "OF"),
    (332, "Griffin Jax", "TB", "RP"),
    (333, "Ethan Holliday", "COL", "SS"),
    (334, "Justin Wrobleski", "LAD", "SP"),
    (335, "Tate Southisene", "ATL", "SS"),
    (336, "Pedro Ramirez", "CHC", "3B"),
    (337, "River Ryan", "LAD", "SP"),
    (338, "Ryan Jeffers", "MIN", "C"),
    (339, "Cade Cavalli", "WSH", "SP"),
    (340, "Cooper Ingle", "CLE", "C"),
    (341, "Jakob Marsee", "MIA", "OF"),
    (342, "Ike Irish", "BAL", "1B"),
    (343, "Nolan Schanuel", "LAA", "1B"),
    (344, "Andrew Vaughn", "MIL", "1B"),
    (345, "Jung Hoo Lee", "SF", "OF"),
    (346, "Troy Melton", "DET", "SP"),
    (347, "Braylon Doughty", "CLE", "SP"),
    (348, "Christian Walker", "HOU", "1B"),
    (349, "Daniel Palencia", "CHC", "RP"),
    (350, "Enddy Azocar", "BOS", "OF"),
    (351, "Jeff Hoffman", "TOR", "RP"),
    (352, "Gavin Fien", "WSH", "SS"),
    (353, "Sal Frelick", "MIL", "OF"),
    (354, "Jonny Farmelo", "SEA", "OF"),
    (355, "Brandon Sproat", "MIL", "SP"),
    (356, "Dansby Swanson", "CHC", "SS"),
    (357, "Connor Prielipp", "MIN", "SP"),
    (358, "Aidan West", "LAD", "SS"),
    (359, "Jhomnardo Reyes", "MIN", "OF"),
    (360, "Pablo Lopez", "MIN", "SP"),
    (361, "Ryan Pepiot", "TB", "SP"),
    (362, "Aiva Arquette", "MIA", "SS"),
    (363, "Yohendrick Pinango", "TOR", "OF"),
    (364, "Charlie Condon", "COL", "OF"),
    (365, "Jefferson Rojas", "CHC", "SS"),
    (366, "Caleb Durbin", "BOS", "2B"),
    (367, "Evan Carter", "TEX", "OF"),
    (368, "Pete Fairbanks", "MIA", "RP"),
    (369, "TJ Rumfield", "COL", "1B"),
    (370, "Nathan Flewelling", "TB", "C"),
    (371, "Kane Kepley", "CHC", "OF"),
    (372, "Luis Arraez", "SF", "1B"),
    (373, "Ben Brown", "CHC", "SP"),
    (374, "Kevin Alvarez", "HOU", "OF"),
    (375, "Felnin Celesten", "SEA", "SS"),
    (376, "Caden Bodine", "TB", "C"),
    (377, "Kendry Chourio", "KC", "SP"),
    (378, "Tatsuya Imai", "HOU", "SP"),
    (379, "Steven Kwan", "CLE", "OF"),
    (380, "Joe Musgrove", "SD", "SP"),
    (381, "Jarlin Susana", "WSH", "SP"),
    (382, "Jasson Dominguez", "NYY", "OF"),
    (383, "Aroldis Chapman", "BOS", "RP"),
    (384, "Carlos Correa", "HOU", "SS"),
    (385, "Andrew Fischer", "MIL", "3B"),
    (386, "Jesus Sanchez", "TOR", "OF"),
    (387, "Trevor Rogers", "BAL", "SP"),
    (388, "Ryne Nelson", "AZ", "SP"),
    (389, "Noah Cameron", "KC", "SP"),
    (390, "Trevor Story", "BOS", "SS"),
    (391, "Eduardo Tait", "MIN", "C"),
    (392, "Austin Wells", "NYY", "C"),
    (393, "Tyler Bremner", "LAA", "SP"),
    (394, "Raisel Iglesias", "ATL", "RP"),
    (395, "Lars Nootbaar", "STL", "OF"),
    (396, "Jonah Tong", "NYM", "SP"),
    (397, "Salvador Perez", "KC", "C"),
    (398, "Chase Harlan", "LAD", "3B"),
    (399, "Bo Davidson", "SF", "OF"),
    (400, "Tanner Franklin", "STL", "SP"),
    (401, "Riley Quick", "MIN", "SP"),
    (402, "Carson Williams", "TB", "SS"),
    (403, "Brooks Lee", "MIN", "SS"),
    (404, "Justin Steele", "CHC", "SP"),
    (405, "Cole Young", "SEA", "2B"),
    (406, "Zac Gallen", "AZ", "SP"),
    (407, "Alejandro Osuna", "TEX", "OF"),
    (408, "JD Dix", "AZ", "SS"),
    (409, "Brandon Marsh", "PHI", "OF"),
    (410, "Didier Fuentes", "ATL", "SP"),
    (411, "Ryan Helsley", "BAL", "RP"),
    (412, "Spencer Steer", "CIN", "1B"),
    (413, "Jose Caballero", "NYY", "2B"),
    (414, "Quinn Priester", "MIL", "SP"),
    (415, "Luis Perales", "WSH", "SP"),
    (416, "Noelvi Marte", "CIN", "3B"),
    (417, "Jake Bennett", "BOS", "SP"),
    (418, "Joseph Dzierwa", "BAL", "SP"),
    (419, "JR Ritchie", "ATL", "SP"),
    (420, "Liam Doyle", "STL", "SP"),
    (421, "Kristian Campbell", "BOS", "OF"),
    (422, "Davis Martin", "CWS", "SP"),
    (423, "Dustin May", "STL", "SP"),
    (424, "Sean Burke", "CWS", "SP"),
    (425, "Joe Boyle", "TB", "SP"),
    (426, "Cam Caminiti", "ATL", "SP"),
    (427, "Cade Horton", "CHC", "SP"),
    (428, "Anderson Brito", "TB", "SP"),
    (429, "Mitch Keller", "PIT", "SP"),
    (430, "John Gil", "ATL", "SS"),
    (431, "Dominic Canzone", "SEA", "OF"),
    (432, "Kumar Rocker", "TEX", "SP"),
    (433, "Miguel Sime Jr.", "WSH", "SP"),
    (434, "Franklin Primera", "BOS", "C"),
    (435, "Hendry Mendez", "MIN", "OF"),
    (436, "Edwin Arroyo", "CIN", "SS"),
    (437, "Zach Root", "LAD", "SP"),
    (438, "Brice Matthews", "HOU", "SS"),
    (439, "Marcus Semien", "NYM", "2B"),
    (440, "Jake Bloss", "TOR", "SP"),
    (441, "Jake Burger", "TEX", "1B"),
    (442, "Jaxon Wiggins", "CHC", "SP"),
    (443, "Brenton Doyle", "COL", "OF"),
    (444, "Michael Arroyo", "SEA", "OF"),
    (445, "Jamie Arnold", "ATH", "SP"),
    (446, "Rhett Lowder", "CIN", "SP"),
    (447, "Jaison Chourio", "CLE", "OF"),
    (448, "Nolan Perry", "TOR", "SP"),
    (449, "Robby Snelling", "MIA", "SP"),
    (450, "Zack Gelof", "ATH", "2B"),
    (451, "Logan O'Hoppe", "LAA", "C"),
    (452, "Curtis Mead", "WSH", "1B"),
    (453, "Wei-En Lin", "ATH", "SP"),
    (454, "Andres Gimenez", "TOR", "2B"),
    (455, "Owen Murphy", "ATL", "SP"),
    (456, "Trevor Larnach", "MIN", "OF"),
    (457, "Tommy Edman", "LAD", "2B"),
    (458, "Robert Arias", "CLE", "OF"),
    (459, "Emerson Hancock", "SEA", "SP"),
    (460, "Emanuel Luna", "STL", "SS"),
    (461, "Spencer Horwitz", "PIT", "1B"),
    (462, "Francisco Renteria", "PHI", "OF"),
    (463, "Nick Pivetta", "SD", "SP"),
    (464, "JJ Bleday", "CIN", "OF"),
    (465, "Trent Grisham", "NYY", "OF"),
    (466, "Sebastian Dos Santos", "STL", "SS"),
    (467, "Kyson Witherspoon", "BOS", "SP"),
    (468, "Clay Holmes", "NYM", "SP"),
    (469, "Garrett Mitchell", "MIL", "OF"),
    (470, "Brady House", "WSH", "3B"),
    (471, "James Tibbs III", "LAD", "OF"),
    (472, "Blake Burke", "MIL", "1B"),
    (473, "Ryan Clifford", "NYM", "1B"),
    (474, "Juan Sanchez", "TOR", "SS"),
    (475, "Kodai Senga", "NYM", "SP"),
    (476, "Braxton Garrett", "MIA", "SP"),
    (477, "Chad Patrick", "MIL", "SP"),
    (478, "Henry Godbout", "BOS", "2B"),
    (479, "Grant Holmes", "ATL", "SP"),
    (480, "Tanner Scott", "LAD", "RP"),
    (481, "J.T. Realmuto", "PHI", "C"),
    (482, "Tommy Troy", "AZ", "OF"),
    (483, "Spencer Jones", "NYY", "OF"),
    (484, "Murf Gray", "PIT", "3B"),
    (485, "Coy James", "WSH", "SS"),
    (486, "Michael Soroka", "AZ", "SP"),
    (487, "Jake Bauers", "MIL", "1B"),
    (488, "Owen Ayers", "CHC", "C"),
    (489, "Mike Burrows", "HOU", "SP"),
    (490, "Chase Dollander", "COL", "SP"),
    (491, "Brayan Rocchio", "CLE", "SS"),
    (492, "Brady Singer", "CIN", "SP"),
    (493, "Brandon Pfaadt", "AZ", "SP"),
    (494, "Drew Gilbert", "SF", "OF"),
    (495, "Joey Cantillo", "CLE", "SP"),
    (496, "Jorge Soler", "LAA", "OF"),
    (497, "Giancarlo Stanton", "NYY", "OF"),
    (498, "Chase Meidroth", "CWS", "SS"),
    (499, "Josue Briceno", "DET", "C"),
    (500, "Isaac Collins", "KC", "OF"),
]


def normalize(name):
    name = unicodedata.normalize("NFKD", name)
    name = name.encode("ascii", "ignore").decode("ascii")
    name = name.lower()
    name = re.sub(r"\b(jr|sr|ii|iii|iv|v)\b\.?", "", name)
    name = re.sub(r"[^a-z\s]", "", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name


norm_rankings = {normalize(name): (rank, team, pos) for rank, name, team, pos in RANKINGS}

with open(MASTER, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    fieldnames = list(reader.fieldnames)
    rows = list(reader)

# Rename column
if OLD_COL in fieldnames:
    idx = fieldnames.index(OLD_COL)
    fieldnames[idx] = NEW_COL
    for row in rows:
        row[NEW_COL] = row.pop(OLD_COL)
    print(f"Renamed '{OLD_COL}' -> '{NEW_COL}'.")
elif NEW_COL not in fieldnames:
    insert_before = "Average Rank"
    idx = fieldnames.index(insert_before)
    fieldnames = fieldnames[:idx] + [NEW_COL] + fieldnames[idx:]
    print(f"Added new column '{NEW_COL}'.")

# Clear existing values for this source
for row in rows:
    row[NEW_COL] = ""

# Match existing players
existing_norm = {normalize(row["Player"]): row for row in rows}
matched = 0
unmatched = []
for rank, name, team, pos in RANKINGS:
    key = normalize(name)
    if key in existing_norm:
        existing_norm[key][NEW_COL] = rank
        matched += 1
    else:
        unmatched.append((rank, name, team, pos))

print(f"Matched {matched} / {len(RANKINGS)} players.")

# Add new players
for rank, name, team, pos in unmatched:
    new_row = {col: "" for col in fieldnames}
    new_row["Player"] = name
    new_row["Position"] = pos
    new_row["Team"] = team
    new_row[NEW_COL] = rank
    rows.append(new_row)
    print(f"  Added new player: {name} ({pos}, {team}) rank {rank}")

with open(MASTER, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print("Running recalculate.py...")
subprocess.run(["python3", "scripts/recalculate.py", MASTER], check=True)
print("Done.")
