import csv
import subprocess
import unicodedata
import re

MASTER = "baseball/baseball_rankings_master.csv"
OLD_COL = "HarryKnowsBall (Crowdsourced, May 2026)"
NEW_COL = "HarryKnowsBall (Crowdsourced, Jun 2026)"

# (rank, name, age, position, team, level) — draft pick slots (e.g. "2027 Early 1st") excluded.
# Two real players share the name "Max Muncy": the veteran Dodgers 3B (LAD) and the
# Athletics prospect (ATH). Matched explicitly by team below rather than by name alone.
RANKINGS = [
    (1, 'Shohei Ohtani', '31.9', 'SP', 'LAD', 'MLB'),
    (2, 'Bobby Witt Jr.', '26', 'SS', 'KC', 'MLB'),
    (3, 'Paul Skenes', '24.1', 'SP', 'PIT', 'MLB'),
    (4, 'Nick Kurtz', '23.3', '1B', 'ATH', 'MLB'),
    (5, 'Juan Soto', '27.7', 'OF', 'NYM', 'MLB'),
    (6, 'Elly De La Cruz', '24.5', 'SS', 'CIN', 'MLB'),
    (7, 'Corbin Carroll', '25.9', 'OF', 'AZ', 'MLB'),
    (8, 'Junior Caminero', '22.9', '3B', 'TB', 'MLB'),
    (9, 'James Wood', '23.8', 'OF', 'WSH', 'MLB'),
    (10, 'Jacob Misiorowski', '24.2', 'SP', 'MIL', 'MLB'),
    (11, 'Konnor Griffin', '20.2', 'SS', 'PIT', 'MLB'),
    (12, 'Jackson Chourio', '22.3', 'OF', 'MIL', 'MLB'),
    (13, 'Aaron Judge', '34.2', 'OF', 'NYY', 'MLB'),
    (14, 'Yordan Alvarez', '29', 'OF', 'HOU', 'MLB'),
    (15, 'Ronald Acuna Jr.', '28.5', 'OF', 'ATL', 'MLB'),
    (16, 'Tarik Skubal', '29.6', 'SP', 'DET', 'MLB'),
    (17, 'Julio Rodriguez', '25.5', 'OF', 'SEA', 'MLB'),
    (18, 'Cam Schlittler', '25.4', 'SP', 'NYY', 'MLB'),
    (19, 'Ben Rice', '27.4', 'C', 'NYY', 'MLB'),
    (20, 'Gunnar Henderson', '25', 'SS', 'BAL', 'MLB'),
    (21, 'Kevin McGonigle', '21.9', '3B', 'DET', 'MLB'),
    (22, 'Chase Burns', '23.5', 'SP', 'CIN', 'MLB'),
    (23, 'Vladimir Guerrero Jr.', '27.3', '1B', 'TOR', 'MLB'),
    (24, 'Yoshinobu Yamamoto', '27.9', 'SP', 'LAD', 'MLB'),
    (25, 'JJ Wetherholt', '23.8', '2B', 'STL', 'MLB'),
    (26, 'Cristopher Sanchez', '29.6', 'SP', 'PHI', 'MLB'),
    (27, 'Roman Anthony', '22.1', 'OF', 'BOS', 'MLB'),
    (28, 'Garrett Crochet', '27', 'SP', 'BOS', 'MLB'),
    (29, 'Drake Baldwin', '25.3', 'C', 'ATL', 'MLB'),
    (30, 'Jesus Made', '19.1', 'SS', 'MIL', 'AA'),
    (31, 'Bryan Woo', '26.4', 'SP', 'SEA', 'MLB'),
    (32, 'Hunter Brown', '27.8', 'SP', 'HOU', 'MLB'),
    (33, 'Nolan McLean', '24.9', 'SP', 'NYM', 'MLB'),
    (34, 'Fernando Tatis Jr.', '27.5', '2B', 'SD', 'MLB'),
    (35, 'Jose Ramirez', '33.8', '3B', 'CLE', 'MLB'),
    (36, 'CJ Abrams', '25.7', 'SS', 'WSH', 'MLB'),
    (37, 'Brice Turang', '26.6', '2B', 'MIL', 'MLB'),
    (38, 'Sal Stewart', '22.6', '1B', 'CIN', 'MLB'),
    (39, 'Pete Crow-Armstrong', '24.3', 'OF', 'CHC', 'MLB'),
    (40, 'Wyatt Langford', '24.6', 'OF', 'TEX', 'MLB'),
    (41, 'Kade Anderson', '21.9', 'SP', 'SEA', 'AA'),
    (42, 'Leo De Vries', '19.7', 'SS', 'ATH', 'AA'),
    (43, 'Kyle Tucker', '29.5', 'OF', 'LAD', 'MLB'),
    (44, 'Mason Miller', '27.9', 'RP', 'SD', 'MLB'),
    (45, 'Zach Neto', '25.4', 'SS', 'LAA', 'MLB'),
    (46, 'Trey Yesavage', '22.9', 'SP', 'TOR', 'MLB'),
    (47, 'Hunter Greene', '26.9', 'SP', 'CIN', 'AAA'),
    (48, 'Jordan Walker', '24.1', 'OF', 'STL', 'MLB'),
    (49, 'Samuel Basallo', '21.9', 'C', 'BAL', 'MLB'),
    (50, 'Logan Gilbert', '29.2', 'SP', 'SEA', 'MLB'),
    (51, 'Matt Olson', '32.3', '1B', 'ATL', 'MLB'),
    (52, 'Shea Langeliers', '28.6', 'C', 'ATH', 'MLB'),
    (53, 'Jackson Merrill', '23.2', 'OF', 'SD', 'MLB'),
    (54, 'Riley Greene', '25.8', 'OF', 'DET', 'MLB'),
    (55, 'Kyle Schwarber', '33.3', 'UT', 'PHI', 'MLB'),
    (56, 'Oneil Cruz', '27.7', 'OF', 'PIT', 'MLB'),
    (57, 'Travis Bazzana', '23.8', '2B', 'CLE', 'MLB'),
    (58, 'Munetaka Murakami', '26.4', '1B', 'CWS', 'MLB'),
    (59, 'Seth Hernandez', '20', 'SP', 'PIT', 'A+'),
    (60, 'George Kirby', '28.4', 'SP', 'SEA', 'MLB'),
    (61, 'Jazz Chisholm Jr.', '28.4', '2B', 'NYY', 'MLB'),
    (62, 'Payton Tolle', '23.7', 'SP', 'BOS', 'MLB'),
    (63, 'Jac Caglianone', '23.4', '1B', 'KC', 'MLB'),
    (64, 'Tyler Soderstrom', '24.6', '1B', 'ATH', 'MLB'),
    (65, 'Max Fried', '32.4', 'SP', 'NYY', 'MLB'),
    (66, 'Ketel Marte', '32.7', '2B', 'AZ', 'MLB'),
    (67, 'Maikel Garcia', '26.3', '2B', 'KC', 'MLB'),
    (68, 'Eury Perez', '23.2', 'SP', 'MIA', 'MLB'),
    (69, 'Joe Ryan', '30.1', 'SP', 'MIN', 'MLB'),
    (70, 'Logan Webb', '29.6', 'SP', 'SF', 'MLB'),
    (71, 'Bryce Eldridge', '21.7', 'UT', 'SF', 'MLB'),
    (72, 'Bryce Harper', '33.7', '1B', 'PHI', 'MLB'),
    (73, 'Cal Raleigh', '29.6', 'C', 'SEA', 'MLB'),
    (74, 'Colt Emerson', '20.9', '3B', 'SEA', 'MLB'),
    (75, 'Francisco Lindor', '32.6', 'SS', 'NYM', 'MLB'),
    (76, 'Gavin Williams', '26.9', 'SP', 'CLE', 'MLB'),
    (77, 'Chase DeLauter', '24.7', 'OF', 'CLE', 'MLB'),
    (78, 'Michael Harris II', '25.3', 'OF', 'ATL', 'MLB'),
    (79, 'Andy Pages', '25.6', 'OF', 'LAD', 'MLB'),
    (80, 'William Contreras', '28.5', 'C', 'MIL', 'MLB'),
    (81, 'Dylan Cease', '30.5', 'SP', 'TOR', 'MLB'),
    (82, 'Carter Jensen', '22.9', 'C', 'KC', 'MLB'),
    (83, 'Max Clark', '21.5', 'OF', 'DET', 'AAA'),
    (84, 'Pete Alonso', '31.6', '1B', 'BAL', 'MLB'),
    (85, 'Freddy Peralta', '30.1', 'SP', 'NYM', 'MLB'),
    (86, 'Kyle Harrison', '24.9', 'SP', 'MIL', 'MLB'),
    (87, 'Colson Montgomery', '24.3', '3B', 'CWS', 'MLB'),
    (88, 'Cole Ragans', '28.6', 'SP', 'KC', 'MLB'),
    (89, 'Spencer Schwellenbach', '26.1', 'SP', 'ATL', 'MLB'),
    (90, 'Sebastian Walcott', '20.3', 'SS', 'TEX', 'AA'),
    (91, 'Eli Willits', '18.6', 'SS', 'WSH', 'A+'),
    (92, 'Bubba Chandler', '23.8', 'SP', 'PIT', 'MLB'),
    (93, 'Josue De Paula', '21.1', 'OF', 'LAD', 'AA'),
    (94, 'Walker Jenkins', '21.4', 'OF', 'MIN', 'AAA'),
    (95, 'Connelly Early', '24.2', 'SP', 'BOS', 'MLB'),
    (96, 'Jesus Luzardo', '28.8', 'SP', 'PHI', 'MLB'),
    (97, 'Geraldo Perdomo', '26.7', 'SS', 'AZ', 'MLB'),
    (98, 'Hunter Goodman', '26.7', 'C', 'COL', 'MLB'),
    (99, 'Rafael Devers', '29.7', '1B', 'SF', 'MLB'),
    (100, 'Jackson Holliday', '22.6', '2B', 'BAL', 'MLB'),
    (101, 'Carson Benge', '23.4', 'OF', 'NYM', 'MLB'),
    (102, 'Austin Riley', '29.2', '3B', 'ATL', 'MLB'),
    (103, 'Parker Messick', '25.7', 'SP', 'CLE', 'MLB'),
    (104, 'Cody Bellinger', '30.9', 'OF', 'NYY', 'MLB'),
    (105, 'Spencer Strider', '27.7', 'SP', 'ATL', 'MLB'),
    (106, 'Jared Jones', '24.9', 'SP', 'PIT', 'MLB'),
    (107, 'Nico Hoerner', '29.1', '2B', 'CHC', 'MLB'),
    (108, 'Ivan Herrera', '26.1', 'C', 'STL', 'MLB'),
    (109, 'Noah Schultz', '22.9', 'SP', 'CWS', 'MLB'),
    (110, 'Braden Montgomery', '23.2', 'OF', 'CWS', 'MLB'),
    (111, 'Mookie Betts', '33.7', 'SS', 'LAD', 'MLB'),
    (112, 'Corey Seager', '32.2', 'SS', 'TEX', 'MLB'),
    (113, 'Luis Pena', '19.6', '2B', 'MIL', 'A+'),
    (114, 'Edward Florentino', '19.6', 'OF', 'PIT', 'A+'),
    (115, 'Thomas White', '21.8', 'SP', 'MIA', 'AAA'),
    (116, 'Bo Bichette', '28.3', '3B', 'NYM', 'MLB'),
    (117, 'Shane McClanahan', '29.2', 'SP', 'TB', 'MLB'),
    (118, 'Jose Soriano', '27.7', 'SP', 'LAA', 'MLB'),
    (119, 'Miguel Vargas', '26.6', '1B', 'CWS', 'MLB'),
    (120, 'Braxton Ashcraft', '26.7', 'SP', 'PIT', 'MLB'),
    (121, 'Robby Snelling', '22.5', 'SP', 'MIA', 'MLB'),
    (122, 'Byron Buxton', '32.5', 'OF', 'MIN', 'MLB'),
    (123, 'Trea Turner', '33', 'SS', 'PHI', 'MLB'),
    (124, 'Josh Naylor', '29', '1B', 'SEA', 'MLB'),
    (125, 'Jarren Duran', '29.8', 'OF', 'BOS', 'MLB'),
    (126, 'Jacob Wilson', '24.3', 'SS', 'ATH', 'MLB'),
    (127, 'Adley Rutschman', '28.4', 'C', 'BAL', 'MLB'),
    (128, 'Chris Sale', '37.3', 'SP', 'ATL', 'MLB'),
    (129, 'Bryce Miller', '27.9', 'SP', 'SEA', 'MLB'),
    (130, 'Emmet Sheehan', '26.6', 'SP', 'LAD', 'MLB'),
    (131, 'Jhoan Duran', '28.5', 'RP', 'PHI', 'MLB'),
    (132, 'MacKenzie Gore', '27.3', 'SP', 'TEX', 'MLB'),
    (133, 'Cade Horton', '24.9', 'SP', 'CHC', 'MLB'),
    (135, 'Xavier Edwards', '26.9', '2B', 'MIA', 'MLB'),
    (136, 'Ryan Waldschmidt', '23.7', 'OF', 'AZ', 'MLB'),
    (137, 'Jonathan Aranda', '28.1', '1B', 'TB', 'MLB'),
    (138, 'Logan Henderson', '24.3', 'SP', 'MIL', 'MLB'),
    (139, 'Jeremy Pena', '28.8', 'SS', 'HOU', 'MLB'),
    (140, 'Franklin Arias', '20.6', 'SS', 'BOS', 'AA'),
    (141, 'Sandy Alcantara', '30.8', 'SP', 'MIA', 'MLB'),
    (142, 'Ryan Sloan', '20.4', 'SP', 'SEA', 'AA'),
    (143, 'Michael Busch', '28.6', '1B', 'CHC', 'MLB'),
    (144, 'Emerson Hancock', '27.1', 'SP', 'SEA', 'MLB'),
    (145, 'Vinnie Pasquantino', '28.7', '1B', 'KC', 'MLB'),
    (146, 'Brent Rooker', '31.7', 'OF', 'ATH', 'MLB'),
    (147, 'Wilyer Abreu', '27', 'OF', 'BOS', 'MLB'),
    (148, 'Rainiel Rodriguez', '19.5', 'C', 'STL', 'AA'),
    (149, 'Dylan Crews', '24.3', 'OF', 'WSH', 'MLB'),
    (150, 'Luke Keaschall', '23.9', '2B', 'MIN', 'MLB'),
    (151, 'Zyhir Hope', '21.4', 'OF', 'LAD', 'AA'),
    (152, 'Andrew Painter', '23.2', 'SP', 'PHI', 'MLB'),
    (153, 'Nick Lodolo', '28.4', 'SP', 'CIN', 'MLB'),
    (155, 'Joshua Baez', '23', 'OF', 'STL', 'AAA'),
    (156, 'Michael King', '31.1', 'SP', 'SD', 'MLB'),
    (157, 'Zack Wheeler', '36.1', 'SP', 'PHI', 'MLB'),
    (158, 'Gage Jump', '23.2', 'SP', 'ATH', 'MLB'),
    (159, 'Cam Smith', '23.4', 'OF', 'HOU', 'MLB'),
    (160, 'Aidan Miller', '22.1', 'SS', 'PHI', 'AA'),
    (161, 'Ethan Holliday', '19.4', 'SS', 'COL', 'A'),
    (162, 'A.J. Ewing', '21.9', 'OF', 'NYM', 'MLB'),
    (163, 'Tyler Glasnow', '32.9', 'SP', 'LAD', 'MLB'),
    (164, 'George Lombard Jr.', '21.1', 'SS', 'NYY', 'AAA'),
    (165, 'Ozzie Albies', '29.5', '2B', 'ATL', 'MLB'),
    (166, 'Seiya Suzuki', '31.9', 'OF', 'CHC', 'MLB'),
    (167, 'Drew Rasmussen', '30.9', 'SP', 'TB', 'MLB'),
    (168, 'Dalton Rushing', '25.4', 'C', 'LAD', 'MLB'),
    (169, 'Dillon Dingler', '27.8', 'C', 'DET', 'MLB'),
    (170, 'Caleb Bonemer', '20.7', '3B', 'CWS', 'AA'),
    (171, 'Mike Trout', '34.9', 'OF', 'LAA', 'MLB'),
    (172, 'Roki Sasaki', '24.7', 'SP', 'LAD', 'MLB'),
    (173, 'Charlie Condon', '23.2', '1B', 'COL', 'AAA'),
    (174, 'Otto Lopez', '27.7', '2B', 'MIA', 'MLB'),
    (175, 'Max Meyer', '27.3', 'SP', 'MIA', 'MLB'),
    (176, 'Jonah Tong', '23', 'SP', 'NYM', 'MLB'),
    (177, 'Kazuma Okamoto', '30', '1B', 'TOR', 'MLB'),
    (178, 'Cade Smith', '27.1', 'RP', 'CLE', 'MLB'),
    (179, 'Moises Ballesteros', '22.6', 'UT', 'CHC', 'MLB'),
    (180, 'Ryan Weathers', '26.5', 'SP', 'NYY', 'MLB'),
    (181, 'Freddie Freeman', '36.8', '1B', 'LAD', 'MLB'),
    (182, 'Jordan Lawlar', '23.9', '3B', 'AZ', 'MLB'),
    (183, 'Taj Bradley', '25.3', 'SP', 'MIN', 'MLB'),
    (184, 'Framber Valdez', '32.6', 'SP', 'DET', 'MLB'),
    (185, 'Kris Bubic', '28.9', 'SP', 'KC', 'MLB'),
    (186, 'Randy Arozarena', '31.3', 'OF', 'SEA', 'MLB'),
    (187, 'Jasson Dominguez', '23.4', 'OF', 'NYY', 'MLB'),
    (188, 'Edward Cabrera', '28.2', 'SP', 'CHC', 'MLB'),
    (189, 'Manny Machado', '33.9', '3B', 'SD', 'MLB'),
    (190, 'Theo Gillen', '20.8', 'OF', 'TB', 'AA'),
    (191, 'Kyle Stowers', '28.5', '1B', 'MIA', 'MLB'),
    (192, 'Sam Antonacci', '23.4', '2B', 'CWS', 'MLB'),
    (193, 'Daylen Lile', '23.6', 'OF', 'WSH', 'MLB'),
    (194, 'Jackson Jobe', '23.9', 'SP', 'DET', 'MLB'),
    (195, 'Corbin Burnes', '31.7', 'SP', 'AZ', 'MLB'),
    (196, 'Will Warren', '27', 'SP', 'NYY', 'MLB'),
    (197, 'Eduardo Quintero', '20.8', 'OF', 'LAD', 'A+'),
    (198, 'Mike Sirota', '23', 'OF', 'LAD', 'AA'),
    (199, 'Kyle Bradish', '29.8', 'SP', 'BAL', 'MLB'),
    (200, 'Alex Bregman', '32.3', '3B', 'CHC', 'MLB'),
    (201, 'Lawrence Butler', '25.9', 'OF', 'ATH', 'MLB'),
    (202, 'Bryce Rainer', '20.9', 'SS', 'DET', 'A+'),
    (203, 'Ranger Suarez', '30.8', 'SP', 'BOS', 'MLB'),
    (204, 'Jo Adell', '27.2', 'OF', 'LAA', 'MLB'),
    (205, 'Alfredo Duno', '20.5', 'C', 'CIN', 'AA'),
    (206, 'JoJo Parker', '19.9', 'SS', 'TOR', 'A'),
    (207, 'Will Smith', '31.3', 'C', 'LAD', 'MLB'),
    (208, 'Kyle Teel', '24.4', 'C', 'CWS', 'MLB'),
    (209, 'Jacob deGrom', '38', 'SP', 'TEX', 'MLB'),
    (210, 'Didier Fuentes', '21', 'SP', 'ATL', 'MLB'),
    (211, 'Kaelen Culpepper', '23.5', 'SS', 'MIN', 'AAA'),
    (212, 'Brandon Lowe', '31.9', '2B', 'PIT', 'MLB'),
    (213, 'Andres Munoz', '27.5', 'RP', 'SEA', 'MLB'),
    (214, 'Cole Young', '22.9', '2B', 'SEA', 'MLB'),
    (215, 'Marcelo Mayer', '23.6', '2B', 'BOS', 'MLB'),
    (216, 'Blake Snell', '33.6', 'SP', 'LAD', 'MLB'),
    (217, 'Agustin Ramirez', '24.8', 'C', 'MIA', 'MLB'),
    (219, 'Jordan Westburg', '27.4', '2B', 'BAL', 'AAA'),
    (220, 'Anthony Eyanson', '21.7', 'SP', 'BOS', 'AA'),
    (221, 'Lazaro Montes', '21.7', 'OF', 'SEA', 'AA'),
    (222, 'Carlos Lagrange', '23.1', 'SP', 'NYY', 'AAA'),
    (223, 'Josuar Gonzalez', '18.7', 'SS', 'SF', 'ROK'),
    (224, 'Shota Imanaga', '32.8', 'SP', 'CHC', 'MLB'),
    (225, 'Owen Caissie', '23.9', 'OF', 'MIA', 'MLB'),
    (226, 'James Tibbs III', '23.7', 'OF', 'LAD', 'AAA'),
    (227, 'Justin Wrobleski', '25.9', 'SP', 'LAD', 'MLB'),
    (229, 'Emmanuel Rodriguez', '23.3', 'OF', 'MIN', 'AAA'),
    (230, 'Matt Shaw', '24.6', '3B', 'CHC', 'MLB'),
    (231, 'Liam Doyle', '22.1', 'SP', 'STL', 'AA'),
    (232, 'Spencer Arrighetti', '26.5', 'SP', 'HOU', 'MLB'),
    (233, 'Ceddanne Rafaela', '25.8', '2B', 'BOS', 'MLB'),
    (234, 'Chase Dollander', '24.7', 'SP', 'COL', 'MLB'),
    (235, 'Liam Hicks', '27.1', 'C', 'MIA', 'MLB'),
    (236, 'Jamie Arnold', '22.3', 'SP', 'ATH', 'AA'),
    (237, 'Alec Burleson', '27.6', '1B', 'STL', 'MLB'),
    (238, 'Andrew Fischer', '22.1', '3B', 'MIL', 'AA'),
    (239, 'Ralphy Velazquez', '21.1', '1B', 'CLE', 'AAA'),
    (240, 'Shane Baz', '27', 'SP', 'BAL', 'MLB'),
    (241, 'Justin Crawford', '22.5', 'OF', 'PHI', 'MLB'),
    (242, 'Henry Bolte', '22.9', 'OF', 'ATH', 'MLB'),
    (243, 'Gage Wood', '22.5', 'SP', 'PHI', 'AA'),
    (244, 'Gerrit Cole', '35.8', 'SP', 'NYY', 'MLB'),
    (245, 'Luis Hernandez', '17.5', 'SS', 'SF', 'ROK'),
    (246, 'Grant Taylor', '24.1', 'SP', 'CWS', 'MLB'),
    (247, 'Tanner Bibee', '27.3', 'SP', 'CLE', 'MLB'),
    (248, 'Chandler Simpson', '25.6', 'OF', 'TB', 'MLB'),
    (249, 'Ethan Salas', '20.1', 'C', 'SD', 'AA'),
    (250, 'Kevin Gausman', '35.5', 'SP', 'TOR', 'MLB'),
    (251, 'Casey Mize', '29.2', 'SP', 'DET', 'MLB'),
    (252, 'Troy Melton', '25.6', 'SP', 'DET', 'MLB'),
    (253, 'Cam Caminiti', '19.9', 'SP', 'ATL', 'A+'),
    (254, 'Yandy Diaz', '34.9', '1B', 'TB', 'MLB'),
    (255, 'Ian Happ', '31.9', 'OF', 'CHC', 'MLB'),
    (256, 'Travis Sykora', '22.2', 'SP', 'WSH', 'ROK'),
    (258, 'Matt McLain', '26.9', '2B', 'CIN', 'MLB'),
    (259, 'Luis Lara', '21.6', 'OF', 'MIL', 'AAA'),
    (260, 'Kendry Chourio', '18.7', 'SP', 'KC', 'A+'),
    (261, 'Andrew Abbott', '27.1', 'SP', 'CIN', 'MLB'),
    (262, 'Ben Brown', '26.8', 'SP', 'CHC', 'MLB'),
    (263, 'Francisco Alvarez', '24.6', 'C', 'NYM', 'MLB'),
    (264, 'Hagen Smith', '22.9', 'SP', 'CWS', 'AAA'),
    (265, 'Tatsuya Imai', '28.1', 'SP', 'HOU', 'MLB'),
    (266, 'Spencer Jones', '25.1', 'OF', 'NYY', 'MLB'),
    (267, 'Emil Morales', '19.8', 'SS', 'LAD', 'A+'),
    (268, 'Mick Abel', '24.9', 'SP', 'MIN', 'MLB'),
    (269, 'Spencer Torkelson', '26.8', '1B', 'DET', 'MLB'),
    (270, 'Mickey Moniak', '28.1', 'OF', 'COL', 'MLB'),
    (271, 'Willson Contreras', '34.1', '1B', 'BOS', 'MLB'),
    (272, 'Jett Williams', '22.7', '2B', 'MIL', 'AAA'),
    (273, 'Tyler Bremner', '22.2', 'SP', 'LAA', 'A+'),
    (274, 'Brendan Donovan', '29.5', '2B', 'SEA', 'MLB'),
    (275, 'Edwin Arroyo', '22.8', '2B', 'CIN', 'MLB'),
    (276, 'Jack Leiter', '26.2', 'SP', 'TEX', 'MLB'),
    (277, 'Hurston Waldrep', '24.3', 'SP', 'ATL', 'MLB'),
    (278, 'J.R. Ritchie', '23', 'SP', 'ATL', 'MLB'),
    (279, 'Devin Fitz-Gerald', '20.9', 'SS', 'WSH', 'AA'),
    (280, 'Trevor Rogers', '28.6', 'SP', 'BAL', 'MLB'),
    (281, 'Edwin Diaz', '32.3', 'RP', 'LAD', 'MLB'),
    (282, 'Reid Detmers', '26.9', 'SP', 'LAA', 'MLB'),
    (283, 'Dax Kilby', '19.6', 'SS', 'NYY', 'ROK'),
    (284, 'Steven Kwan', '28.8', 'OF', 'CLE', 'MLB'),
    (285, 'Aiva Arquette', '22.7', 'SS', 'MIA', 'AA'),
    (286, 'Jhonny Level', '19.3', 'SS', 'SF', 'A+'),
    (287, 'Christian Yelich', '34.6', 'OF', 'MIL', 'MLB'),
    (288, 'Brandon Sproat', '25.8', 'SP', 'MIL', 'MLB'),
    (289, 'Esmerlyn Valdez', '22.4', 'OF', 'PIT', 'MLB'),
    (290, 'Josh Hader', '32.2', 'RP', 'HOU', 'MLB'),
    (291, 'Josh Jung', '28.4', '3B', 'TEX', 'MLB'),
    (292, 'Rhett Lowder', '24.3', 'SP', 'CIN', 'MLB'),
    (293, 'Cooper Pratt', '21.9', 'SS', 'MIL', 'MLB'),
    (294, 'Kyson Witherspoon', '21.9', 'SP', 'BOS', 'A+'),
    (295, 'Bryan Reynolds', '31.4', 'OF', 'PIT', 'MLB'),
    (296, 'Isaac Paredes', '27.4', '1B', 'HOU', 'MLB'),
    (298, 'Ethan Conrad', '21.9', 'OF', 'CHC', 'ROK'),
    (299, 'Jarlin Susana', '22.3', 'SP', 'WSH', 'AA'),
    (300, 'Landen Roupp', '27.8', 'SP', 'SF', 'MLB'),
    (301, 'Karson Milbrandt', '22.2', 'SP', 'MIA', 'AAA'),
    (302, 'Luis Robert Jr.', '28.9', 'OF', 'NYM', 'MLB'),
    (303, 'Noelvi Marte', '24.7', '3B', 'CIN', 'MLB'),
    (304, 'Willy Adames', '30.8', 'SS', 'SF', 'MLB'),
    (305, 'Carlos Rodon', '33.6', 'SP', 'NYY', 'MLB'),
    (306, 'Kyle Manzardo', '25.9', '1B', 'CLE', 'MLB'),
    (307, 'Josue Briceno', '21.8', 'C', 'DET', 'A'),
    (308, 'Elmer Rodriguez-Cruz', '22.9', 'SP', 'NYY', 'MLB'),
    (309, 'Dylan Beavers', '24.9', 'OF', 'BAL', 'MLB'),
    (310, 'Bryce Elder', '27.1', 'SP', 'ATL', 'MLB'),
    (311, 'AJ Smith-Shawver', '23.6', 'SP', 'ATL', 'A'),
    (312, 'Steele Hall', '18.9', 'SS', 'CIN', 'ROK'),
    (313, 'Noah Cameron', '26.9', 'SP', 'KC', 'MLB'),
    (314, 'Eric Hartman', '20', '2B', 'ATL', 'A+'),
    (315, 'Abner Uribe', '26', 'RP', 'MIL', 'MLB'),
    (316, 'Christian Scott', '27', 'SP', 'NYM', 'MLB'),
    (317, 'Braylon Payne', '19.9', 'OF', 'MIL', 'A+'),
    (318, 'Kerry Carpenter', '28.8', 'OF', 'DET', 'MLB'),
    (319, 'Jakob Marsee', '25', 'OF', 'MIA', 'MLB'),
    (320, 'Cade Cavalli', '27.9', 'SP', 'WSH', 'MLB'),
    (321, 'Joey Cantillo', '26.5', 'SP', 'CLE', 'MLB'),
    (322, 'Max Muncy', '23.8', '2B', 'ATH', 'MLB'),
    (323, 'Casey Schmitt', '27.3', '1B', 'SF', 'MLB'),
    (324, 'Caden Scarborough', '21.2', 'SP', 'TEX', 'A+'),
    (325, 'Zebby Matthews', '26.1', 'SP', 'MIN', 'MLB'),
    (326, 'Ryan Pepiot', '28.9', 'SP', 'TB', 'MLB'),
    (327, 'Pedro Ramirez', '22.2', '2B', 'CHC', 'MLB'),
    (328, 'Arjun Nimmala', '20.7', 'SS', 'TOR', 'AA'),
    (329, 'Pablo Lopez', '30.3', 'SP', 'MIN', 'AAA'),
    (330, 'Jung Hoo Lee', '27.9', 'OF', 'SF', 'MLB'),
    (331, 'Daniel Palencia', '26.4', 'RP', 'CHC', 'MLB'),
    (332, 'Heliot Ramos', '26.8', 'OF', 'SF', 'MLB'),
    (333, 'Colt Keith', '24.9', '1B', 'DET', 'MLB'),
    (334, 'Jonny Farmelo', '21.8', 'OF', 'SEA', 'A+'),
    (335, 'Spencer Steer', '28.6', '1B', 'CIN', 'MLB'),
    (336, 'Royce Lewis', '27.1', '1B', 'MIN', 'MLB'),
    (337, 'Brandon Woodruff', '33.4', 'SP', 'MIL', 'MLB'),
    (338, 'Addison Barger', '26.6', '3B', 'TOR', 'MLB'),
    (339, 'Felnin Celesten', '20.8', 'SS', 'SEA', 'A+'),
    (340, 'Luis Garcia Jr.', '26.1', '1B', 'WSH', 'MLB'),
    (341, 'Louis Varland', '28.6', 'RP', 'TOR', 'MLB'),
    (342, 'Masyn Winn', '24.3', 'SS', 'STL', 'MLB'),
    (343, 'Chase Meidroth', '24.9', '2B', 'CWS', 'MLB'),
    (344, 'Andrew Vaughn', '28.2', '1B', 'MIL', 'MLB'),
    (345, 'Christian Moore', '23.7', '2B', 'LAA', 'MLB'),
    (346, 'Shane Bieber', '31.1', 'SP', 'TOR', 'MLB'),
    (347, 'Quinn Priester', '25.8', 'SP', 'MIL', 'AAA'),
    (348, 'Gabriel Moreno', '26.4', 'C', 'AZ', 'MLB'),
    (349, 'Evan Carter', '23.8', 'OF', 'TEX', 'MLB'),
    (350, 'Zack Gelof', '26.7', '2B', 'ATH', 'MLB'),
    (351, 'Coby Mayo', '24.6', '1B', 'BAL', 'MLB'),
    (352, 'Jaison Chourio', '21.1', 'OF', 'CLE', 'AA'),
    (353, 'Cole Carrigg', '24.1', 'OF', 'COL', 'MLB'),
    (354, 'Brady House', '23.1', '3B', 'WSH', 'MLB'),
    (355, 'Daulton Varsho', '29.9', 'OF', 'TOR', 'MLB'),
    (356, 'Sonny Gray', '36.6', 'SP', 'BOS', 'MLB'),
    (357, 'Michael Arroyo', '21.7', '2B', 'SEA', 'AA'),
    (358, 'Kevin Alcantara', '23.9', 'OF', 'CHC', 'MLB'),
    (359, 'Seaver King', '23.2', 'SS', 'WSH', 'AAA'),
    (360, 'Justin Steele', '30.9', 'SP', 'CHC', 'MLB'),
    (361, 'Xavier Neyens', '19.7', '3B', 'HOU', 'A'),
    (362, 'Luis Arraez', '29.2', '1B', 'SF', 'MLB'),
    (363, 'River Ryan', '27.9', 'SP', 'LAD', 'AAA'),
    (364, 'Kruz Schoolcraft', '19.2', 'SP', 'SD', 'A'),
    (365, 'Blaze Jordan', '23.5', '1B', 'STL', 'MLB'),
    (366, 'Devin Williams', '31.8', 'RP', 'NYM', 'MLB'),
    (367, 'JJ Bleday', '28.6', 'OF', 'CIN', 'MLB'),
    (368, 'Angel Martinez', '24.4', '2B', 'CLE', 'MLB'),
    (369, 'Nathan Eovaldi', '36.4', 'SP', 'TEX', 'MLB'),
    (370, 'Kayson Cunningham', '20', 'SS', 'AZ', 'A+'),
    (371, 'Connor Prielipp', '25.5', 'SP', 'MIN', 'MLB'),
    (372, 'Joe Mack', '23.5', 'C', 'MIA', 'MLB'),
    (373, 'Jefferson Rojas', '21.2', '2B', 'CHC', 'AA'),
    (374, 'Jaxon Wiggins', '24.7', 'SP', 'CHC', 'AAA'),
    (376, 'Carson Williams', '23', 'SS', 'TB', 'MLB'),
    (377, 'Justin Gonzales', '19.5', 'OF', 'BOS', 'A+'),
    (378, 'Taylor Ward', '32.5', 'OF', 'BAL', 'MLB'),
    (379, 'Nick Pivetta', '33.4', 'SP', 'SD', 'MLB'),
    (380, 'Teoscar Hernandez', '33.7', 'OF', 'LAD', 'MLB'),
    (381, 'Dominic Canzone', '28.9', 'OF', 'SEA', 'MLB'),
    (382, 'Jack Wenninger', '24.3', 'SP', 'NYM', 'AAA'),
    (383, 'Brandon Nimmo', '33.3', 'OF', 'TEX', 'MLB'),
    (384, 'Johnny King', '19.9', 'SP', 'TOR', 'A+'),
    (385, 'Ryne Nelson', '28.4', 'SP', 'AZ', 'MLB'),
    (386, 'Michael Soroka', '28.9', 'SP', 'AZ', 'MLB'),
    (387, 'Ezequiel Tovar', '24.9', 'SS', 'COL', 'MLB'),
    (388, 'Kash Mayfield', '21.4', 'SP', 'SD', 'A+'),
    (389, 'Tanner McDougal', '23.2', 'SP', 'CWS', 'AAA'),
    (390, 'Dansby Swanson', '32.4', 'SS', 'CHC', 'MLB'),
    (391, 'Colton Cowser', '26.3', 'OF', 'BAL', 'MLB'),
    (392, 'Brooks Lee', '25.4', '2B', 'MIN', 'MLB'),
    (393, 'Kristian Campbell', '24', '2B', 'BOS', 'AAA'),
    (394, 'Anthony Volpe', '25.2', 'SS', 'NYY', 'MLB'),
    (395, 'Kumar Rocker', '26.6', 'SP', 'TEX', 'MLB'),
    (396, 'Grayson Rodriguez', '26.6', 'SP', 'LAA', 'MLB'),
    (397, 'Robbie Ray', '34.7', 'SP', 'SF', 'MLB'),
    (398, 'Brody Hopkins', '24.4', 'SP', 'TB', 'AAA'),
    (399, 'Angel Genao', '22.1', '3B', 'CLE', 'AAA'),
    (400, 'Xavier Isaac', '22.5', 'UT', 'TB', 'AA'),
    (401, 'Matt Chapman', '33.2', '3B', 'SF', 'MLB'),
    (402, 'Tommy White', '23.3', '3B', 'ATH', 'AAA'),
    (403, 'Ike Irish', '22.6', 'C', 'BAL', 'A+'),
    (404, 'Ronny Cruz', '19.9', 'SS', 'WSH', 'A+'),
    (405, 'David Bednar', '31.7', 'RP', 'NYY', 'MLB'),
    (406, 'Gavin Fien', '19.3', '3B', 'WSH', 'A'),
    (407, 'Gleyber Torres', '29.5', '2B', 'DET', 'MLB'),
    (408, 'Sal Frelick', '26.2', 'OF', 'MIL', 'MLB'),
    (409, 'Aroldis Chapman', '38.3', 'RP', 'BOS', 'MLB'),
    (410, 'Nate George', '20.1', 'OF', 'BAL', 'A+'),
    (411, 'Michael McGreevy', '25.9', 'SP', 'STL', 'MLB'),
    (412, 'Garrett Mitchell', '27.8', 'OF', 'MIL', 'MLB'),
    (413, 'Reese Olson', '26.9', 'SP', 'DET', 'AAA'),
    (415, 'Max Muncy', '35.8', '3B', 'LAD', 'MLB'),
    (416, 'Jurrangelo Cijntje', '23.1', 'SP', 'STL', 'AA'),
    (417, 'Nolan Schanuel', '24.4', '1B', 'LAA', 'MLB'),
    (418, 'Matthew Liberatore', '26.6', 'SP', 'STL', 'MLB'),
    (419, 'Ryan Clifford', '22.9', '1B', 'NYM', 'AAA'),
    (420, 'Ryan Helsley', '31.9', 'RP', 'BAL', 'MLB'),
    (421, 'Elian Pena', '18.7', 'SS', 'NYM', 'A'),
    (422, 'Joseph Dzierwa', '22.2', 'SP', 'BAL', 'AA'),
    (423, 'Josiah Hartshorn', '19.4', '1B', 'CHC', 'A+'),
    (424, 'Yainer Diaz', '27.8', 'C', 'HOU', 'MLB'),
    (425, 'Hector Rodriguez', '22.3', 'OF', 'CIN', 'AAA'),
    (426, 'Taitn Gray', '18.9', 'C', 'TB', 'A'),
    (427, 'Brandon Marsh', '28.5', 'OF', 'PHI', 'MLB'),
    (428, 'Christian Walker', '35.3', '1B', 'HOU', 'MLB'),
    (429, 'Kendry Rojas', '23.6', 'SP', 'MIN', 'MLB'),
    (430, 'Trent Grisham', '29.7', 'OF', 'NYY', 'MLB'),
    (431, 'Tommy Troy', '24.5', '2B', 'AZ', 'MLB'),
    (432, 'Bryson Stott', '28.7', '2B', 'PHI', 'MLB'),
    (433, 'Clay Holmes', '33.3', 'SP', 'NYM', 'MLB'),
    (434, 'Sean Burke', '26.5', 'SP', 'CWS', 'MLB'),
    (435, "Ryan O'Hearn", '32.9', '1B', 'PIT', 'MLB'),
    (436, 'Mitch Keller', '30.2', 'SP', 'PIT', 'MLB'),
    (437, 'Griffin Jax', '31.6', 'SP', 'TB', 'MLB'),
    (438, 'Braxton Garrett', '28.9', 'SP', 'MIA', 'MLB'),
    (439, 'Eduardo Tait', '19.8', 'C', 'MIN', 'A+'),
    (440, 'Juan Sanchez', '18.8', '3B', 'TOR', 'A'),
    (441, 'Alejandro Kirk', '27.6', 'C', 'TOR', 'MLB'),
    (442, 'Eugenio Suarez', '34.9', '3B', 'CIN', 'MLB'),
    (443, 'Kevin Alvarez', '18.5', 'OF', 'HOU', 'A'),
    (444, 'Jacob Reimer', '22.4', '3B', 'NYM', 'AA'),
    (445, 'Garrett Whitlock', '30.1', 'RP', 'BOS', 'MLB'),
    (446, 'Josh Hammond', '19.8', '3B', 'KC', 'A'),
    (448, 'Zac Veen', '24.6', 'OF', 'COL', 'AAA'),
    (449, 'Cooper Ingle', '24.4', 'C', 'CLE', 'MLB'),
    (450, 'Jose Altuve', '36.2', '2B', 'HOU', 'MLB'),
    (451, 'Cam Collier', '21.6', '1B', 'CIN', 'AA'),
    (452, 'Jose Fernandez', '22.8', '1B', 'AZ', 'MLB'),
    (453, 'Michael Forret', '22.2', 'SP', 'TB', 'AAA'),
    (455, 'Jhostynxon Garcia', '23.6', 'OF', 'PIT', 'MLB'),
    (456, 'Davis Martin', '29.5', 'SP', 'CWS', 'MLB'),
    (457, 'Caleb Durbin', '26.4', '2B', 'BOS', 'MLB'),
    (458, 'Alex Freeland', '24.9', '2B', 'LAD', 'MLB'),
    (459, 'Carlos Correa', '31.8', '3B', 'HOU', 'MLB'),
    (460, 'Jeferson Quero', '23.7', 'C', 'MIL', 'MLB'),
    (461, 'Trey Gibson', '24.1', 'SP', 'BAL', 'MLB'),
    (462, 'Randy Vasquez', '27.7', 'SP', 'SD', 'MLB'),
    (463, 'Juneiker Caceres', '18.9', 'OF', 'CLE', 'A'),
    (464, 'T.J. Rumfield', '25', '1B', 'COL', ''),
    (465, 'Brayan Bello', '27.1', 'SP', 'BOS', 'MLB'),
    (466, 'Zac Gallen', '30.9', 'SP', 'AZ', 'MLB'),
    (467, 'Chad Patrick', '27.9', 'SP', 'MIL', 'MLB'),
    (468, 'Mark Vientos', '26.6', '1B', 'NYM', 'MLB'),
    (469, 'Ernie Clement', '30.3', '1B', 'TOR', 'MLB'),
    (470, 'Jacob Melton', '25.8', 'OF', 'TB', 'AAA'),
    (471, 'Gavin Kilen', '22.3', 'SS', 'SF', 'A+'),
    (472, 'Spencer Horwitz', '28.6', '1B', 'PIT', 'MLB'),
    (473, 'Luis Morales', '23.8', 'SP', 'ATH', 'MLB'),
    (474, 'Quinn Mathews', '25.7', 'SP', 'STL', 'AAA'),
    (475, 'Wei-En Lin', '20.7', 'SP', 'ATH', 'AAA'),
    (476, 'Aroon Escobar', '21.5', '2B', 'PHI', 'AA'),
    (477, 'Jacob Gonzalez', '24.1', '1B', 'CWS', 'MLB'),
    (478, 'George Springer', '36.8', 'OF', 'TOR', 'MLB'),
    (479, 'Shane Smith', '26.2', 'SP', 'CWS', 'MLB'),
    (481, 'Curtis Mead', '25.7', '1B', 'CWS', 'MLB'),
    (482, 'Brayan Rocchio', '25.5', '2B', 'CLE', 'MLB'),
    (483, "Logan O'Hoppe", '26.4', 'C', 'LAA', 'MLB'),
    (484, 'Joe Boyle', '26.9', 'SP', 'TB', 'MLB'),
    (485, 'Brett Baty', '26.6', '1B', 'NYM', 'MLB'),
    (486, 'Luis Castillo', '33.6', 'SP', 'SEA', 'MLB'),
    (487, 'Owen Murphy', '22.8', 'SP', 'ATL', 'AAA'),
    (488, 'Andres Gimenez', '27.8', '2B', 'TOR', 'MLB'),
    (489, 'Jace LaViolette', '22.6', 'OF', 'CLE', 'A+'),
    (490, 'Chase Petty', '23.2', 'SP', 'CIN', 'MLB'),
    (491, 'Aaron Nola', '33.1', 'SP', 'PHI', 'MLB'),
    (492, 'Noble Meyer', '21.5', 'SP', 'MIA', 'A'),
    (493, 'Bailey Ober', '30.9', 'SP', 'MIN', 'MLB'),
    (494, 'Billy Carlson', '19.9', 'SS', 'CWS', 'A'),
    (495, 'John Gil', '20.1', 'SS', 'ATL', 'A+'),
    (496, 'Josh Adamczewski', '21.1', 'SS', 'MIL', 'AA'),
    (497, 'Walbert Urena', '22.4', 'SP', 'LAA', 'MLB'),
    (498, 'Ryan Jeffers', '29.1', 'C', 'MIN', 'MLB'),
    (499, 'Jordan Beck', '25.2', 'OF', 'COL', 'MLB'),
]


def normalize(name):
    name = unicodedata.normalize("NFKD", name)
    name = name.encode("ascii", "ignore").decode("ascii")
    name = name.lower()
    name = re.sub(r"\b(jr|sr|ii|iii|iv|v)\b\.?", "", name)
    name = re.sub(r"[^a-z\s]", "", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name


with open(MASTER, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    fieldnames = list(reader.fieldnames)
    rows = list(reader)

# Rename column
if OLD_COL in fieldnames:
    idx = fieldnames.index(OLD_COL)
    fieldnames[idx] = NEW_COL
    for row in rows:
        row[NEW_COL] = row.pop(OLD_COL)
    print(f"Renamed '{OLD_COL}' -> '{NEW_COL}'.")
elif NEW_COL not in fieldnames:
    insert_before = "Average Rank"
    idx = fieldnames.index(insert_before)
    fieldnames = fieldnames[:idx] + [NEW_COL] + fieldnames[idx:]
    print(f"Added new column '{NEW_COL}'.")

# Clear existing values for this source
for row in rows:
    row[NEW_COL] = ""

existing_norm = {}
for row in rows:
    key = normalize(row["Player"])
    if key == "max muncy":
        continue  # handled explicitly by team below
    existing_norm[key] = row

max_muncy_lad = next(r for r in rows if r["Player"] == "Max Muncy" and r["Team"] == "LAD")

matched = 0
unmatched = []
for rank, name, age, pos, team, level in RANKINGS:
    key = normalize(name)
    if key == "max muncy":
        target = max_muncy_lad if team == "LAD" else None
    else:
        target = existing_norm.get(key)

    if target is not None:
        target[NEW_COL] = rank
        if not target["Age"].strip():
            target["Age"] = age
        if not target["Level"].strip():
            target["Level"] = level
        matched += 1
    else:
        unmatched.append((rank, name, age, pos, team, level))

print(f"Matched {matched} / {len(RANKINGS)} players.")

# Add new players
for rank, name, age, pos, team, level in unmatched:
    new_row = {col: "" for col in fieldnames}
    new_row["Player"] = name
    new_row["Position"] = pos
    new_row["Team"] = team
    new_row["Age"] = age
    new_row["Level"] = level
    new_row[NEW_COL] = rank
    rows.append(new_row)
    print(f"  Added new player: {name} ({pos}, {team}) rank {rank}")

with open(MASTER, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print("Running recalculate.py...")
subprocess.run(["python3", "scripts/recalculate.py", MASTER], check=True)
print("Done.")
